.gitignore
package-lock.json
package.json

PR contains following changes.
* Linting configuration for Semistandard for JS.
based on the work done in (https://github.com/compucorp/civihr/pull/2464/files)
* `.gitignore` configuration to ignore several files.
* Created a new 'package.json' for the repository and added devDependencies
* "husky"
* "lint-staged"
* "semistandard"
* Created `.gitignore` and added `node_modules/` folder path.

C51-30: Implement Semistandard javascript and add gitignore.

---

CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Base.php
LICENSE.txt
README.md
civicase.civix.php
info.xml

PR changes extension name from `org.civicrm.civicase` to `uk.co.compucorp.civicase` and all its occurence from the codebase.
In the extension list (`civicrm/admin/extensions?reset=1&action=browse`)
In the extension list (`civicrm/admin/extensions?reset=1&action=browse`)

C51-31: Change extension name to uk.co.compucorp.civicase and its occurences.

---

.gitignore
ang/civicase/ActivityFeed.js
ang/civicase/CaseList.html
ang/civicase/DashboardCtrl.html
ang/civicase/SearchCtrl.js
css/caseView.css
css/civicase.min.css
css/dashboard.css
css/general.css
gulpfile.js
package-lock.json
package.json
scss/base/mixins/readme.md
scss/base/typography/readme.md
scss/base/variables/readme.md
scss/civicase.scss
scss/components/readme.md
scss/overrides/readme.md
scss/pages/_pages.scss
scss/pages/readme.md
templates/CRM/Civicase/Page/ContactActivityTab.tpl

PR covers following features
* Setup Folder structure for SASS.
* Setting up Gulp task for CSS complilation from SASS and adding minification to it
* Adding stylelint linter for scss check
* Make the UI for civicase to take full width
* Setup Folder structure for SASS.
```
scss
|- base (Contains base code)
|  |- mixins (Contains partials for mixins)
|  |- typography (contains partials for app typography)
|  |- variables (contains partials for variables used sitewide)
|
|- components (partials for different components)
|- overrides (overrides if any) 
|- pages (Partials specific to pages) 
```
* Replace occurence of `civicase-main` class to `civicase__container` making the HTML & CSS more BEM oriented.
* Gulp is configured to add `#bootstrap-theme` selector to each css styles except body …

C51-37: Making UI full bleed sass integration with gulp and add stylelint

---

ang/civicase/CaseList.html
ang/civicase/CaseListDirectives.js
ang/civicase/Search.html
ang/civicase/Search.js
ang/test/civicase/CaseListDirectives.spec.js

This PR covers UI enhacements for sticky header and basic HTML fixes for fitler panel on case list
* For the HTML fixes
* Sticky header fixes 
* This PR fixes sticky header scroll glitch by adding top padding to the table element when the header sticks to the top by hooking in `affixed-top.bs.affix` event and add logic
* Update Unit tests
* Fix the civicaseSearch directive. 
** Changed selector from just attribute to all. 
** Add `replace: true` to cut down the extra wrapper divs
** Renamed `civicase-search` attribute to `filter` attrbute to increase readability.
* Add BEM classes to the HTML. Classes used
** **civicase__case-filter-panel** : For search panel container
** **civicase__case-filter-panel .panel-header** : For search panel header
** **civicase__case-filter-panel__title** : …

C51-34: Add BEM classes to HTML and move the title inside panel header and misc fixes

---

ang/civicase/ContactsDataService.js
ang/test/civicase/ContactsDataService.spec.js

This PR fixes the field names for the contact popover so they can be displayed properly.
The information exists, but it's not being displayed.
The issue happened because the name of the fields are different in the request VS the response. To get the `gender` field one must request the `gender_id` field, and to get the `tags` field one must request the `tag` field.
Also, the tags field returns the tags without space between them so the following transformation was done in order to display the tags with proper spacing between them:
```js
contact.tags = (contact.tags + '').split(',').join(', ');
```

C51-185: fix contact popover fields

---

ang/civicase/ContactsDataService.js
ang/test/civicase/ContactsDataService.spec.js

Contact Type Icons not displayed for some users, this PR fixes that issue.
`ContactsDataService.js` was only loading 25 records so some of the records had missing data. 
Added `'options': { 'limit': 0 }` to load all contacts.
This is not reproducible in local so screenshots are not provided.

C51-187: Contact Type Icons not displayed for some users

---

ang/civicase/ContactCard.html

This PR removes the contact popover when hovering the activity manager icon.
The solution was just removing the contact popover trigger from the manager icon:
```html
<span ng-if="isAvatar">
<a
href="{{ url('civicrm/contact/view', {cid: contacts[0].contact_id}) }}"
class="civicase__contact-avatar crm_notification-badge"
ng-class="{'civicase__contact-avatar--image': contacts[0].image_URL}"
title="{{contacts[0].display_name}}">
<span ng-if="!contacts[0].image_URL">{{contacts[0].avatar}}</span>
</a>
</span>
```

C51-190: Remove contact popover for manager

---

ang/civicase/ActivityIcon.html

This PR covers fix for making the task icon of next activity card to turn `green` when the task is checked.
* Removes `text-danger` class on the icon and adds `text-success` class if the activity is completed.

C51-204: Task icon to turn green when task is checked

---

ang/civicase/ActivityCard--Big.html
ang/civicase/ActivityCard--Long.html
ang/civicase/ActivityCard--Short.html
ang/civicase/ActivityIcon.js
ang/civicase/CaseCard--case-list.html
ang/civicase/CaseCard--other-cases.html
ang/civicase/CaseDetails.js
ang/civicase/DateHelperService.js
ang/test/civicase/DateHelperService.spec.js

PR contains fix for the incorrect overdue styles on next activity card.
Checking the activity is overdue was not implemented generically throughout the app and hence was creating issues at some activities.
As there were three cases
* is_overdue was sent as Boolean for some activities
* is_overdue was sent as String for some activities
* is_overdue might not be present for some activities.
So to fix this we have a single function which will take care of this is used throughout the app now. At
* Activity Icon directive
* Case Card Variant
* Case Card List view
* Case Card Other cases view
* Activity Card Variant
* Activity Card Big
* Activity Card Short
* Activity Card Long

C51-202: Fix color logic for due date

---

ang/civicase/ActivityCard--Big.html
ang/civicase/ActivityCard--Long.html
ang/civicase/ActivityCard--Short.html
ang/civicase/ActivityCard.js
ang/civicase/ActivityIcon.js
ang/civicase/CaseCard--case-list.html
ang/civicase/CaseCard--other-cases.html
ang/civicase/CaseCard.js
ang/civicase/CaseDetails.js
ang/civicase/DateHelperService.js
ang/civicase/Utils.js
ang/test/civicase/DateHelperService.spec.js

This PR covers the code refactoring for overdue dates and fix the order of next activity to come on the case summary with some UI fixes.
There is already a factory `formatActivity` which formats the activity's keys with correct values and types. It also fix the type and value of `is_overdue` key. So we technically don't need another service `isOverdue` for this.
```
module.factory('formatActivity', function (ContactsDataService) {
var activityTypes = CRM.civicase.activityTypes;
var activityStatuses = CRM.civicase.activityStatuses;
var caseTypes = CRM.civicase.caseTypes;
var caseStatuses = CRM.civicase.caseStatuses;
return function (act, caseId) {
act.category = (activityTypes[act.activity_type_id].grouping ? activityTypes[act.activity_type_id].grouping.split(',') : []);
act.icon = …
```

C51-227: Fix next activity tile overdue date issue and next activity order issue

---

ang/civicase/ActivityFeed.html
ang/civicase/FileList.html
ang/civicase/FileList.js

PR covers the fix for the `Copy activity` and `Delete Activity` feature on Activity feed and Files Feed
* Since the refresh function on activity feed was wrongly passed to activity card the functionality broke for activity feed
* Adding the same refresh function implementation for `FileList` directive fixed the issue.

C51-237: Fix Copy activity / Delete activity for Activity Feed and Files Feed,

---

ang/civicase/ActivitiesCalendar.js
ang/test/civicase/ActivitiesCalendar.spec.js

This PR changes the way overdue dates are calculated for the activities calendar. Before they were calculated when all activities were in the past. Now they just take into consideration the `is_overdue` field.
The `getDayCustomClass` was refactored so it checks if at least one activity is overdue to mark the date as `overdue`:
```js
function getDayCustomClass (params) {
var allActivitiesHaveBeenCompleted, isOneActivityOverdue;
// ...
allActivitiesHaveBeenCompleted = checkIfAllActivitiesHaveBeenCompleted(activities);
isOneActivityOverdue = checkIfOneActivityIsOverdue(activities); // checked here
if (allActivitiesHaveBeenCompleted) {
return 'civicase__activities-calendar__day-status civicase__activities-calendar__day-status--completed';
} else if (isOneActivityOverdue) { // used here
return …
```

C51-233: Mark calendar overdue date using is_overdue field

---

ang/civicase/Search.js
ang/civicase/Utils.js

As part of this PR the autofill has been disabled for all `crmUiSelect`.
1. Added a decorator to disable the autofill for the `crmUiSelect` directive.
2. Removed similar code from `Search.js`

C51-250: Disable autofill for crmUiSelect

---

ang/civicase/ContactCard.html
ang/civicase/ContactCard.js
ang/test/civicase/ContactCard.spec.js

This PR fixes the contact card's popover. In some instances the contact information
may be missing.
The reason for this is that the contact information may not be ready by the time the
contact card is displayed since the activity information and the contact information
are fetched one after the other.
To fix this, the contact information is fetched on mouseover instead, which is when
the contact popover is requested.
```html
<span uib-popover-template="'contact-popover.html'"
popover-class="contact-popover-container"
popover-append-to-body="true"
popover-placement="auto bottom"
popover-trigger="'mouseenter'">
popover-trigger="'mouseenter'"
ng-mouseover="initMainContact()">
</span>
```
```js
scope.initMainContact = function () {
scope.mainContact = …
```

C51-241: Change case contact popover data loading from init to mouseover

---

ang/civicase/CaseListTable.js
ang/civicase/Utils.js

Notice the -28.
The scrollbar is longer because it contains all the activities for the day.
The issue happens because when the case list and the case details are loaded they don't specify a limit for the activities and the default limit is `25`. The activities are needed to count how many scheduled/completed tasks there are for each case. Also, the activities are needed because they are passed to the calendar. It doesn't requests them itself.
To solve it, the limit was changed to `0` which means that all activities will be requested.
To test the request sizes a few activities were created using the following command from the console:
```js
var caseIds = [43, 70, 85, 120, 84, 87];
caseIds.forEach((caseId) => {
CRM._.times(50).forEach((i) => CRM.api3('Activity', 'create', { …
```

C51-253: Fix activities count and calendar

---

ang/civicase/PanelQuery.html
ang/civicase/PanelQuery.js
ang/test/civicase/PanelQuery.spec.js

This PR adds a new directive, `<civicase-panel-query>` that provides an out-of-the-box panel that takes care of
* running a given query via the API
* displaying the results on custom markup
* paginating the results (with deferred loading)
* doing a live-reload of the results in case the query parameters have changed
* provide a a date range select dropdown
* providing customization options for title, items name in the pagination, and top-right corner actions
This is what the directive looks like in a simple scenario where a list of cases are fetched and displayed in `<civicase-case-card>` directives:
_(please note that the style of the case cards in the panel is temporary)_
```html
<civicase-panel-query query="queryData">
<panel-query-results>
<div ng-repeat="item in …
```

C51-271: civicase-panel-query directive

---

ang/civicase/Dashboard.html
ang/civicase/Dashboard.js
ang/civicase/DashboardTab.html
ang/civicase/DashboardTab.js
ang/civicase/PanelQuery.html
ang/civicase/PanelQuery.js
ang/civicase/Search.js
ang/test/civicase/Dashboard.spec.js
ang/test/civicase/DashboardTab.spec.js
ang/test/civicase/PanelQuery.spec.js

This PR improves the `<civicase-panel-query />` directive and uses it to display the "new cases" block in the dashboard
The main improvements are to the ux
_(Just for illustrative purposes in this gif, the page size has been reduced and the period range filter has been disabled)_
* Two different loading statuses:
* Full (when the query params changes): empty the results cache, show placeholders, make a new `getcount` request
* Partial (when the current page changes): Keep the results cache, change the opacity of `.panel-body`, don't make a new `getcount` request
* Cache: when doing a "partial" loading, the results are cached so that they are not fetched again if the user goes to a page he's already been on
* Prevent multiple requests: the directive disables the pagination when loading, …

C51-280: New cases block

---

ang/civicase/Actions.js

As a part of this PR the "dialog box clipping from the bottom when selecting change case status for case list bulk action" bug is fixed.
When jQuery UI align the CRM popup box it aligns it correctly but after it gets rendered to the screen it appends extra markup (loads wysiwyg inside it) making it grow from the bottom which eventually hides the extra part that crosses the browser screen bottom.
Fixed by hooking on the resolve callback of load wysiwyg (as CRM.wysiwyg.create which is responsible for loading the editor returns a promise) and telling dialog popup box to re adjust itself using 
```js
$(dialog).parent().position({ 'my': 'center', 'at': 'center', 'of': window });
```

C51-261 - Dialog box alignment for change case for bulk actions

---

ang/civicase/CaseDetails--tabs--summary--RecentCommunications.html
ang/civicase/CaseDetails--tabs--summary--Tasks.html

This PR refreshes the case details when creating a new task or communication from their respective details panels.
The issue happens the `civicase-add-activity-menu` needs to have a `crm-popup-form-success` property added to it and pass a refresh function to reload the case data:
```html
<civicase-add-activity-menu
case="item"
filter-activities-by="communication"
crm-popup-form-success="pushCaseData($data.civicase_reload[0])">
</civicase-add-activity-menu>
```
`crm-popup-form-success` is a directive that triggers an event when the activity modal form is submitted. It passes a `$data` object with the details of the activity. One of this properties is `civicase_reload` which contains query params to pass to the reload function. This params were constructed by `civicase-add-activity-menu` …

C51-248: Fix case refresh when creating new tasks

---

ang/civicase/ContactCaseTab.html
ang/civicase/ContactCaseTab.js
ang/civicase/ContactCaseTabCaseDetails.html
ang/civicase/ContactCaseTabCaseDetails.js
ang/civicase/ContactCaseTabCaseList.html

As a part of this PR some minor bugs and improvements are done on contact records
##Issue list
Since the count API for cases where contact is case manager is not returning right response, we decided to disable load more for `Other cases where the contact is related` on contact record screen under cases tab
db02d63
Due to same API issue the no result was broken
So for now the count is calculated from the length of the cases arrays when all of them are loaded
910483c
Make the left case list to refresh when status is changed
Passed `refresh` function inside the `ContactCaseTabCaseDetails` from `ContactCaseTab` Directive
90b269c
Changed the text to `Resolved case`
18d8d53

C51 312 fix bugs for contact record

---

ang/civicase/ContactsDataService.js
ang/test/civicase/ContactsDataService.spec.js

This PR fixes a bug with Activity Feed where Contact initials were not shown.
Suppose `ContactsDataService.add()` is called with Contact A and Contact B, then it will make an api call to fetch more details about those. But before this API call ends, if another call is made to again fetch Contact A and Contact B, then `newContacts.length` will be equal to 0, and the code will return directly. This was a problem because 2nd call to `ContactsDataService.add()` returned before the respective data is loaded.
To fix this, a deferred object is created. And whenever there is no new data to be loaded, it checks whether a previous call is already in progress, if yes it waits for the call to finish.

C51-299: Fix ContactDataService logic

---

ang/civicase/CaseListTable.js
ang/civicase/Search.html
ang/civicase/Search.js
ang/test/civicase/CaseListTable.spec.js
ang/test/civicase/Search.spec.js

PR covers fix for URL being read by the case list filter after reloading it or going directly on it.
* The filter objects were binded to the routeparams to `CaseListTable` directive, but are also used by `Search.js`. 
Since they both are sibling to each other, they don't share the same scope (and also `filter` object).
* The solution to this was binding the route params to filter object in `Search.js` and make its member fns to use it and then fire `civicase::case-search::filters-updated` which will be caught by its other sibling `CaseListTable` and then the cases filters are updated there 
`CaseListTable.js`
```
$scope.$on('civicase::case-search::filters-updated', function (event, filters) {
$scope.applyAdvSearch(filters.selectedFilters);
});
$scope.applyAdvSearch = function (newFilters) …
```

C51-323: Fix filter persistance issue when reload case page

---

ang/civicase/DashboardTab.html
ang/civicase/DashboardTab.js
ang/civicase/PanelQuery.js
ang/test/civicase/DashboardTab.spec.js

As part of this PR, the Activities block in Dashboard has been developed.
1. One more `civicase-panel-query` component has been added to show the activity block.
2. `ACTIVITIES_QUERY_PARAMS_DEFAULTS ` and `$scope.activitiesPanel` is also added for the same block with its parameters.
When an Activity Card is edited from the Popup, the blocks pager resets to 1, instead of remembering its old state. Because of time crunch this could not be implemented.

C51-321: Activities block

---

ang/civicase/Search.html

Hiding End Date filter when status filter is not resolved, and showing only when one of the status filter is resolved.
By default the case list shows all open cases, so filtering open cases with end date is kind of useless and will not shows any cases. Obviously, because an open case can't have an end date.
So, showing end date filter only when filtered cases status is `Resolved`.

C51-197: Hiding end-date filter when status is not in 'Resolved' cases

---

api/v3/Activity/Getdayswithactivities.php

This PR adds a `getdayswithactivities` to the `Activity` entity. The endpoint is used to get the list of _unique_ YYYY-MM-DD dates that have at least one activity.
It supports the following parameters:
* `activity_date_time` 
* `activity_status_id`
* `case_id`
Example of a response:
```json
{
"is_error": 0,
"version": 3,
"count": 534,
"values": [
"2008-01-10",
"2008-02-01",
"2008-02-05",
"2008-03-05",
"2008-03-11"
]
}
```

C51-333: Add Activity.getdayswithactivities endpoint

---

ang/civicase/ActivitiesCalendar--decorator.js
ang/civicase/ActivitiesCalendar.js
ang/civicase/CaseDetails--tabs--summary.html
ang/test/civicase/ActivitiesCalendar.spec.js

_(Note: To reduce the scope of the tickets and PRs, the refactoring of the calendar has been split into two separate tasks, this one being the first of them. To avoid merging an incomplete calendar to `develop`, a `C51-refactor-activities-calendar` branch has been created in which the two tasks will be merged, so that the calendar will be release on `develop` only once it has been fully refactored)_
This PR utilizes the new `Activity.getdayswithactivities` endpoint (#110), to fetch the data necessary for the calendar to display the due/overdue/completed dots under each day
This is the flow:
1. The `uib-datepicker`'s link function has been decorated so that a `civicase::uibDaypicker::compiled` event is emitted when the directive has been compiled and attached to the DOM
2. The Activities …

C51-334: Use Activity.getdayswithactivities in civicase-activities-calendar

---

ang/civicase/ActivitiesCalendar.html
ang/civicase/ActivitiesCalendar.js
ang/civicase/ActivityCardPlaceholder.html
ang/civicase/ActivityCardPlaceholder.js
ang/civicase/CaseDetails.js
ang/test/civicase/ActivitiesCalendar.spec.js
ang/test/civicase/DashboardTab.spec.js
ang/test/mocks/services/formatActivity.mock.js
ang/test/mocks/services/formatCase.mock.js

This PR add the deferred loading of activities to the calendar, in order to improve performance.
Before, the calendar would receive the full list of activities, which it would use to both display the dots under days with activities, and also to display the list of a day's activities when the user clicked on that day.
With #111, now the calendar doesn't receive the full list of activities anymore, but calls a new api endpoint that returns the list of days with any activities, which the calendar uses to display the dots.
The list of activities of a given day needs then to be fetched on-demand, when the user clicks on a day. The list is then cached as to avoid unnecessary api calls if the user clicks on a day he previously clicked on
Moreover, the calendar needed now a new way to refresh …

C51-265: Defer loading activities

---

ang/civicase/ActivitiesCalendar--decorator.js
ang/civicase/ActivitiesCalendar.js
ang/civicase/PanelQuery.js
ang/test/civicase/ActivitiesCalendar.spec.js

This PR adds the ability for the calendar to load only a month's worth of data at a time, in order to improve performance in case of large numbers of cases and/or activities. Additionally the data is cached, so that the component doesn't make api requests for months the user already previously selected 
The loading functionality is debounced with a wait time of `300`ms, so that the user doesn't flood the API when switching quickly between months.
**Debounce off**
**Debounce on**

C51-267: Load only data of currently selected month in Activities Calendar

---

api/v3/Case/Getdetailscount.php

This PR adds a new endpoint that counts cases properly after being filtered by special case fields like `case_manager`.
The original `getcount` does not respect the `case_manager` filter when doing the count. This is a special filter that was added to the `getdetails` api: 
https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/api/v3/Case/Getdetails.php#L50-L57
This new endpoint allows cases to be counted using the `getdetails` api and passing the `is_count` option, which CiviCRM uses to override the query and replace it with a count using the same filters.
Unit tests were created for this endpoint but they were failing. For more information please refer to:
https://compucorp.atlassian.net/browse/C51-340

C51-340: Add Case.getdetailscount api endpoint

---

ang/civicase/CaseListTable.js
ang/civicase/ContactCaseTab.js
ang/civicase/Dashboard.js
ang/civicase/DashboardTab.js
ang/civicase/PanelQuery.js
ang/civicase/Search.js
ang/test/civicase/CaseListTable.spec.js
ang/test/civicase/Dashboard.spec.js
ang/test/civicase/PanelQuery.spec.js
api/v3/Case/Getdetailscount.php

This PR replaces the `getcount` api endpoint with the new `getdetailscount` introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/117
This new endpoint allows for properly counting the results for cases filtered by their manager or contacts involved in the case.
Notice these two things:
* The "My Cases" search filter, and
* The pagination list
The contact only has 1 case assigned to them, but the pagination displays more records than what it should.
The pagination now works properly. When there's only 1 page, the pagination is not displayed.
* `Case.getcount` was replaced with `Case.getdetailscount`.
* Code that was added as a temporary fix for C51-277 was removed.
* Code that was commented out as a temporary fix for C51-277 was added back.
The `getdetailscount` breaks …

C51-341: Implement getdetailscount api endpoint on the front end

---

ang/civicase/DashboardTab.html
ang/civicase/DashboardTab.js
ang/test/civicase/ActivitiesCalendar.spec.js
ang/test/civicase/DashboardTab.spec.js
ang/test/global.js

This PR adds a "View cases" link in the "new cases" block in the dashboard, that will redirect the user to the "Manage Cases" page.
The link will change both label and query string params depending on the current value of the "case relationship" filter:
When the filter is on "All Cases":
When the filter is on "My cases":
When the filter is on "Cases I'm involved in":
The link is generated every time `$scope.filters.caseRelationshipType` changes
```js
function initWatchers () {
$scope.$watchCollection('filters.caseRelationshipType', function (newType, oldType) {
// ...
$scope.newCasesPanel.query.params = getQueryParams('cases');
$scope.newCasesPanel.custom.viewCasesLink = viewCasesLink();
});
}
```
The link's query string parameters are generated on the fly by the function. The only …

C51-315: "View cases" link

---

ang/civicase/ContactCaseTab.html
ang/civicase/ContactCaseTab.js
ang/test/civicase/ActivityFeed.spec.js
ang/test/civicase/ContactCaseTab.spec.js

This PR automatically selects the current contact when creating a new case from the contact's case tab.
The solution was simple: to pass the `cid` (contact id) parameter to the form URL:
```html
<a ng-href="{{ 'civicrm/case/add' | civicaseCrmUrl:{cid: contactId, reset: 1, action: 'add', context: 'standalone'} }}">
```
The contact ID is provided by ` Contact.getContactIDFromUrl()`:
```js
$scope.contactId = Contact.getContactIDFromUrl();
```
Since this value is constant all other instances of `Contact.getContactIDFromUrl()` were replaced by `$scope.contactId`.

C51-286: Auto populate contact

---

ang/civicase/DashboardTab.js
ang/test/civicase/DashboardTab.spec.js

This PR fixes an issue where deleted cases would be displayed on the dashboard.
The default query parameters for the case now include the `is_deleted: 0` option to skip deleted records.

C51-314: Do not display cases that have been deleted on the dashboard

---

CRM/Civicase/Hook/BuildForm/CaseClientPopulator.php
ang/civicase/ContactCaseTab.html
civicase.php

This PR autopopulates the case client using the BuildForm hook.
[Previously](https://github.com/compucorp/uk.co.compucorp.civicase/pull/131) we tried to autopopulate this field using the `cid` parameter, but this fail due to an error in core.
There are two issues:
* The field is autopopulated for a single contact. This blocks users from creating a multiple contact case, unless they later edit it.
* When saving the case an error is thrown saying the field is "missing". This is an error from core.
The field is autopopulated, it allows for multiple contacts, and can be saved correctly.
As mentioned before, this field was previously autopopulated in https://github.com/compucorp/uk.co.compucorp.civicase/pull/131 using only the `cid` parameter as provided by core, but this method fails when …

C51-286: Autopopulate case client using hook

---

CRM/Civicase/Activity/ContactActivitiesSelector.php
ang/civicase/ActivityFeed.js
ang/civicase/DashboardTab.js
ang/test/civicase/ActivityFeed.spec.js
ang/test/civicase/DashboardTab.spec.js
api/v3/Activity/Getcontactactivities.php
api/v3/Activity/Getcontactactivitiescount.php

This PR hides the activities from "My Activities" that have been delegated to other contacts.
**Note:** The "Medical Evaluation" activity was assigned to another contact so it should not be visible in "My Activities" tab.
In order to hide the activities that have been delegated to another contact we needed to create a new endpoint that would query the activities for the contact and filter out the delegated ones manually. The reason for this is because the query to exclude these activities is quite complex and not supported by the API:
```sql
WHERE contact_id = 123
AND (contact_id IN assignee_contact_id
OR assignee_contact_id IS NULL)
```
Since the `assignee_contact_id` is a foreign field, working with NULL is not supported.
The implementation for the new service is as follows:
```php …
```

C51-320: Hide delegated activities from "My Activities"

---

api/v3/Activity/Getmonthswithactivities.php
civicase.civix.php
tests/phpunit/BaseHeadlessTest.php
tests/phpunit/api/v3/Activity/GetmonthswithactivitiesTest.php

The PR adds `Activity.getmonthswithactivities` endpoint which returns a list of the map of unique `month` and `year` with at least one activity. The endpoint supports all the parameters that `Activity.get` does.
Sample response
```json
[
{
"year": "2009",
"month": "1"
},
{
"year": "2009",
"month": "10"
},
{
"year": "2010",
"month": "3"
},
{
"year": "2015",
"month": "5"
},
{
"year": "2015",
"month": "12"
},
{
"year": "2016",
"month": "12"
},
{
"year": "2017",
"month": "1"
},
{
"year": "2017",
"month": "10"
},
{
"year": "2017",
"month": "11"
},
{
"year": "2017",
"month": "12"
},
{
"year": "2018",
"month": "11"
}
]
```

C51-269: Add Activity.getmonthswithactivities endpoint

---

CRM/Civicase/XMLProcessor/Report.php

This PR fixes the the following two bugs related to the Case Report Bulk Action
Non-Assigned roles are displayed on reports generated using Bulk Actions.
While refactoring `Report.php`(https://github.com/compucorp/uk.co.compucorp.civicase/commit/5428f4d4a29118cfcb4ad945c903923b8215ff93#diff-ea1f1b04ff56d2e2a233049eddae8d21), some of the things were missed
1. `$caseRoles` and `$isRedact` parameter was not passed to `redactCaseRelationshipFields`. Also the following code should have run irrespective of the value of `$isRedact`.
Now those are added and the function is renamed to `processCaseRelationshipFields`.
2. Also `processClientRelationshipFields` method was missing the `$caseRelationships` param, which is fixed.
Past Activities are not displayed on report generated using Bulk Actions. …

C51-371: Bug Fixes for Case Report Bulk Action

---

Civi/CCase/Utils.php
ang/civicase/CaseListTable.js
ang/civicase/Dashboard.js
ang/civicase/Search.js
ang/test/civicase/Dashboard.spec.js
ang/test/civicase/Search.spec.js
api/v3/Case/Getcaselist.php
api/v3/Case/Getdetails.php
api/v3/Case/Getstats.php
api/v3/Case/Gettypestats.php

This PR creates a new parameter `contact_involved` for the `getCaseDetails` and `getcaselist` endpoint for `case` entity. 
`contact_involved` returns all the cases for a contact in which the contact is involved as either a case client or with some other relationship.
* Updated `getCaseManagerRelationshipTypes ` function to more generic one. which will get the casetype <-> case-relationship keys on basis of parameter passed
```php
// prepares list of links between casetypeid <-> case relationship
public static function getRelationshipTypes($type) {
.....
....  
foreach ($caseTypes['values'] as $caseType) {
$lists = array();
foreach ($caseType['definition']['caseRoles'] as $role) {
if ($type == 'all') {
$lists[] =  $relationshipTypes[$role['name']]['id'];
} else {
if (!empty($role[$type])) …
```

C51-318:Add API param to case list to fetch non-case-manager cases

---

ang/civicase/activity/directives/add-activity-menu.directive.js
ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js

As part of this PR, Activity Types exceeding max_instance are hidden from "Add New Menu".
Issue reported in Github: https://github.com/compucorp/uk.co.compucorp.civicase/issues/151
The original issue reported is a Core Issue, but this problem was not present in old civicase, because we hid all activity types exceeding max_instance. Hence the same fix needs to be applied to current version.
This functionality got broken when copying code from old civicase to new. 
So the following line is added back
https://github.com/compucorp/uk.co.compucorp.civicase/blob/78a35c1f90fa0f5aa0e1e530f1f97278ab24a0e8/ang/civicase/View.js#L94
However, there was a bug in the old logic, 
`actSpec.max_instances < activityCount[actTypeId]`
but the `activityCount[actTypeId]` should be less than …

C51-387: Hide Activity Types when Exceeding max instance

---

ang/civicase/case/details/directives/case-details.directive.js

In the PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/157, the client name removal was not done when Editing an Activity. It has been fixed in this PR.

C51-222: Remove Client name from Edit Activity modal

---

gulp-tasks/backstopjs.js
gulp-tasks/karma-unit-test.js
gulp-tasks/sass-sync.js
gulp-tasks/sass.js
gulp-tasks/test.js
gulp-tasks/watch.js
gulpfile.js
tests/backstop_data/Readme.md

This PR 
* Refactors Gulpfile.js and break the gulp tasks to their corresponding files in `gulp-tasks` folder
* List all the screens to be covered under backstopJS test suite
No visual changes are brought by the PR
* All the related gulp tasks function are extracted from main `Gulpfile.js` and moved in their corresponding js files in `gulp-tasks` folder. Now the gulpfile.js only calls the `gulp.tasks` functions
```js
/**
* The gulp task updates and sync the scssRoot paths
*/
gulp.task('sass:sync', sassSyncTask);
/**
* Gulp sass task
*/
gulp.task('sass', ['sass:sync'], sassTask);
/**
* Gulp unit tests task
*/
gulp.task('test', testTask);
/**
* Gulp watch task
*/
gulp.task('watch', watchTask);
/**
* Gulp backstop tasks
*/
['reference', 'test', 'openReport', 'approve'].map(backstopJSTask); …
```

C51-390: Refactor Gulpfile.js and adds list all screens to be covered under backstopJS to the readme file

---

ang/civicase/activity/actions/directives/activity-actions.directive.html
ang/civicase/activity/calendar/directives/activities-calendar.directive.js
ang/civicase/activity/factories/get-activity-feed-url.factory.js
ang/civicase/case/card/directives/case-card-case-list.directive.html
ang/civicase/case/card/directives/case-card-other-cases.directive.html
ang/civicase/case/card/directives/case-card.directive.js
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/details/summary-tab/case-details-summary-tab.html
ang/civicase/case/details/summary-tab/case-summary-recent-communications.html
ang/civicase/case/details/summary-tab/case-summary-tasks.html
ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
ang/test/civicase/activity/factories/get-activity-feed-url.factory.spec.js
ang/test/civicase/case/card/directives/case-card.directive.spec.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/shared/directives/popover.directive.spec.js

This PR redirects the "see all activities" link from the activity calendar on the case details so they are displayed on the activity tab for the case instead of displaying the activities on the activity tab of the dashboard.
The "See All" takes the user to the activities tab on the dashboard.
The "See All" takes the user to the activities tab on the case.
**Note:** for both scenarios the activities limit was removed so the effect can be demonstrated more clearly.
The solution was to adapt the `getActivityFeedUrl` util function so it can take the user to either the case activities or the dashboard activities depending on their current section. Also, the `getActivityFeedUrl` was refactored so it uses a single object parameter instead of multiple parameter values in order to simplify passing …

C51-354: Fix "See all" link of Activity Calendar

---

tests/backstop_data/Readme.md
tests/backstop_data/backstop.tpl.json
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail.js
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-edit-details.js
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions.js
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/on-contact-page.js
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/on-manage-cases.js
tests/backstop_data/engine_scripts/puppet/contacts/contact-dashboard.js
tests/backstop_data/engine_scripts/puppet/manage-cases/select-case.js
tests/backstop_data/engine_scripts/puppet/mouse-events-helper.js
tests/backstop_data/engine_scripts/puppet/utility.js
tests/backstop_data/scenarios/activity-feed-panel.json

This PR covers backstopJS screens for Activity Panel feeds 
* Activity Feed Panel - Main Section
* Activity Feed Panel - Bulk Actions
* Activity Feed Panel - Loading State
* Activity Feed Panel - Load more clicked
* Activity Feed Panel - Selected Filter
* Activity Feed Panel - Activity Details - Select Activity
* Activity Feed Panel - Activity Details - Selected Activity - Details
* Activity Feed Panel - Activity Card Menu
* Activity Feed Panel - Activity Details - Edit Activity
* Activity Feed Panel - On Manage Cases
* Activity Feed Panel - On Contact Page
* Updates viewport dimensions from random big values to sensible values (1660x1050)
* Updates `waitForLoadingComplete ` function to takes on a parameter so that loading screen can be checked on the micro level (by filtering the …

C51-392: Add screens for activity panel feed and add some utility functions

---

ang/civicase/activity/card/directives/activity-card.directive.js
ang/test/civicase/activity/card/directives/activity-card.directive.spec.js

This PR implements opening the standalone activity modal form for activities that don't belong to a particular case.
**Note:** The standalone activity breaks because it's opening the civicase form and it does not have all the data that is required by said form.
**Note:** The first activity is standalone, the second one belongs to a particular case.
The civicase or standalone forms are displayed depending if the `case_id` property of the activity is defined or not. To accomplish this the activity card directive:
```js
$scope.viewInPopup = function ($event, activity) {
var activityFormUrl = activity.case_id
? 'civicrm/case/activity'
: 'civicrm/activity';
// ...
CRM.loadForm(CRM.url(activityFormUrl, {
// ...
}));
// ...
};
```

C51-403: Standalone activity modal form

---

api/v3/RelationshipType/Getcaseroles.php

This PR adds a new action endpoint that returns a list of relationship types that are associated to case types.
The relationship types associated to case types are stored in their XML definition field and only have a reference to the `label_b_a` of the relationship type, not the ID. A sample structure for a case type would be as follows:
```js
{
id: 1,
// ...
definition: {
// ...
caseRoles: [
{ name: 'Relationship Type label b a', manger: 1, creator: 1 },
{ name: 'Another relationship type' }
]
}
}
```
This action endpoint queries all active case types, stores all references to case roles, queries the relationship type entity to find those roles, and then returns them:
```php
function civicrm_api3_relationship_type_getcaseroles($params) {
$rolesMap = [];
$caseTypes = …
```

C51-411: Get case roles

---

api/v3/Case/Getcaselist.php
api/v3/Case/Getdetails.php

This PR adds support for filtering case types by the contacts that have some relationship to it.
* Contact is Betty Adams (204)
* Betty Adams is client for case 148, 149, and 150
* Betty Adams is "Homeless Services Coordinator" (id 11) for case 145
* Betty Adams is "Health Services Coordinator" (id 12) for case 6
```js
// request:
{
has_role: {
contact: 204,
can_be_client: false
}
}
// returned cases:
6, 145
```
```js
// request:
{
has_role: {
contact: 204,
role_type: 12,
can_be_client: false
}
}
// returned cases:
6
```
```js
// request:
{
has_role: {
contact: 204,
// role_can_be_client: true (optional)
}
}
// returned cases:
6, 145, 148, 149, 150
```
```js
// request
{
role_contact: 204,
role_type: 12,
// role_can_be_client: true (optional)
}
// returned cases
6, 148, 149, 150
```
(this …

C51-410: Case Role Filtering

---

ang/civicase/case/search/directives/search.directive.html
ang/civicase/case/search/directives/search.directive.js
ang/civicase/shared/factories/get-select2-value.factory.js
ang/test/civicase/case/search/directives/search.directive.spec.js
ang/test/civicase/contact/directives/contact-icon.directive.spec.js

This PR modifies the the case search. The client search was changed to a contact search that allows users to filter cases by contact clients or roles. 
The filter implements `crm-ui-select`, the format for the options looks as follows:
```js
$scope.contactRoleFilters = [
{ id: 'all-case-roles', text: 'All Case Roles' },
{ id: 'client', text: 'Client' }
// sample of options added later:
{ id: 12, text: 'Health Service Coordinator' }
];
```
The "All Case Roles" and "Client" options are provided as soon as the component is rendered, but the specifics role options are fetched asynchronously:
```js
(function init () {
// ...
requestCaseRoles().then(addCaseRolesToContactRoleFilters);
}());
function requestCaseRoles () {
return crmApi('RelationshipType', 'getcaseroles', {
options: { limit: 0 } …
```

C51-412: Filter cases by role

---

api/v3/Case/Getdetails.php
api/v3/Case/Getdetailscount.php

The role filter introduced in #183 has been refactored in order to fix an issue with where the case count was not correct.
The temporary fix introduced in #187 was reverted back.
The query for filtering cases by roles was refactored into a subquery. The advantage of this approach is that the `GROUP BY` statement can be avoided by the main query and moved into the subquery. The train of thought of the subquery goes as follows:
1. Selects case id from the case table.
2. If the role can either be of a "manager" or a client, ir `LEFT JOIN`s the `case_client` and `relationships` table.
3. If the role is only for manager it `JOIN`s to the `relationships` table.
4. Groups the subquery by case id to avoid duplicates.
```php
function _civicrm_api3_case_getdetails_handle_role_filters ($sql, …
```

C51-414: Refactor role filter into a sub query

---

ang/civicase/case/search/directives/search.directive.js
api/v3/Case/Getdetails.php

Searching For "Client" Role displays results of all roles for the specified Contact
Previously, when `can_be_client` was true, we were applying the `other roles` filter. This was resulting in returning all cases where the selected contact has any role, instead of just being the client.
```php
if ($canBeAClient) {
_civicrm_api3_case_getdetails_join_client($roleSubQuery, $hasRole);
// the following lines should be applied only when the other roles than client is selected. or all case roles has been selected.
_civicrm_api3_case_getdetails_join_relationships($roleSubQuery, $hasRole, [
'joinType' => 'LEFT JOIN',
]);
$roleSubQuery->where('case_relationship.case_id IS NOT NULL
OR case_client.case_id IS NOT NULL');
} 
```
To fix this, a new param `all_case_roles_selected ` has been sent from …

C51-401: Fix has_roles logic

---

ang/civicase/activity/actions/directives/activity-actions.directive.html
ang/civicase/activity/feed/directives/activity-feed.directive.js
api/v3/Activity/GetActionLinks.php

After installing the civicase extension, activity action links added by custom extensions and even some core extension like Contributions are not taken into account and only default links shows up for all activity types.
The activity action links displayed in the activity tab for a contact for each activity is a set of hardcoded pre-defined links.
The activity action links for an activity may be different from that of another activity as it is determined by some logic executed in the hook_civicrm_links implemented by each extension.
I did some investigations on how Civi adds the activity action links for an activity record [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Activity/BAO/Activity.php#L2604-L2626) and extracted the relevant function to an API action so that the …

RSE-110: Add custom activity actions added by other extensions.

---

api/v3/Activity/Getactionlinks.php

When the latest civicase release was deployed on the test server, the activities for all contacts on the contact summary were not loading. Checking the API requests, the call to load activities has this error `Activity_getactionlinks : API (Activity, getactionlinks) does not exist (join the API team and implement it!)"},`
Seems the API naming convention could affect the calling the API on some servers as seen [here](https://civicrm.stackexchange.com/questions/22412/api-creation-my-action-is-not-found-only-on-linux-server?rq=1)
The API action is in camel case and it is being called from angular frontend with lowercase so the fix was to rename the API action to all lower case rather than using the camel case.

C51-417: Fix API naming convention

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js

In the People tab of Case Details, the Case Manager role was shown for all relationships, even if it is not assigned.
This was happening because the `Case.getCaseList` API, sometimes returns `0` and sometimes returns `false` for the `manager` property under contacts.
That is why the code needed to be refactored to consider `0` as `false`.
`role.manager === '1'`

CATL-1069: Fix case_manager role shown for all roles

---

ang/civicase.ang.php
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js

This PR adds support to use different case client as configured in webform. 
Previously just the 'cid' would be passed in the URL which would work only if the first contact is set as case client.
Now which ever contact is set as case client in the webform, the url will be used as 'cid[client-contact]'.
So if contact 2 is set as case client in webform, the add case URL will have 'cid2=[contact_id]'.
A variable called 'newCaseWebformClient' is added which will have the case client number for the webform configured. So in the webform if there are more than 1 contact and say contact 2 is set as case client, then 'newCaseWebformClient' will say 'cid2'.
Previously it will always say 'cid' and so it will only work if the case client is set to contact 1 in the webform.
In …

C51-417: Add Case Button In Contact; Select Case Client As Configured In Webform

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.mgd.php
CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
CRM/Civicase/Form/Report/ColumnDefinitionTrait.php
CRM/Civicase/Form/Report/ExtendedReport.php
templates/CRM/Report/Form/Tabs/Aggregate.tpl
templates/CRM/Report/Form/Tabs/Aggregates.tpl
templates/CRM/Report/Form/Tabs/CustomFieldSelection.tpl
templates/CRM/Report/Form/Tabs/FilterField.tpl
templates/CRM/Report/Form/Tabs/FiltersCiviCase.tpl
templates/CRM/Report/Form/Tabs/Relationships.tpl
templates/CRM/Report/Form/Tabs/Results.tpl
templates/CRM/Report/Form/Tabs/Template.tpl

A report of Cases, with their activities and Case roles involved with the cases is required for NEU. Civi reports which is Civi's default reporting has it's functionality extended by [Extended Reports Extension](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport). The extended reports extension provides some reports out of the box with Pivot functionalities which allows to group and aggregate on selected field.
For the purpose of this task, one of such reports provided by Extended Reports: `Extended Report - Case with Activity Pivot Chart` was used as the base report for NEU. This report was extended to include Joins to relevant tables to get Case roles data, Custom fields and other fields not provided by the original report.
Also the Extended report was enhanced to provide …

CATL-1055: NEU Civicase Reporting

---

CRM/Civicase/Form/Report/ColumnDefinitionTrait.php

The Activity duration fields labels are confusing and both fields seems to be doing the same thing when used in the reports. This PR removes one of the fields and renames the labels properly for easy comprehension.

CATL-1083: Remove Duplicate Activity Duration Field

---

CRM/Civicase/Setup/CaseTypeCategorySupport.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0001.php
CRM/Civicase/Upgrader/Steps/Step0002.php
civicase.php
sql/auto_install.sql
sql/auto_uninstall.sql

As part of this PR, the Case Type Category field is added to Civicase.
Field is Added
Option Group is created
**Upgrader**
Support for adding upgraders in individual files has been added.
A new upgrader has been added which adds a new field `case_type_category` to `civicrm_case_type` table. 
Also it adds a new Option Group called `Case Type Categories`.
**hook_civicrm_entityTypes**
A new function `_civicase_update_case_type_entity` is added, which adds the `case_type_category` field to the `CaseType` DAO.
`civilint` fixes has been made to the touched files. But there will be a discussion with Davi regarding this, and once finalised, `civilint`(or any other linter) will be added as part of pre commit hooks.

RSE-32: Create Case Type Category field

---

CRM/Civicase/Setup/CreateCasesOptionValue.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0003.php

As part of this PR, a new Option Value called `Cases` is created part of `Case Type Categories` Option Group.
Added `CRM_Civicase_Setup_CreateCasesOptionValue` class, which takes care of adding the option value, and it is reused for Upgrading and also for Installing the extension.

RSE-176: Add Cases Option Value

---

CRM/Civicase/APIHelpers/CasesByContactInvolved.php
CRM/Civicase/APIHelpers/CasesByManager.php
ang/civicase/case/directives/case-overview.directive.js
ang/civicase/dashboard/directives/dashboard-tab.directive.html
api/v3/Case/Getdetails.php
api/v3/Case/Getstats.php

This PR automatically refreshes the case stats every time the case filters change.
The `Getstats` action had a regression issue introduced by https://github.com/compucorp/uk.co.compucorp.civicase/commit/6829b1a644ef778a62b8c1532041b27364977c23#diff-7e05760a6cb00db1b09138c9665389dfL30
As you can see, the new code is referencing the `$sql` variable when it meant to reference `$query`. This was fixed.
The `Getstats` API action only had filters to get stat data for the current logged in user, but it was missing filters for for an arbitrary manager, or an involved contact. The code from the `Getcasedetails` action was extracted into two helper classes:
```php
<?php
class CRM_Civicase_APIHelpers_CasesByManager {
static function filter($query, $caseManager) {
if (!is_array($caseManager)) { …
```

C51-360: Update case stats on case filters change

---

CRM/Civicase/Hook/Helper/CaseTypeCategory.php
CRM/Civicase/Hook/PostProcess/CaseCategoryCustomFieldsSaver.php
CRM/Civicase/Hook/PreProcess/CaseCategoryCustomFieldsAdder.php
CRM/Civicase/Hook/PreProcess/CaseCategoryCustomFieldsSetDefaultValues.php
CRM/Civicase/Setup/AddCaseCategoryCgExtendsValue.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0004.php
civicase.php

This PR modifies the Add case page at `civicrm/case/add` to include custom fields for a case type category. 
This functionality does not exist.
The Case category custom fields are added.
- When fetching Case Type Custom fields to be added to the Add Case form, an additional check is added via a hook to check if the case type belongs to a case category that has custom fields. If there is, the custom fields are added as part of the custom fields set to be displayed on the form.
A function was added to the `CRM_Civicase_Hook_PreProcess_CaseCategoryCustomFieldsAdder` t take care of this
```php
private function addCaseCategoryCustomFields(&$form) {
$form->_type = 'CaseCategory';
$caseTypeCategoryHelper = new CaseTypeCategoryHelper();
$caseCategoryId = …
```

RSE-227: Modify Add Case Page To Show Custom Fields For Case Categories

---

CRM/Civicase/Hook/BuildForm/CaseClientPopulator.php
CRM/Civicase/Hook/BuildForm/FilterCaseTypeByCategory.php
civicase.php
phpcs-ruleset.xml

This PR filters the case type select field on an Add Case form when a category option is provided in the URL. The case types is filtered to contain only Case Types that belong to the specified category.
For example a URL `http://local.buildkit/civicrm/case/add?reset=1&action=add&category=prospecting` will filter the Case types field to return only case types related to the Prospecting case category.
Functionality was not present
Functionality is added.
The `hook_buildForm` was used to fetch the options for this case type field and these options were modified depending on the category value in the URL.
```php
private function filterCaseTypeOptionValues(CRM_Core_Form $form, $caseCategoryName) {
$caseTypesInCategory = $this->getCaseTypesForCategory($caseCategoryName);
if …
```

RSE-181:  Filter Available Case Types By Category Value In URL On Add Case Form

---

ang/civicase.ang.php
ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/case/search/directives/search.directive.js

As part of this PR, filtering by case type category is added to `Manage Cases` page.
1. Linting fixes and refactoring has been done to `civicase.ang.php`. All the code has been moved to separate small functions to make it more manageable.
**Filtering using Case Type Category**
1. Case type categories Option Values has been exposed to frontend global variable named `CRM.civicase.caseTypeCategories`.
2. The Case category value for each case type is exposed using the existing `CRM.civicase.caseTypes` global variable.
3. A new function `setCaseTypesBasedOnCategory` is created, which is called at init, and also when `filters` are changed. It checked if the `case_type_category` filter is present, and filters the `CaseTypes` for that category.
4. `case-list-table.directive.js` reads the …

RSE-184: Filter by Case Type Category in Manage Case

---

Civi/CCase/Utils.php

Previously the following Apis used to return a Syntax Error
- Getdetails
- Getstats
- Gettypedetails
The API return values without any error.
**When this bug will occur**
If we create a `Relationship Type`, where 
`A to B`label is `CEO for` and 
`B to A`  label is `CEO`.
Then if we create a new Case Type, where we add both `CEO` and `CEO for` relationship.
Now previously `getRelationshipTypesListByCaseRole` function used to only fetch `name_b_a` for relationships, and then used to match it with the Relationship coming from Case Types.
```php
$relationshipTypes = civicrm_api3('RelationshipType', 'get', array(
'options' => array('limit' => 0),
'return' => array('name_b_a'),
));
```
Problem with this is, if both `A to B` and `B to A` relation is used in Case Type, then the `A to B` relation …

C51-360: Fix Get relationship by case role bug

---

ang/civicase/dashboard/directives/dashboard.directive.html
ang/civicase/dashboard/directives/dashboard.directive.js
civicase.php

#197  adds a way to allow the Add case URL to be configurable. This PR allows the New Case on the navigation menu and the Add case button on Case dashboard to use this functionality. If an alternate add new case URL is set, the new URL is used rather than the default behaviour for these menus.
The new case on navigation and the Add Case button on the cases dashboard is not configurable

C51-418: Configurable 'New Case' button

---

CRM/Civicase/Helper/CaseCategory.php
api/v3/CustomValue/Gettreevalues.php

Civi provides a `CustomValue.gettree` API that allows to provide an entity ID e.g a Case ID and it will return the Custom group, Custom fields and the Custom field values for that entity ID. 
Since we are now establishing the concept of Case categories and a case type can belong to a case category(Say Prospect) and it will have custom groups extending that category, there is a need to refactor this API to understand this concept and appropriately get a Case Id's category and  return the custom groups and fields belonging to that category for the Case ID
To fix this a new API `CustomValue.gettreevalues` was created in the Civicase extension, the API contains majorly code from the core `CustomValue.gettree` API but with some customizations to fix the issue described above.
- The API does …

RSE-217: Add CustomValue.getTreeValues API

---

ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/factories/get-case-query-params.factory.js
ang/test/mocks/data/cases.data.js

As part of https://github.com/compucorp/uk.co.compucorp.civicase/pull/226, a new endpoint `getTreeValues` was introduced. In this PR the same is used.

RSE-237: Change CustomValue Endpoint

---

CRM/Civicase/Hook/PostProcess/ProcessCaseCategoryCustomFieldsForSave.php
CRM/Civicase/Hook/PreProcess/ProcessCaseCategoryCustomFieldsForEdit.php
civicase.php

Currently, When adding a new Case for a case category e.g Prospect, the custom fields saved with the case are not editable. This PR fixes the issue.
- The Custom field values on Manage Case category page is not editable.
- The Custom field values on Manage Case category page are now editable.
- Hook PreProcess and Hook PostProcess was implemented to check if the case type category is not of case (Civi already takes care of this by default), then the custom fields are added for editing and saving for the relevant case category.

RSE-241: Allow Editing Of Custom Fields on Manage Case Category Page

---

api/v3/Case/Getstats.php

Currently the `Case.getstats` API does not support filtering by case type categories. This is really needed as we need to be able to return results based on the category filter.
- The `Case.getstats` API does not support filtering by case type categories
- The `Case.getstats` API now supports filtering by case type categories
The API can now be called as follows: 
```php
civicrm_api3('Case', 'getstats', [
'case_type_id.case_type_category' => ['IN' => ["Prospecting", "Cases"]],
]);
civicrm_api3('Case', 'getstats', [
'case_type_id.case_type_category' => "prospecting",
]);
```

RSE-187: Case Category filter support for  "Case.getstats"

---

ang/civicase/case/directives/case-overview.directive.js
ang/civicase/dashboard/directives/dashboard.directive.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
ang/test/mocks/data/case-type-category.data.js
ang/test/mocks/data/cases-types.data.js
package-lock.json

As part of this PR, the Dashboard of Civicase supports filtering Cases and Activities by Case Type Category.
1. In `dashboard.directive.js`, the `case_type_category` query string is saved inside `$scope.filters.caseTypeCategory` variable. Which in turn is saved inside `$scope.activityFilters.case_filter`, and this takes care of filtering all records(case/activities) in both Dashboard and Activities tab.
2. In `case-overview.directive.js`, the shown Case Types are also filtered.

RSE-183: Filter Dashboard records with case type category

---

ang/civicase/case/actions/directives/case-actions.directive.js
ang/civicase/case/details/directives/case-details.directive.js

Previously, when Pledge/Contribution was edited, the Custom field values did not get updated. This PR fixes that.
1. In `case-actions.directive.js`, `$rootScope.$broadcast('updateCaseData');` is fired to fetch the latest data.
2. In `case-details.directive.js`, added a check to eliminate console errors
```js
if ($scope.item && data && data.id === $scope.item.id) {
```

RSE-175: Add refresh logic

---

CRM/Civicase/Hook/BuildForm/CaseCategoryCustomFieldsProcessing.php
CRM/Civicase/Hook/BuildForm/FilterByCaseCategoryOnChangeCaseType.php
CRM/Civicase/Hook/Helper/CaseTypeCategory.php
civicase.php

When changing a case type for a case, a user is presented with all the case types in the system. This PR fixes that and only allows users to change to another case type that is in same category for that case.
User can change case type to any case type.
User can change to only case type within the case category

RSE-270: Only Allow Case type to be changed to another Case Type within the Same Category

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Setup/AddCaseTypesForCustomGroupExtends.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step004.php

We can already add Custom Groups to extend cases but the issue is that in the field for selecting case types, all case types are shown. We only need case types belonging to the Case category. This PR fixes that issue.
- The UI shows that Custom Groups can extend Cases for all case types.
- Custom Groups can extend Cases for all case types in the case category. The UI is changed to reflect this.
Civicrm uses the description field for the option value to determine which function to use to fetch the object subtypes. See [Here.](https://github.com/civicrm/civicrm-core/blob/b2ccd9fe6cb84d96d35c85582418311509f9af9b/CRM/Core/BAO/CustomGroup.php#L2084-L2101).
This PR adds a new function to only fetch case types for the cases category. The description field for the Cases option value is updated to …

RSE-216: Case Custom Fields UI Solution For Cases Category

---

CRM/Civicase/Setup/UpdateMenuLinks.php
CRM/Civicase/Upgrader/Steps/Step0005.php
civicase.php

As part of this PR, the Dashboard and Manage Cases menu item for Cases has been changed so that it filters Cases with `cases` case type category only.
New Class `UpdateMenuLinks` and `Step0005` has been created to change Manage Cases menu.
In `civicase.php` the Dashboard menu item link is changed.

RSE-168: Change Case Menu URLS

---

CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForChangeCase.php
CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForNewCase.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForChangeCase.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
ang/civicase/activity/actions/directives/activity-actions.directive.js
ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.js
civicase.php

This PR makes a couple of changes:
- Word replacement changes for Change Case Type Form
- Word replacements for activities bulk actions
- Word replacements for Calendar on Manage Case category dashboard.
- Word replacements for the Change Case Type form was done by adding thw word replacements for the relevant case category into civi's translation locale via the PreProcess hook. All form labels that are displayed using the `ts` function will automatically be translated to the right word out of the box, however Civi did not run some form labels through the `ts` function e.g the `Case Type` label and this had to be done manually in the buildForm hook.
- The FE screens fix was simply to import the `ts` service and use in the relevant screens in order to effect the word replacements.

RSE-271: Case Type Category Word Replacements

---

ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.html

This PR reverts some changes made in last PR. Some api fields were wrapped in civi's translation function. However when some of these fields are `NULL`, it gives un-desirable results as the screen displays the variable name. To avoid this as described in the translation [best practices](https://docs.civicrm.org/dev/en/latest/translation/#best-practices), it is good to include word in strings in addition to the variables. However since the translation for API fields are not working as it should, for now, I have removed the `ts` function.

RSE-271: Case Category Word Replacement Changes

---

ang/civicase.ang.php
ang/civicase/dashboard/directives/dashboard.directive.html
ang/civicase/dashboard/directives/dashboard.directive.js
civicase.php

This PR fixes some issues that came up when creating a PR #244 to merge `prospect-develop` into `develop.`
This PR #203 brings about some changes that needs to be factored in when determining the URL for the Add Case button on the Manage Case page.
The fix was to add a new variable `defaultCaseCategory` that allows us determine the correct URL for the Add Case button taking the `newCaseWebformUrl` into consideration.
```php
<a ng-if="checkPerm('add cases') && caseTypeCategoryName == defaultCaseCategory && !newCaseWebformUrl"
ng-href="{{ url('civicrm/case/add', {reset: 1, action: 'add', context: 'standalone'}) }}"
class="btn btn-primary crm-popup civicase__dashboard__add-case"
crm-popup-form-success="refresh()">
<i class="material-icons">add_circle</i>{{ ts('Add Case') }}
</a>
<a …
```

Resolve Merge Conflicts Plus Fix Issues with Add Case button

---

CRM/Civicase/Hook/Post/PopulateCaseCategoryForCaseType.php
CRM/Civicase/Setup/MoveCaseTypesToCasesCategory.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0007.php
civicase.php

After merging the work done on Case Type category to the develop branch, the develop site does not show cases when visiting the Dashboard. 
This is rightly so because the case types on the site does not have a case category assigned and we don't have a UI to do this.
This PR adds an upgrader to mark all existing case types without a case category to be of category Cases when case extension is upgraded/installed. Also when adding a new case type, the case category is set to be of Cases by default via a `civicase_civicrm_post` hook.
Existing/New Case types will not have a default Case category assigned. 
The Cases category is assigned by default to existing case types without a case category or for new case types.
Installing the prospect extension comes with it's own case type Default …

RSE-336: Move New/Existing Case Types To Case Category.

---

CRM/Civicase/Upgrader.php

Removed Object Type hinting in the `CRM_Civicase_Upgrader` upgrader class as it was preventing upgraders from running on the Civicase Dev site.
Object Type Hinting is not available for PHP Version < [7.2](https://wiki.php.net/rfc/object-typehint). So this is removed.
The dev site will be upgraded to 7.2 ASAP after the next release is done.

 RSE-336: Removed Object Type hinting

---

CRM/Civicase/APIHelpers/ActivityQueryApi.php
CRM/Civicase/APIHelpers/EntityTagQueryApi.php
CRM/Civicase/APIHelpers/GenericApi.php
api/v3/Activity/Copybyquery.php
api/v3/Activity/Deletebyquery.php
api/v3/Activity/Movebyquery.php
api/v3/EntityTag/Createbyquery.php
api/v3/EntityTag/Deletebyquery.php

When accessing activities for a contact on the Activities tab on the contact summary page for a contact that has a lot of activities (say ~10k), the page becomes un-responsive.
After investigation, the reason for the slowness was because the FE has to fetch all the activity ID's so that they can be used for performing bulk actions like `Delete All`, Move to Case` e.t.c. 
This PR fixes that issue by moving the bulk action operations to the Back End such that the Front end does not need to fetch all the activity Id's, all the FE needs to send to the newly created API;s is the API parameters needed to fetch the activities from the database or a list of Activity Id's , the BE will then fetch these Id's and perform the bulk operations.
When accessing activities for a contact on the Activities …

BASW-515: BE Solution for Activity Feed Causes Major System Slowdown

---

ang/civicase/activity/actions/directives/activity-actions.directive.html
ang/civicase/activity/actions/directives/activity-actions.directive.js
ang/civicase/activity/actions/services/delete-activity-action.service.js
ang/civicase/activity/actions/services/move-copy-activity-action.service.js
ang/civicase/activity/actions/services/tags-activity-action.service.js
ang/civicase/activity/feed/directives/activity-feed.directive.html
ang/civicase/activity/feed/directives/activity-feed.directive.js
ang/civicase/activity/filters/directives/activity-filters.directive.html
ang/civicase/activity/filters/directives/activity-filters.directive.js
ang/civicase/bulk-action/directives/bulk-actions-message.directive.html
ang/civicase/bulk-action/directives/bulk-actions-message.directive.js

When accessing activities for a contact on the Activities tab on the contact summary page for a contact that has a lot of activities (say ~10k), the page becomes un-responsive.
After investigation, the reason for the slowness was because the FE has to fetch all the activity ID's so that they can be used for performing bulk actions like Delete All, Move to Case` e.t.c.
https://github.com/compucorp/uk.co.compucorp.civicase/pull/259 fixes that issue by moving the bulk action operations to the Back End such that the Front end does not need to fetch all the activity Id's. In this PR, the FE uses the newly created API's.
**In `delete-activity-action.service.js`**
New service  is created, where deletion action code is moved.
**In `activity-feed.directive.js `**
1. Logic for Select All has …

BASW-517: FE Solution for Activity Feed Causes Major System Slowdown

---

ang/civicase/case/actions/directives/case-actions.directive.js

This PR fixes console errors related to Manage Case Page.
No console errors.
In case the `caseActionService` is not found, angular was throwing Injector Not Found error. So the code is placed inside a `try/catch` block.

BASW-514: Fix case action error

---

ang/civicase.ang.php
ang/civicase/case/details/directives/case-details-header.html
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/directives/case-overview.directive.html
ang/civicase/case/directives/case-overview.directive.js

In the following placed the field “civicrm_option_value.weight” is not respected in the ordering. Case status should be ordered by the weight property.
Case dashboard
Case dashboard select items
https://nimb.ws/ehKJ2i
Change case status on case itself.
https://nimb.ws/3ka1G4
The case status order was not obeying the weights.
https://nimb.ws/ehKJ2i
https://nimb.ws/3ka1G4
Now case status in the above areas obey weight and are sorted based on that.
In the following 'testfirst' had the lowest weight, and 'test1' had the most weight.
In civicase.ang.php, the 'weight' attribute was added to the options array so that for case statuses we have the weight. This was then used in case-details.directive.js and case-overview.directive.js to sort and index them by weight. case-details-header.html and …

CATL-1115: Fix Case Status Order In Case Dashboard Pages

---

CRM/Civicase/Form/CaseWebforms.php
templates/CRM/Civicase/Form/CaseWebforms.tpl

1. On case webforms page (civicrm/case/webforms), add saved notification on save. Stay on same page after save.
https://nimb.ws/jteH1F
2. Update to use correct markup to have shoreditch looking table if possible.
The above 2 issues were not addressed.
Both the above issues are handled.
The save notification was added to CaseWebforms class using CRM_Core_Session::setStatus.
The markup of the case webforms page was modified to support UI based on Shoreditch theme.

CATL-1120: Add Case Webforms Notification And Fix Theme Based On Shoreditch

---

CRM/Civicase/Activity/ContactActivitiesSelector.php
ang/civicase/activity/calendar/directives/activities-calendar.directive.js
ang/civicase/activity/feed/directives/activity-feed.directive.js
ang/civicase/case/factories/get-case-query-params.factory.js
ang/civicase/dashboard/directives/dashboard-tab.directive.js
api/v3/Activity/Getdayswithactivities.php
api/v3/Case/Getdetails.php

As part of this PR the Bulk Emails have been hidden from the Civicase.
From the following files/components, the Bulk Email activities are filtered
1. `activities-calendar.directive.js`
2. `activity-feed.directive.js `
3. `get-case-query-params.factory.js`
4. `dashboard-tab.directive.js`
5. `Getdayswithactivities.php`
6. `Getdetails.php`

CATL-1134: Dont show Bulk Email

---

ang/civicase.ang.php
civicase.php

As part of this PR
* Bulk Email Activity Type is removed from Activity Feed filters.
1. In `civicase.ang.php`, added a new function `remove_bulk_email_activity_type` to remove Bulk Email Activity.

CATL-1134: Remove Bulk Email from Filters dropdown

---

ang/civicase.ang.php
ang/civicase/activity/filters/directives/activity-filters.directive.js

This PR changes the implementation to Remove Bulk Email from filters.
Previously the Bulk Email was removed using BE, but this way the user cant create Bulk Email. So the implementation is moved to FE.

CATL-1134: Remove Bulk Email from FE

---

ang/civicase/activity/feed/directives/activity-feed.directive.js
api/v3/Activity/Getactionlinks.php

When Payment type Activity is present, the Activity Load does not load.
Also the Month Nav is visible now.
1. Moved the `getactionlinks` Chained API call into a new function.
2. `getactionlinks` Chained API call is only applied to fetch the Activities, and not to other calls, which fixes the Month Nav.
3. In "api/v3/Activity/Getactionlinks.php" `_civicrm_api3_activity_getActivityActionLinks` function, the `CRM_Activity_Selector_Activity::actionLinks` call generates throws an error for Payment type Activities.
This is because `actionLinks` calls `CRM_Core_DAO::getFieldValue('CRM_Event_BAO_ParticipantPayment', $sourceRecordId, 'participant_id', 'contribution_id')`. Here `$sourceRecordId` is empty, so an error is thrown https://github.com/civicrm/civicrm-core/blob/b064b7052ff2cb2b490a05266b4e …

CATL-1145: Activity feed Doesnot load when Payment type Activity is present.

---

ang/civicase/activity/filters/directives/activity-filters.directive.js

This PR fixes an issue with the Case Activities' filters where filtering by activity type was not working.
The issue happens because on https://github.com/compucorp/uk.co.compucorp.civicase/pull/267 we started filtering the option values. The problem is that when you use lodash's `filter` method, the index values are not preserved.
As an example on this screenshot you can see that "Secure temporary housing" now has the index value for "Medical Evaluation":
To fix this we use the option's value property instead of the index:
```js
function mapSelectOptions (option) {
return {
id: option.value,
text: option.label,
color: option.color,
icon: option.icon
};
}
```
Both `CRM.civicase.activityStatuses` and `CRM.civicase.activityTypes` (the objects mapped using `mapSelectOptions`) have a `value` …

CATL-1147: Fix activity filters

---

CRM/Civicase/Helper/CaseCategory.php

The Prospect Case category custom financial fields were not showing up on the dev site and this is also replicated on local for a fresh prospect extension installation.
The Prospect Case category custom financial fields were not showing up on the dev site and this is also replicated on local for a fresh prospect extension installation.
The `CaseCategory` helper class has  some functions that uses the `CaseType::buildOptions('case_type_category')` for fetching the case category option label and the id for some processing.  The issue with this is that the option label can be changed by the user on the UI and this is not reliable.
Also the Prospect extension adds the Prospect case type category with the name `Prospecting` and the label …

RSE-377: Fix Issue With Not Displayed Prospect Financial Custom Fields

---

info.xml

As we are moving to a new workflow, where the `develop` branch wont exist anymore. So merging from `develop` to `master`, before getting rid of `develop` branch.

RSE-439: Merge to Develop

---

ang/civicase/contact/directives/contact-popover-content.directive.html
ang/civicase/contact/services/contacts-cache.service.js

Previously Contact phone numbers were not mapped correctly, this PR fixes that.
Correct Phone Numbers in Contact Record Page
1. In `contacts-cache.service.js`, the api call has been changed, and now the Location Type ID is also fetched.
```javascript
'return': ['phone', 'phone_type_id.name', 'location_type_id'],
'api.LocationType.get': { 'id': '$value.location_type_id' }
```
2. A new function `prepareContactPhoneNumbers` has been created, which Adds the Location type with the Phone number to get a correct mapping of phone numbers.
3. `contact-popover-content.directive.html` is edited, here  a loop is created for `contact.phoneNumbers`.
Unit tests are not working inside vagrant, I will create a ticket to fix this.

BASW-544: Show all phone numbers

---

info.xml

**Fixes:**
- Fixed Civicase unit tests and added JsDoc.
- Fixed permission issues that does not allow a user without administer Civicrm permission to view Manage Cases page.
- Fixed issue with Reassigning case manager role to the same user.
- Member modal pop-up on CiviCase now matches that of contact record data.
- Fixed Filtering by activity type not working on manage case activities tab.

Release v1.0.0-alpha11

---

CRM/Civicase/XMLProcessor/Report.php

Selecting activities under the Activities tab in manager cases and printing report generates a report but the activities section is missing data.
When Selecting activities under the Activities tab in manager cases and printing, the activities section is missing data.
When Selecting activities under the Activities tab in manager cases and printing, the activities section now has data.
The timeline is passed in via the URL for printing reports, for a case type that does not have a timeline, this results in an empty result for activity types and subsequently no activities are returned. See [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/XMLProcessor/Report.php#L100)
Rather than checking if the timeline name is set, we also need to check if the timeline …

CPS-9: Activities missing on Print Report

---

CRM/Civicase/Upgrader.php

The Custom group/fields page `civicrm/admin/custom/group` becomes inaccessible when the civicase extension is disabled shows an error.
An error `Warning: require_once(CRM/Civicase/Helper/CaseCategory.php): failed to open stream: No such file or directory in require_once() (line 2099 of /var/www/site/profiles/compuclient/modules/contrib/civicrm/CRM/Core/BAO/CustomGroup.php).`
Custom group page is accessible when civicase extension is disabled.
A class was added [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Setup/AddCaseTypesForCustomGroupExtends.php#L14) as part of the parameters for the option group value for the `cg_extend_objects` that allows the Case Types returned on the Custom Group page when adding a custom field set to a Case to only be those …

CATL-1141: Fix Custom Group Page inaccessible when Civicase extension is disabled

---

ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js

This PR hides deleted cases from the contact's cases tab
Case #1 had been deleted but is still shown
We added `is_deleted: 0` to the params passed to the API when requests the contact's cases.

CATL-1142: Hide deleted cases from contact's case tab

---

ang/civicase-base/services/case-status.service.js
ang/civicase-base/services/case-type.service.js
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
ang/civicase/case/search/directives/search.directive.html
ang/civicase/case/search/directives/search.directive.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/test/civicase-base/services/case-status.service.spec.js
ang/test/civicase-base/services/case-type.service.spec.js
ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
ang/test/civicase/case/search/directives/search.directive.spec.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
ang/test/karma.conf.js

This PR fixes an issue that happens when trying to open the case details page for a case that has any status other than "Opened".
This PR closes #251 for *Before* and *After* screens of the issue please find them in the previous PR.
It also fixes a regression issue related to the case search title.
The issue happens because the case manager filters by "Opened" cases by default. Since the selected case has a different status they are completely and the details can't be shown.
To fix this we pass the status id through the URL which in turn is read by the manager and the case can be properly fetched. 
The regression was introduced after we started filtering cases by category on the dashboard. The issue happens because the title can only be built for case type or case status filters. If any …

CATL-1128: Fix open case details

---

CRM/Civicase/Upgrader.php

The When installing the civicase extension for a site, after installation, there is a notice that extension updates are available. This should not happen as a fresh install of the extension should set the schema version to the version of the latest upgrader.
The scenario described above is observed.
After installing the civicase extension the schema version column for the extension record in the database has the Upgrader class name rather than the latest version number. i.e `CRM_Civicase_Upgrader_Steps_Step0007`
After installing the civicase extension the schema version column for the extension record now has the latest version number and there is no notice that extension updates are available.
The Civicase extension follows the new way of adding upgraders described …

CATL-1129: Fix pending upgrader issues after Civicase install.

---

civicase.php

When a user with the Role Civicase user visits the Activities tab for a contact, the user is unable to view the activities. 
When displaying the contact card for an activity, the `LocationType.get` API is used to get the location for the contact phone number. This API uses the default permission of `administer CiviCRM`. The Civicase user does not have this permission hence the error. 
The fix is to add the `view all activities` permission in addition to the default permission required to access this API. The Civicase user has the `view all activities` permission assigned by default.
Also set the permission for the custom `RelationshipType.getCaseRoles` API to use same permission as RelationshipType.get which is `access CiviCRM`.

BASWSPRT-84: Fix User cannot view contact activities without "CiviCRM: administer CiviCRM" 

---

ang/civicase/case/directives/case-overview.directive.html

This PR fixes an issue where case types would not be shown on the overview breakdown of the dashboard when only a single case type was available.
The issue was introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/96 when the overview table was first introduced. It's not clear if it was made by design or if this is an actual feature, but it was requested to be removed.
The value was set to zero instead of completely removing the `if` to avoid showing the arrow when no case types are defined which would be confusing for the user.

CATL-1133: Fix overview dropdown issue

---

CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php

This PR fixes the error that breaks Javascript and causes the pivot table to be shown below
The Case Activity Pivot Table report fetches the Contact data for the case roles involved in a Case.
This means that when the Contact data for the Case roles are fetched, we need to alias Contact table in the JOIN  for each case role contact data in order to distinguish the join to contact table for each of the case roles involved.
This is done by prefixing the Contact table for each case role contact data with the Case role/relationship name, the contact fields are also aliased with this prefix(https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php#L97). This is fine but when adding these fields as form elements, Extended Report …

CPS-27: Strip strange characters from role names

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html

In the Contacts Case tab, contacts added as non client relationships were being shown as clients, this PR fixes the same.
Previously all contacts with relationship were shown, now only the client are being shown.

CPS-29: Fix wrong client in case contact tab

---

ang/civicase/activity/directives/add-activity-menu.directive.js
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/factories/get-case-query-params.factory.js
ang/civicase/case/list/directives/case-list-table.directive.html
ang/civicase/case/list/directives/case-list-table.directive.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
ang/test/global.js

As part of this PR, the case type category is being sent to backend for the Manage Case screens. This is used to validate whether the logged in user has permission to view case of a particular case type category.
1. In `case-list-table.directive.js`, setting the default Case Type category. So that incase even if browser URL does not have the case type category mentioned, still the case type category will be sent to backend.
2. In `case-list-table.directive.html`, the case type category is sent to the `civicase-case-details` directive. Which send the same to the `getCaseQueryParams` factory. Inside `getCaseQueryParams`, the Case Type Category is sent to BE via API call.

RSE-355: Send case category from FE

---

api/v3/CustomValue/Gettreevalues.php

Civi does not support `CaseType` entity when fetching the custom field values, this PR adds this functionality in `CustomValue.gettreevalues` API.
Getting `CustomValues` with `CaseType` entity was not possible.
It is now possible to get values for Awards `CaseType` entity

RSE-667: Add Functionality for Awards Custom Fields

---

CRM/Civicase/Hook/alterAPIPermissions/Case.php

Each case category like Awards, Prospects now have their own respective permissions defined and the permission is needed to access the respective pages for each of the categories.
When testing this functionality, an errors came up for the Award manager when trying to create an Award : `API Permission check failed for CaseType/create call: insufficient permission: require Administer Civicase`
Error when Award manager is trying to create an Award.
The CaseType.create API requires the `Administer Civicase`. The PR fixes the issue by using the equivalent `Administer Civiawards` permission when the case type category is awards. The award manager already has the `Administer Civiawards` permission and hence is able to create the Award.

RSE-298: Fix Permission Errors

---

CRM/Civicase/Hook/PageRun/ViewCasePageRedirect.php

When a new case is created(any case type), the browser gets redirected to Manage Cases page. But the url should contain the 'case_type_category' value, so that cases from that category is shown. This was not happening before. This PR fixes the same.
`civicrm/case/a/?case_type_category=cases#/case/list?sf=id&sd=DESC&caseId=13&cf=%7B%22status_id%22:%5B%22Open%22%5D,%22case_type_id%22:%5B%22adult_day_care_referral%22%5D%7D`
`civicrm/case/a/?case_type_category=cases#/case/list?sf=id&sd=DESC&caseId=12&cf=%7B%22case_type_category%22:%22cases%22,%22status_id%22:%5B%221%22%5D,%22case_type_id%22:%5B%22adult_day_care_referral%22%5D%7D`
1. In `ViewCasePageRedirect.php`, added `case_type_category` query string which is used by angular.
2. Also, the url now sends `status_id` instead of status name. …

RSE-298: Fix Case Creation URL

---

ang/civicase-base/providers/case-type.provider.js
ang/civicase-base/providers/dashboard-case-type-items.provider.js
ang/civicase/case/directives/case-overview.directive.html
ang/civicase/case/directives/case-overview.directive.js
ang/civicase/dashboard/directives/dashboard-tab.directive.js
ang/test/civicase-base/providers/dashboard-case-type-items.provider.spec.js
ang/test/civicase/case/directives/case-overview.directive.spec.js

This PR changes how the case type buttons are configured to allow custom templates to be used instead of defining buttons through configuration objects.
**Important:** This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/48. Please refer to this one for Before and After pictures.
* the `DashboardCaseTypeButtons` was renamed to `DashboardCaseTypeItems` and it now accepts a `templateUrl` parameter. This is used to include the template next to the corresponding dashboard case type.
* There was an issue introduced by https://github.com/compucorp/uk.co.compucorp.civicase/pull/318 when loading case types. It would load all case types, even those that were not active. This was fixed.

RSE-643: Dashboard Case Type Buttons custom templates

---

ang/civicase/case/actions/services/print-case-action.service.js

When clicking the Print case action on the actions menu for a case, the case activities are not displayed in the report.
Case activities are not displayed in the print case report:
Case activities are now displayed in the print case report:
Part of the parameters passed to the report URL is the timeline parameter and it is hardcoded to `standard_timeline` , the implication of this is that the report will only generate activities report for activity types added to the standard timeline, if the standard timeline has no activity types added, the activities section on the report will be empty, See [here](https://monosnap.com/file/OY376OmhcAAP8KOqnHxM76ROeqha9k) 
This fix of removing this parameter ensures that reports will always be generated for all activities on the case.

BASW-566: Fix Activities are not displayed on print case action

---

CRM/Civicase/Hook/PostProcess/SetUserContextForSaveAndNewCase.php
civicase.php

When creating a new Case of a particular case type category on the Case add form and the `Save and New` button is clicked, rather than redirect to the new Case form view for the case type category, it redirects to the default Case type form. This PR fixes the issue.
Issue described in overview exists.
When creating a new Case of a particular case type category on the Case add form and the `Save and New` button is clicked it opens a new for for the case type category.
The Case form to be opened is determined by the case type category parameter passed in the URL e.g for the Case creation for the Award form: `civicrm/case/add?case_type_category=prospecting&action=add`. When the `Save and New` button is clicked, rather than use the entry URL for accessing the form, Civi discards the URL …

RSE-711: Fix Issue With Clicking On Save And New Button Shows Original Case Type Instead Of Case Category Form

---

CRM/Civicase/Hook/alterAPIPermissions/Case.php
CRM/Civicase/Service/CaseCategoryPermission.php
ang/civicase.ang.php

When a new case type category is added, some dynamic permissions are generated for the case type category derived from the original Civicase permissions. One of such permission is the `administer CiviCase` permission. The awards category variant will be `administer CiviAwards`. This PR removes the process of generating category permission variant for this particular permission. We only want `administer CiviCase` and no other case type variant.
- Case type category variants for the `administer CiviCase` permission e.g `administer CiviAwards` exists
- Case type category variants for the `administer CiviCase` permission e.g `administer CiviAwards` no longer exists
The permission `ADMINISTER_CASE_CATEGORY` key in the `get` function of the CaseCategoryPermission service was removed. Other …

RSE-298: Remove the Administer Case Category Permission.

---

ang/civicase/activity/filters/directives/activity-filters-contact.directive.html

This PR changes the help text for some of the activity filters.
- The text on `activity-filters-contact.directive.html` was updated.

BD-23: Change activity filters help text

---

ang/civicase-base/providers/activity-forms.provider.js
ang/civicase/activity/activity-forms/activity-forms.config.js
ang/civicase/activity/activity-forms/services/activity-popup-form.service.js
ang/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.js
ang/civicase/activity/activity-forms/services/view-activity-form.service.js
ang/civicase/activity/factories/check-if-draft-email-or-pdf.factory.js
ang/civicase/activity/factories/view-in-popup.factory.js
ang/civicase/activity/panel/directives/activity-panel.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.js
ang/test/civicase-base/providers/activity-forms.provider.spec.js
ang/test/civicase/activity/activity-forms/activity-forms.config.spec.js
ang/test/civicase/activity/activity-forms/services/activity-popup-form.service.spec.js
ang/test/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.spec.js
ang/test/civicase/activity/activity-forms/services/view-activity-form.service.spec.js
ang/test/civicase/activity/factories/check-if-draft-email-or-pdf.factory.spec.js

This PR allows other extensions to define the URL to use when viewing an activity depending on its type and the way the form should be shown.
For before and after please check https://github.com/compucorp/uk.co.compucorp.civiawards/pull/51
A new activity form provider has been added. It can be used to define the services that will return the form URLs. For example:
```js
ActivityForms. addActivityForms([
{
name: 'MyCustomForm',
weight: 1
}
]);
```
The `name` should be the name of the service to inject, and the `weight is the priority compared to other services. Only one service will be used to determine the URL.
The services themselves should define 2 functions:
* `canHandleActivity` which should return `true` if the service can return the form URL taking into consideration the activity …

RSE-644: Show reviews form

---

CRM/Civicase/Hook/PermissionCheck/CaseCategory.php

When the Award Manager tries to change a Case or Application status, An error occurs
When the Award Manager tries to change a Case or Application status, the case status is changed successfully.
The permissions required to access the `civicrm/case/activity`  i.e the page for changing the case activity status are civicase permissions ([See](https://github.com/civicrm/civicrm-core/blob/master/CRM/Case/Form/Activity.php#L88)). The Award manager does not have these permissions but have the award case category equivalent for these permissions.
The fix was to add this page to the list of pages that will translate civicase permission to the equivalent case category permissions based on the Case ID parameter in the URL.

RSE-774: Fix issue with Changing Case Activity Status For Award Manager

---

ang/civicase/case/directives/case-overview.directive.html

As part of this PR, the link from Case Overview to Manage Cases page has been fixed.
Previously when clicking on any 'Case Status' or the 'Case Status Count' in the Case Overview of Dashboard section, browser redirected to Manage Cases page, but the Clicked Status was not set as a filter. Also there were console errors.
This PR fixes the same.
This is a regression issue. As part of https://github.com/compucorp/uk.co.compucorp.civicase/pull/290, the url expects `status_id`s to be set, but in `case-overview.directive.html` this was missed, where still Status Name was being set to the url.

BASWSPRT-98: Fix case overview link

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

When saving a report instance for the "Case with Activity Pivot Chart" report the filters are not displayed correcting next time when viewing the saved report. For example the Aggregate function gets displayed as 'COUNT' even if SUM or COUNT UNIQUE was used in creating the report instance
The scenario described in overview exists.
The filters used in creating a report instance are saved and displays correctly when viewing the saved report.
The "Case with Activity Pivot Chart" report sets some defaults that override the saved form values for the instance in the db as seen [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Report/Form.php#L1040) that the defaults take precedence in displaying form values.
To fix this. The defaults are only set for viewing a fresh form report …

CPS-57: [Cases / Reports] Aggregate function gets saved as "Count" in "Case with Activity Pivot Chart" report

---

CRM/Civicase/Hook/BuildForm/EnableCaseCategoryIconField.php
CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
civicase.php

Currently Civi only allows icons to be set for Activity Type option group icons in the UI([See](https://github.com/civicrm/civicrm-core/blob/master/CRM/Admin/Form/Options.php#L159-L174)). We need to be able to set these icons for Case type category option group values also. This PR makes that happen. Also when generating case contact tabs for case categories, these icon set for the case categories are used.
- Icons can not be set for case type categories in the UI
- Case contact tabs for case categories uses default icons
- Icons can now be set for case type categories in the UI
- Case contact tabs for case categories uses icons set in the icon field for the option value.
- The [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/331) for generating the menus dynamically when a …

RSE-790:  Allow Icon Field For Case Categories

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

When saving a Case with Activity Pivot Chart report and selecting the option to include in civicrm dashboard. When this report added as a dashlet to the dashboard, it simply does not show any data.
Case with Activity Pivot Chart report does not show in dashlet.
It turned out that setting the chart parameter to TRUE for the Case with Activity Pivot Chart caused this issue. This has always been an existing issue and is not a regression.
Setting the parameter to FALSE fixed the issue.
When the chart parameter is TRUE,  the section to be shown on the report is set [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Report/BAO/ReportInstance.php#L194-L200), This section means that the Chart template will be used to display the report on the dashlet, …

CP-67: Fix "Case with Activity Pivot Chart" Report not showing data on civicrm dashboard

---

ang/civicase/activity/calendar/directives/activities-calendar.directive.js
ang/civicase/dashboard/directives/dashboard-tab.directive.html
ang/civicase/dashboard/directives/dashboard-tab.directive.js
ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
api/v3/Activity/Getdayswithactivities.php

When having a lot of Case, the Calendar in Case Dashboard, does not work, because the `Activity.getdayswithactivities` api threw `414 Request: URI Too Large` error. This PR fixes that problem.
**Problem**
Previously, all case IDs which matched the 'Relationship' filter where sent to the Back end using `IN` filter(as shown in Before image). So when the number of cases were too many, this resulted in Get Requested being too large.
**Fixes for Activity.getdayswithactivities api**
So now, instead all the Case Filter Parameters are sent to the `Activity.getdayswithactivities` api using `case_params` parameter. And the backend fetches the Case IDs and then applies the same. This way a huge list of Case Ids does not need to be sent to the backend.
```php
if (!empty($params['case_params'])) { …
```

CPS-68: Activity Calendar Refactor

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/XMLProcessor/Report.php

On the Print Reports page for a case, the values of case custom fields shown are numerical values rather than the actual display values for these fields. This is observed with fields like 
- Field type - radio
- Field type - Select
- Field type - Checkbox
- Field type - Multi-Select
- Field Type - Autocomplete-select
- Field Type - File
The core `CRM_Core_BAO_CustomValueTable::getEntityValues` function was used to fetch the custom values for a case. This function returns the values for the custom fields but sometimes these values are not meaningful to the user viewing the report especially for the fields mentioned in the overview. For example a custom field having a select list options of `Yes => 1, No => 2 `, If the value selected is Yes, what is displayed to the user is `1`. 
The …

BASWSPRT-114:  Show the Display values of Custom fields on Case Activities 'Print Report'

---

api/v3/Activity/Getdayswithactivities.php
package-lock.json

The Calendar stopped working in Manage Case page, also there were console errors, this PR fixes the same.
Dashboard Calendar still works
This is a regression issue caused by https://github.com/compucorp/uk.co.compucorp.civicase/pull/343/commits/c998701e59b7e49285a4fa589d1d5e80f97aff9d#diff-d87117017b42280e07244ce963fbb608R102
In `_join_to_case`, the `$value` can be both Array or String type. When `$params['case_id']` is present, $value` is of Type String. And `case_id`  is sent for the Manage Cases page. Hence there were console errors. This PR fixes the same by removing the parameter type.

CPS-68: change parameter type

---

CRM/Civicase/Hook/PreProcess/AddCaseAdminSettings.php
CRM/Civicase/Service/CaseCategorySetting.php
civicase.php
settings/CiviCase.setting.php
templates/CRM/Civicase/Admin/Form/Settings.tpl

Currently, in the Civicase settings, An administrator can choose to set an alternative URL which is to be used when creating new cases both on the case dashboard and the navigation menu. 
This setting is only available for cases but we need it to be available for other case type categories in the system. This PR makes that possible.
The `CRM_Civicase_Service_CaseCategorySetting` was created to dynamically generate webform settings for all case type categories. 
```php
public function getForWebform() {
$caseTypeCategories = CaseType::buildOptions('case_type_category', 'validate');
$caseCategorySettings = [];
foreach ($caseTypeCategories as $caseCategoryName) {
$caseCategorySettings = array_merge($caseCategorySettings, $this->getCaseWebformSetting($caseCategoryName));
}
return …
```

RSE-752:  Generate Case Webform Setting Fields For Case Type Categories

---

CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
CRM/Civicase/Service/CaseCategorySetting.php
civicase.php

#347 allows the case webform settings to be set per case type category. This PR allows these setting to reflect in the New [Case category] Menu url in the navigation menu. Whatever is set for the webform URL in the case category is the URL that will be used for adding a new case of that category in the navigation menu.
This functionality is not available
Whatever is set for the webform URL in the case category is the URL that will be used for adding a new case of that category in the navigation menu.
```php
if (strpos($item['url'], $addCaseUrl) !== FALSE) {
$caseCategoryName = $this->getCaseCategoryName($item['url']);
$webformUrl = $this->getNewCaseCategoryWebformUrl($caseCategoryName);
if (!empty($webformUrl)) {
$item['url'] = $webformUrl;
}
return;
}
```

RSE-753: Replace Add New [Case category] Menu URL with Webform URL.

---

CRM/Civicase/Helper/NewCaseWebform.php
CRM/Civicase/Hook/Helper/CaseTypeCategory.php
CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
ang/civicase-base.ang.php

In https://github.com/compucorp/uk.co.compucorp.civicase/pull/350, the URL for the Add New [Case category] was replaced with what is set in the webform settings for the Case category. This PR uses the URL to set a variable that is used in the frontend for the Add New [Case category] button on the dashboard.
- Currently the Add New [Case category] button on the dashboard is only set based on Civicase webform settings.
- Currently the Add New [Case category] button on the dashboard is only set based on Case type category for the dashboard being viewed.
The `newCaseWebformUrl` variable set at the BE [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/RSE-44-awards-management/CRM/Civicase/Helper/NewCaseWebform.php#L15) is used to determine the value of the Add new Case Category …

RSE-754: Dynamically Set Variable Used For Add Case Category Button on Dashboard

---

CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
CRM/Civicase/Hook/Tabset/CaseTabModifier.php
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
templates/CRM/Civicase/Page/ContactCaseTab.tpl

As part of this PR, the ability to filter contact case tabs by case type category has been added.
**`civicaseContactCaseTab` now accepts case type category parameter**
`civicaseContactCaseTab` now accepts case type category parameter and uses the same to filter the cases.
In `ContactCaseTab.tpl`, `case-type-category` is set as an attribute.
```javascript
$routeProvider.when('/', {
reloadOnSearch: false,
template: '<civicase-contact-case-tab case-type-category="{/literal}{$case_type_category}{literal}"></civicase-contact-case-tab>'
});
```
Also the container for Contact Case tab is assigned an unique id for every Case type Category. Otherwise angular throws, `App already bootstrapped with this element '<div id="civicaseContactTab" class="ng-scope">'` error.

RSE-757: Filter contact tabs by case category

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/PostProcess/CaseCategoryCustomFieldsSaver.php

When you try to edit the custom field values for a prospect and you save, the prospect values does not get saved. This is a random issue and does not happen all the time. This PR fixes the issue so that the prospect custom fields gets saved whenever their values are changed.
- The issue was initially thought to be a permission related issue but it was not. When you create a new prospect and the prospect is saved, the prospect custom field values are saved [in the cache](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/CustomField.php#L544) so that when saving the values of these custom fields the next time, the fields meta data can easily be retrieved from the cache. 
When you try to edit prospect custom fields it works fine but when the cache is cleared, the custom fields …

RSE-761: Fix Issues With Saving Prospect Custom Field Values Not Saving

---

ang/civicase/case/list/directives/case-list.html

The manage case tab header always shows `Manage Cases` regardless of case type category
- The page title for the Manage Case page is translated based on the word replacement config for the case category by using the `ts` function.

RSE-828: Manage Case Tab header Always Shows Manage Cases Regardless of Case Type category

---

ang/civicase-base.ang.php
ang/civicase-base/constants.js
ang/civicase/case/factories/get-case-query-params.factory.js
ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
ang/civicase/dashboard/directives/dashboard.directive.js
ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
ang/test/global.js
ang/test/mocks/data/constants.data.js

This PR fixes an issue where trying to view an award application by clicking on an application from the dashboard it would not display the details for them. This issue can only be reproduced when trying to view the details as an award manager.
The main issue happens because the award manager does not have permissions to view normal cases, just awards, and the API was being called using `case` as the default category.
To fix this we updated the `expose_settings` function in `ang/civicase-base.ang.php` so it configures the default category depending on the value that is stored in the URL. So for the awards dashboard and manage applications the default category is `awards`.
Some other fixes done:
Also This PR fixed a regression introduced by …

RSE-858: Fix view award application details

---

ang/test/mocks/data/option-value.data.js
ang/test/mocks/services/crm-status.factory.mock.js
api/v3/CustomValue/Gettreevalues.php

Related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/53
**CustomValue.gettreevalues api**
CustomValue.gettreevalues api now supports `custom_group.name` parameter, this is used in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/53/files#diff-c845698ec2554abeeceb8861cbdc5f25R70
**Other Changes**
1. Added `option-value.data.js` mock data file.
2. Updated `crm-status.factory.mock.js` file to resolve with the sent promise.

RSE-341: Updated Mock files related to Unit Tests

---

CRM/Civicase/Hook/alterAPIPermissions/Case.php

The other relationship tab was not showing up for Award manger viewing an award application. Normally the view should have shown `None Found` if there were no relationships.
The other relationship tab was not showing up for Award manger viewing an award application. 
The other relationship tab was is now showing up for Award manger viewing an award application. 
When there are no relationship, it shows `None found`.
The issue was because the Case.getrelations API used to fetch contents for this tab required the permissions: `API permission check failed for Case\/getrelations call; insufficient permission: require ( access my cases and activities or access all cases and activities or basic case information )`.
Since we can't give the Award manager case related permissions, this API is …

RSE-882: Fix Issue With Other Relationships Tab Not Showing Up For awards

---

ang/civicase/case/directives/case-overview.directive.js
ang/civicase/dashboard/directives/dashboard.directive.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/civicase/dashboard/directives/dashboard.directive.spec.js

As part of this PR, the Award Status filter functionality is fixed.
Related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/58
See https://github.com/compucorp/uk.co.compucorp.civiawards/pull/58
In `dashboard.directive.js`, applying all the parameters broadcasted, instead of just `case_type_id`.
In `case-overview.directive.js`, removing the `status_id` parameter, because case overview section should not filter by Award Status and show all statuses.

RSE-363: Filter by Award Status

---

CRM/Civicase/Service/CaseCategorySetting.php
templates/CRM/Civicase/Admin/Form/Settings.tpl

The Civicase settings page  allows an administrator to choose to set an alternative URL which is to be used when creating new case category case both on the case category dashboard and the navigation menu. These form fields descriptions are updated in this PR as they are not translated (i.e  `Case` should be replaced by the appropriate case category name), also the `URL webform ` field description is updated to reflect what can be added for the field.

RSE-747: Update and Translate Case Category Form Settings Description For  CiviCase Settings

---

CRM/Civicase/XMLProcessor/Report.php

This PR allows the activity report for each case type category to be translated based on the translation config for each case type category.
Sample report for prospect category before
Sample report for prospect category after
The Word replacement function is used to add translation strings  just before the output of the print report is rendered so that the template [here](https://github.com/civicrm/civicrm-core/blob/master/templates/CRM/Case/Audit/Report.tpl) will be translated

RSE-830: Fix: Activity Report Should Reflect Correct Case Type Category

---

CRM/Civicase/Setup/UpdateMenuLinks.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0009.php
civicase.php

This PR fixes some issues with the Case Dashboard and Manage Case URL.
(1) The Manage Case URL has the case type category parameter missing from the URL in a newly built site despite adding it in a upgrader earlier. 
(2) The Case Dashboard URL is not consistent with other case type category URL's because it's missing the case category URL parameter
The above stated issues were present.
- The Manage Case URL has the case type category parameter missing from the URL in a newly built site because the new URL with the case type category parameter was only added in an upgrader and not in the extension install. Since upgraders won't run in a freshly installed site, the URL is not updated to the new one. 
The fix for this was to update the Manage case URL in the extension install and also to …

CPS-85: Make Case Category URL's Consistent With Other Case Type Categories

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
CRM/Civicase/Form/Report/ColumnDefinitionTrait.php

The Case activity pivot report currently does not support filtering the reports by case tags or selecting case tags as the columns. This PR makes it possible.
This functionality was not available.

BASWSPRT-99: Case Tag Support For Case Activity Pivot Report

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
CRM/Civicase/Form/Report/ExtendedReport.php
templates/CRM/Report/Form/Tabs/FilterCriteria.tpl
templates/CRM/Report/Form/Tabs/FilterField.tpl
templates/CRM/Report/Form/Tabs/FilterPane.tpl
templates/CRM/Report/Form/Tabs/FiltersCiviCase.tpl

The Case Activity pivot reports takes time to load and the page would somehow hang before the reports become usable. 
The issues described above exist.
The report functionality was optimized in the following areas:
- The `setCaseRolesContactMetaData` function of the `CaseWithActivityPivot` class was optimizes such that it makes a single API call to the Relationship API to fetch available relationship types rather than multiple calls it was making before the change.
- An issue with un-necessary multiple loops in the `setDefaultValues` function of the `ExtendedReport` class was fixed.
- Issue with un-necessary multiple loops when adding Custom fields for entities was also fixed.
- The filter fields could grow really huge and this slows down the report rendering, rather than loading all the …

CATL-1214: Optimize Case Activity Pivot Report

---

ang/civicase-base.ang.php

This fixes an issue in civicase-base.ang.php where an undefined variable `$caseTypes` is referenced, which leads to notices and warnings in some scenarios.
Various case screens (e.g. Dashboard) show messages like `Notice: Undefined variable: caseTypes in set_custom_fields_info_to_js_vars()`, `Warning: array_intersect_key(): Argument #1 is not an array in set_custom_fields_info_to_js_vars()`, etc.
No notices or warnings are shown.
The issue is only present when case type specific custom fields exist.

Fix reference to undefined variable $caseTypes

---

ang/civicase/case/directives/case-overview.directive.js

When the Case overview breakdowns are expanded, and "More Filters" are applied in Awards Dashboard resulting in no Awards. There is a visible blank section, which is fixed in this PR.
When Case Types are updated by filtering, the SimpleBar Scrollbar was not rerendering, and caused the bug. To fix this, `civicase::custom-scrollbar::recalculate` event has been emitted when Case Types are fetched.
```javascript
return crmApi('CaseType', 'get', params)
.then(function (data) {
$scope.caseTypes = data.values;
$scope.caseTypesLength = _.size($scope.caseTypes);
$scope.$emit('civicase::custom-scrollbar::recalculate');
});
```
Unit tests could not be written, because `civicase::custom-scrollbar::recalculate` is being fired multiple times(count is not the same, sometimes its 4 or 8). So there is no …

RSE-953: Recalculate scrollbar when case types are fetched

---

CRM/Civicase/Page/ContactCaseTab.php
ang/civicase-base/factories/parse-url-parameters.factory.js
ang/civicase-base/services/case-type-category-translation.service.js
ang/civicase/case/card/directives/case-card-contact-record.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-list.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-list.directive.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/civicase/shared/directives/on-contact-tab-change.directive.js
ang/test/civicase-base/factories/parse-url-parameters.factory.spec.js
ang/test/civicase-base/services/case-type-category-translation.service.spec.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
ang/test/civicase/shared/directives/on-contact-tab-change.directive.spec.js

This PR adds the translations needed for the case and other case categories tabs in the contact details page.
Using awards as an example. The word "Case" has not been replaced in a few places.
For the most part we simply replaced the "Case" word and printed it using the `ts` service.
Regarding the PHP changes in `CRM/Civicase/Page/ContactCaseTab.php` these are done in order to run the proper word replacements belonging to the case type category.
When changing tabs the translations would be replaced from the global object and when coming back to a particular tab the last translation file would be used. This caused the following issue:
As you can see the "cases" tab gets the translations from the last accessed case category tab. This is because when an angular page is loaded it replaces the …

RSE-751: Contact Cases Tab Word Replacement

---

ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/search/directives/search.directive.spec.js

This PR allows to pass a placeholder value to the case relationship type filter through the URL. The placeholder is `user_contact_id` and this value is replaced for the actual user ID (ex: 2). This is needed in order to create URLs that could be used by any user instead of a particular one.
Accessing `/civicrm/case/a/#/case/list?cf=%7B%22case_type_category%22:%22cases%22,%22case_manager%22:%22user_contact_id%22%7D`
The filter is not understood.
Accessing `/civicrm/case/a/#/case/list?cf=%7B%22case_type_category%22:%22cases%22,%22case_manager%22:%22user_contact_id%22%7D`
The `user_contact_id` placeholder was used because it's the one used by core. We still translate the value to the direct contact ID because the placeholder only works for direct values (`{ case_manager: 'user_contact_id' …

CATL-1221: Accept URL values for the case relationship type filter

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
ang/civicase.ang.php
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js

This PR fixes the following issues with the New case category contact tabs. 
(1) A permission issue that does not allow the Award manager to view the case category contact tab
(2) The Add New Case [Category] button on the case category tab is pointing to the generic add case page rather than the Add New Case [Category] page.
- The issues described above exists.
- The Case contact tab page was added to the list of pages where logic for case category permissions is applied.
- Also Case category contact tabs are only shown when user has the corresponding case category permission.
- The Add New Case [Category] button now leads to the Add New Case [Category] page

RSE-746: Fix Open Issues With New Case Category Contact Tab

---

CRM/Civicase/Hook/PostProcess/CaseCategoryMenuLinksProcessor.php
CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php
CRM/Civicase/Hook/alterAPIPermissions/Case.php
CRM/Civicase/Service/CaseCategoryMenu.php
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
ang/civicase/case/details/summary-tab/case-summary-tasks.html
ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
api/v3/Case/Getfiles.php

This PR fixes issues found when testing the Case Category Menu/Tabs Issues functionality.
- An issue with not being able to upload files for a case category on manage case category.
- Issue with disabled case tabs still active
- Menu items not getting deleted after disabling the case category option value.
- Word replacements on Manage Cases task block
- GO TO [Case Category] button on case category contact tab was giving an access denied error.
- These issues exist
These Issues were fixed.
- The issue with not being able to upload the files for a case category was due to a call to Case.getsingle API. This call will invoke the `civicase_civicrm_selectWhereClause` which is already overriden [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/civicase.php#L700-L704) to …

RSE-745:  Fix Case Category Menu/Tabs Issues

---

CRM/Civicase/Hook/PostProcess/CaseCategoryMenuLinksProcessor.php
CRM/Civicase/Service/CaseCategoryMenu.php

This PR fixes fixes an issue whereby when a case category is added, the menu for the option value is not reflected on the menu icon for the Navigation menu generated.
- This issue exist.
Issue is fixed.
The `toggleStatus` function of the `CRM_Civicase_Service_CaseCategoryMenu` was changed to `updateItems` to accommodate for properties of the case category menu that needs to be updated.

CPS-94: Fix [Case Type Category] Adding An icon to a Case Type Category Not displaying Icon On Main Menu

---

ang/civicase/case/factories/get-case-query-params.factory.js
ang/test/civicase/case/factories/get-case-query-params.factory.spec.js

Other Cases section inside Case Summary, was showing cases from other Case Type Categories, this PR fixes the same.
In `get-case-query-params.factory.js` , when `relatedCasesByContact` and `linkedCases` are loaded, case type category filter is not sent here. Fix is the following
```javascript
'api.Case.getcaselist.relatedCasesByContact': {
'case_type_id.case_type_category': filters.caseTypeCategory, // added this
contact_id: { IN: '$value.contact_id' },
id: { '!=': '$value.id' },
is_deleted: 0,
return: caseListReturnParams
},
// Linked cases
'api.Case.getcaselist.linkedCases': {
'case_type_id.case_type_category': filters.caseTypeCategory, // added this
id: { IN: '$value.related_case_ids' },
is_deleted: 0,
return: caseListReturnParams
},
```

CPS-102: Filter other cases by category

---

CRM/Civicase/Hook/PermissionCheck/CaseCategory.php

When a user with all permissions associated to new case type category tries to edit an activity for that case category, an error is thrown.
Issue exist.
The activity add/edit page is added to the list of pages where we check for case category permission equivalent.

CPS-101: Fix Unable to Edit an Activity For Newly Created Case Type Category

---

ang/civicase/activity/panel/directives/activity-panel.directive.js

This PR is a continuation of https://github.com/compucorp/uk.co.compucorp.civicase/pull/375.
When no Activity Category is selected for an Activity Status, now it is considered that all categories are selected. 
Added a check to see if the Activity Status has no category selected.
```javascript
if (ifStatusIsInSameCategory || ifStatusIsInNoneCategory || ifStatusIsForAllCategories) {
$scope.allowedActivityStatuses[activityStatusID] = activityStatus;
}
```

CPS-106: Fix undefined activity status grouping

---

CRM/Civicase/Hook/alterAPIPermissions/Case.php

A user with relevant permissions related to a created case type category cannot edit the case category subject on manage case type category.
- The issue above exists.
- The case update API is added to the list of API's that allows the equivalent case type category permission to be used.

CPS-109: Fix [Case Type Category / Case] User with relevant permissions is unable to edit case subject

---

CRM/Civicase/Hook/PermissionCheck/CaseCategory.php

There is a permission error when accessing the case category contact tabs even if user has sufficient permissions
- Issue exists
- Issue is fixed
There is a bug in the permission logic caused by using the assignment operator instead of the comparison operator.

CPS-113: Fix Permission Issues With Case Category Contact tabs

---

ang/civicase/case/directives/case-overview.directive.html
ang/civicase/case/directives/case-overview.directive.js
ang/civicase/dashboard/directives/dashboard-tab.directive.html
ang/civicase/dashboard/directives/dashboard.directive.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/civicase/dashboard/directives/dashboard.directive.spec.js

This PR fixed the following things,
1. When clicking on any 'Case Status' or the 'Case Status Count' in the Case Overview of Dashboard section, browser redirected to Manage Cases page, but the "Relationship" filter was not sent to the Manage Cases page. 
2. When clicking on any 'Case Status' or the 'Case Status Count' in the Case Overview of Dashboard section the Case Type Category filter was not sent to the Manage Cases page, which resulted in showing cases from all Case Categories. 
1. As the Relationship Filter is available on the `civicaseDashboard` directive, and not in `civicaseCaseOverview`, the `$scope.caseListLink` function has been moved to `civicaseDashboard`, and then the same is passed down to `civicaseCaseOverview` using attributes.
2. In `civicaseDashboard`, there was an …

BASWSPRT-98: Apply Relationship Filter to Manage Cases link from Dashboard

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab-placeholder.html
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js

This PR displays an error message when adding a client as another role type for the case. Previously this would fail silently.
The request fails and this is not shown to the user.
The `assignRole` function was refactored and splitted into 3 different functions. The reason for this is that the same function was used to do at least 4 different things:
* Assign a case clients
* Assign a case role
* Replace a case client
* Replace a case role
This lead to a lot of conditions inside of the `assignRole` function which made it difficult to follow.
The new functions are `assignClient`, `assignRole`, `replaceRoleOrClient`. The code for displaying the contact selection dialog was moved to `promptForContact` and is used by all of these functions.
To display the error message and blocking the …

CATL-1132: Block clients from having other roles

---

ang/civicase/activity/directives/add-activity-menu.directive.js
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html

In Contact Case tab, the Add Activities button inside "Next Activity" block does not show list of available Activity Types. This PR fixes this issue.
This PR also fixes CPS-116.
This is a regression issue introduced by https://github.com/compucorp/uk.co.compucorp.civicase/commit/6eff6b413cbf4f2a59838f116dd573eedda261ea
Where the following code was introduced
```
$scope.$watch('case.allActivities', function () {
$scope.availableActivityTypes = getAvailableActivityTypes(
$scope.case.activity_count,  $scope.case.definition);
});
```
But in some scenarios `$scope.case.definition` is undefined, when the case has been fetched, but the definition is not set yet in https://github.com/compucorp/uk.co.compucorp.civicase/blob/6cfbb9772787d73a7204c602090919e141b4c22a/ang/civicase/case/details/directiv …

CPS-117: Fix Activty Types not shown on Contact Case tab

---

ang/civicase/case/factories/format-case.factory.js

The Case List on Manage Cases page, the My Role column does not show anything, this PR fixes the same.
The `Case.getcaselist` API already returns `myRole`, 
But this was getting reset in `format-case.factory.js`, 
```
item.myRole = [];
...
if (contact.contact_id === CRM.config.user_contact_id) {	
item.myRole.push(contact.role);	
}
```
Now the logic could have been fixed, but as the API already returns the My Role, the above logic is not necessary anymore. So it has been removed.

CPS-122: Fix my role not showing

---

ang/civicase/activity/feed/directives/activity-feed.directive.js
ang/test/civicase/activity/feed/directives/activity-feed.directive.spec.js

This PR fixes an issue where the case relationship filter does not update the activity feed properly when changing its value.
This bug has existed for a while. The issue happens because the activity feed accepts the `params` binding and it uses this to populate the activity filter values, but it only uses it on init. If the `params` value changes the activity feed does not take it into account:
```js
(function init () {
if ($scope.params && $scope.params.filters) {
angular.extend($scope.filters, $scope.params.filters); // <--- $scope.params.filters is a binding
}
// ...
}());
```
To fix this we extend the `$scope.filters` object again when the `params.filters` binding changes.

CPS-105: Fix dashboard activity feed

---

CRM/Civicase/Hook/PermissionCheck/CaseCategory.php

Currently a user with enough permissions is unable to use the download all action for files on the files tab of the manage case category page. When the user tries to, an access denied error page is gotten.
- The issue above exists.
- The permissions required for the Download all files page is `access all cases and activities` and `access my cases and activities`, the fix is to add this page to the case category permission logic so that the equivalent case type category permission can be used when acessing this page.

CPS-115: Fix [Case Type Category / Attachments] Unable to download all attachments from files tab with enough permissions.

---

ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/card/directives/activity-card.directive.js
ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
ang/test/civicase/case/search/directives/search.directive.spec.js

This PR fixes the links to the case details. There are two fixes involved:
* Links to case details from activity cards did not have the `case_type_category` parameter. This made permission checking impossible.
* The list of case types were not being properly filtered according to the category the user was currently in.
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
<th>Notes</th>
</tr>
<tr>
<th>Contact Case Tab</th>
<td><img src="https://user-images.githubusercontent.com/1642119/76762529-d620fd00-6767-11ea-9b69-3191dc9a9227.gif" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/76712639-0e392900-66f1-11ea-85ee-c7d218880716.gif" /></td>
<td>The case type filter showed all case types.</td>
</tr>
<tr>
<th>Activity Card</th>
<td><img …

CPS-114: Fix case details link

---

ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html

This PR fixes the link to create a new case from the contact's case tab. The issues fixed were:
* The case type category was not being passed to the case form so the right list of case types is not displayed. This also causes permission issues.
* The contact was not being preselected.
The issue happens because we were not passing the case type category name to the form. We were also not passing the contact id. To fix this issue we pass these parameter which are the same ones passed to the "Add Case" button on the top:
```html
<a ng-if="checkPerm('add cases')"
class="civicase__activity-card--big--empty-button btn"
ng-href="{{ 'civicrm/case/add' | civicaseCrmUrl:{civicase_cid: contactId, reset: 1, action: 'add', context: 'standalone', case_type_category: caseTypeCategoryName } }}" …
```

CPS-128: Fix "add new case" link for contact case tab

---

ang/civicase/shared/directives/dropdown.directive.js
ang/test/civicase/shared/directives/dropdown.directive.spec.js

This PR fixes the case details' "Add New" Dropdown menu breaks on Firefox since it disappears when trying to access child menu items.
Fixes #152 
The issue happens because the `civicase-dropdown` directive used `mouseover` and `mouseout` events, and these trigger multiple times while the mouse moves which makes Firefox hide the menu because it's the last event triggered out of those two.
To avoid this issue we use `mouseenter` and `mouseleave` events which only trigger once.

CPS-78: Fix dropdown menu on Firefox

---

ang/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.js
ang/civicase/activity/feed/directives/activity-feed.directive.js
ang/civicase/case/actions/services/email-managers-case-action.service.js
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/services/cases-utils.service.js
ang/test/civicase/activity/activity-forms/services/draft-email-or-pdf-activity-form.service.spec.js
ang/test/civicase/case/actions/services/email-managers-case-action.service.spec.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/case/services/cases-utils.service.spec.js

This PR adds case clients as default recipients to send email popup on civicase detail pane. And add a proper error validation message for email case manager popup when no case manager are selected.
* In `email-managers-case-action.service.js` if no case managers are available then there are no error validation messages for this use case. So we have added a proper error validation message
* In `case-details.directive.js` set `cid` to contacts id which are the case clients for the particular case. 
This PR also adds the same solution to the activity pdf letter draft activity popup on the activity panel.
While fetching all the activities we now need the related case clients array too. So, the same is added in return params in `loadactivities` function in `activity-feed` directive.
Since …

CATL-1113: Set case clients as default recipients to send email popup

---

ang/civicase-base/providers/activity-actions.provider.js

This PR fixes the labels for the activity actions since they were not using the proper word replacements.
The `ts` function was used on the `activity-actions.provider.js` file.

RSE-1000: Fix actions word replacement

---

CRM/Civicase/Helper/NewCaseWebform.php
ang/civicase-base.ang.php
ang/civicase-base/constants.js
ang/civicase-base/services/case-category-webform-settings.service.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
ang/civicase/dashboard/directives/dashboard.directive.js
ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
ang/test/mocks/data/constants.data.js

Previously the Add <Case Category Name>, link in Contact Case tabs always redirected to "Case" webform. This PR fixes the same.
1. `newCaseWebformClient` and `newCaseWebformUrl` set from Backend, always had Cases values inside the Contact Case Category Tabs. As angular loads only once for these tabs, it was always Cases. So to fix these, now all the webform settings are exposed to FE in `NewCaseWebform.php`
2. Removed `newCaseWebformClient` and `newCaseWebformUrl` angular constants. And added `case-category-webform-settings.service.js`, which exposes `getSettingsFor` function to get settings for a specific case category.

RSE-1028: Fix Add Case link

---

ang/civicase/activity/actions/services/move-copy-activity-action.service.js

The Move/Copy Activity Popup had translation issues in Case Type categories, this PR fixes the same.
Using `ts` angular service in `move-copy-activity-action.service.js`.

RSE-1031: Fix translation in Move/Copy Activity Popup

---

ang/civicase-base.ang.php
ang/civicase-base/providers/case-type.provider.js
ang/civicase/case/directives/case-overview.directive.js
ang/civicase/case/factories/format-case.factory.js
ang/test/civicase-base/services/case-type.service.spec.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/mocks/data/cases-types.data.js

This PR allows filters to request cases belonging to disabled case types and to show disabled case types in the overview section.
**Note:** this PR is linked to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/75
For before and after screens please refer to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/75
In `civicase-base.ang.php` we made so that all case types are appended to the global JS variable regardless of its active status. We also added the `is_active` parameter to determine if a particular case type should be shown or not.
The `CaseType` provider now can return all case types (including disabled ones) when the `{ includeInactive: true }` property is passed, otherwise it will only return active ones.
The `case-overview.directive.js` directive will …

RSE-1033: Allow filtering by disabled case types

---

api/v3/Case/Getstats.php

This PR fixes the count issue on the overview tab for civiawards extension when the more filters search box filters yields no results.
When awards filter (`More filters`) filter criterion is changed in a way which results in no awards, the count on the overview section for the total application doesn't get updated to 0. See before screen grab. However, it was showing count of all the awards count. 
The reason behind this issue is that the API for getstats for the Cases was not returning the correct value when `case_type_id` passed is set to empty or null (which mean selecting no case types), the PHP code is considering it as no param (in the logic) at all and returning all the cases expecting this as an empty param.
So, to fix this we need to handle this corner case and pass different …

RSE-944: Improve Get Stats API - handle no case_type_id corner case

---

tests/backstop_data/Readme.md
tests/backstop_data/engine_scripts/puppet/contacts/contact-dashboard.js

This PR fixes some part of js code related to capture contact activity dashboard and related readme content
For some reason full name (with first and last name) doesn't return correct result for the contact search form
So, we have changed the logic to only search for the first name. So, inspite of `Betty Adams` now it only search for `Betty` and same has been updated in the readme file.

CPS-136: [Backstop JS]Tweak contacts dashboard js and associated readme content

---

tests/backstop_data/Readme.md
tests/backstop_data/engine_scripts/puppet/mouse-events-helper.js
tests/backstop_data/engine_scripts/puppet/utility.js
tests/backstop_data/scenarios/dashboard.json

This PR adds screens for the dashboard sections
* Add screen while opening the filter dropdown
* Add screen for opening new case modal
* Moved all empty state screens in a new group `Empty screens` as this will be handled separately
* Added a new utility function `waitForUIModalLoad` and provided this as a configuration from the scenario building list in `clickSelectorAction` function
* Added an extra click selector to capture civicase filter dropdown with it.

CPS-140: [Backstop JS] - Dashboard section - Add logic for opening filter dropdown and add open case modal screen

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
ang/civicase.ang.php

When a user clicks on the Case category dashboard link on the breadcrumbs, either for Awards or any other case category, it takes the user to the default Case dashboard. The user should be taken to the dashboard for that case category and not the case dashboard.
The issue described above exists
Issue is fixed.
The function for updating the Case category breadcrumbs was moved to a central function and used from there for the New case page and the angular related case category pages.

RSE-957: Fix Clicking on "Case Category Dashboard" Breadcrumb Takes User to Cases Dashboard

---

ang/civicase/activity/actions/services/tags-activity-action.html

When "Tag - add to activities" or " Tag - remove from activities" bulk actions were performed in Activity Feed, the tags were not visible and there were console errors. This PR fixes the same.
This is a regression issue, as part of https://github.com/compucorp/uk.co.compucorp.civicase/pull/405, a new directive `civicase-tags-selector` was created, but the markup was wrong in `tags-activity-action.html`.
The attribute name is changed to `model` from `model-object`.

RSE-659: Fix Bulk Action Error with Tags

---

ang/civicase.ang.php
ang/civicase/case/actions/directives/case-actions.directive.js
ang/civicase/case/actions/services/webforms-case-action.service.js
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/details/directives/case-details-header.html
ang/civicase/case/list/directives/case-list-table-first-column-header.html
ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js

There is *Webforms* menu item available for cases. According to new requirements we need to keep it on case details view only:
1. Remove the webforms link from contact card actions menu.
2. Remove the webforms link from manage cases > bulk actions menu.
3. Keep the webforms link on manage cases > case details > actions menu.
Contact details - Cases tab before:
Contact details - Cases tab after:
Manage cases - bulk actions before:
Manage cases - bulk actions after:
Case details before and after (no changes):
The *Webforms* menu item is added in the `add_webforms_case_action()` back-end function, but there are no reliable ways to tweak this function to add this item for case details only.
So it was decided to go ahead with front-end approach:
1. The `isActionAllowed()` method was added for …

CPS-86: Remove Webforms case action

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html

There was an issue with case subject saving: when user clicks it and textarea appears allowing user to edit it. But when user clicks Save button - nothing happend.
This PR fixes it and now subject is saved.
There was js error in the console: Uncaught TypeError: Cannot read property 'id' of undefined (jquery.crmEditable.js).
After some investigation it turned out that editor requires a parent container to have `.crm-entity` class and 2 attributes (data-entity and data-id) in order to work as expected.
So in this PR we've added everything necessary to the parent container.

CPS-81: Fix case subject saving

---

CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForChangeCase.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForChangeCase.php
ang/civicase/case/actions/services/email-managers-case-action.service.js

There were some screens on Awards where the case category translation were not working as expected. Also an issue with Notification when trying to trigger “Email application manager“ action from the actions menu if there’s no application manager assigned. This PR fixes that.
The following screens were not translated as expected:
- Updating Application Status Screen
- Link applications screen
- Milestone activity edit screen.
- The screens above were properly translated. Note that the fix is a generic fix that works for all case type categories including Prospect, Awards and other categories created

RSE-714: Fix Award/Case Category Page Translation Issues

---

CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
CRM/Civicase/Hook/ValidateForm/SaveCaseTypeCategory.php
civicase.php

Currently, when user saves case type category special characters in it's name would be saved as well. We need to prevent the name to have special characters such as quotes, ampersand.
So this PR adds validation for case type category.
Any characters are allowed for category name (label).
Following characters are allowed for category name (label): letters (a-z), numbers, space and hyphen. Respective error is displayed in case if validation failed:
1. To validate the case type category form (which is the option group form) we created `CRM_Civicase_Hook_ValidateForm_SaveCaseTypeCategory` class, which is then used in `civicase_civicrm_validateForm()` hook.
2. Also as part of this PR wrong array key names where fixed in the sibling `CRM_Civicase_Hook_ValidateForm_SaveActivityDraft` class.

CPS-124: Remove special characters from case type category name

---

ang/civicase/activity/activity-forms/activity-forms.config.js
ang/civicase/activity/activity-forms/services/add-activity-form.service.js
ang/civicase/activity/activity-forms/services/add-custom-path-activity-form.service.js
ang/civicase/activity/activity-forms/services/update-activity-form.service.js
ang/civicase/activity/directives/add-activity-menu.directive.js
ang/civicase/activity/factories/view-in-popup.factory.js
ang/test/civicase/activity/activity-forms/activity-forms.config.spec.js
ang/test/civicase/activity/activity-forms/services/add-activity-form.service.spec.js
ang/test/civicase/activity/activity-forms/services/add-custom-path-activity-form.service.spec.js
ang/test/civicase/activity/activity-forms/services/update-activity-form.service.spec.js

This PR implements the form service introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/329 and uses it when creating new activities. This allows other extensions to define the form to display when creating new activities.
**Note:** this PR is linked to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/80
Please refer to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/80 for before and after screenshots
* Divided the logic that was in `add-activity-menu.directive.js`'s `newActivityUrl` method into two new form services: `AddCustomPathActivityForm` and `AddActivityForm`.
* `AddCustomPathActivityForm` is used for activities that have a custom path to save the activity such as `Email` and `Print PDF Letter`.
* `AddActivityForm` is used for all …

RSE-956: Use form service when adding new activities

---

CRM/Civicase/Page/ContactCaseTab.php
ang/civicase-base/services/case-actions.service.js
ang/civicase/case/actions/directives/case-actions.directive.js
ang/test/civicase-base/services/case-actions.service.spec.js
ang/test/civicase/case/actions/directives/case-actions.directive.spec.js

This PR fixes the following issues related to case actions on the contact's case tab:
* It uses the right translation for each action depending on the case category the tab belongs to (ie: Print Application instead of Print Case)
* It uses the right case actions as provided by other extensions. Previously we were adding repeated actions for the same extension
* Notice the menu on the right: there are repeated actions, and the "Case" word is not translated
It also works when switching tabs:
The issue is that the case actions are defined in the `civicase.ang.php` file, and we use `Civi\Angular\Manager` to get the translations. It seems this class only gets the translations from JS files when running `$angularManager->getTranslatedStrings('civicase');`.
We took advantage of this same class, …

RSE-1050: Fix Contact Tab Case Actions

---

ang/civicase-base/providers/case-type.provider.js
ang/civicase/activity/directives/add-activity-menu.directive.js
ang/test/civicase-base/services/case-type.service.spec.js

This PR fixes an issue where award managers could not create review activities from the award tab on the contact details due to lack of permissions.
The issue happened because we were not passing the case category parameter to the form.
To pass the parameter we did the following changes:
* Added a `getById` method to the case type service so it's easier to get case types.
* Modified `add-activity-menu.directive.js` so we pass the `case_type_category` parameter to the   award form.

RSE-1053: Fix create activity

---

ang/civicase/case/services/add-case.service.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
ang/test/civicase/case/services/add-case.service.spec.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js

The Add Case button in Contact Tab((when there are no existing cases) did not redirect to Webforms even when webforms are configured for the case type category. This PR fixes this bug.
**`AddCase` - A new Service**
A new service `AddCase` has been created, to reuse the common logic of creating a new case.
It has 2 functions,
1. `clickHandler` - It accepts 3 parameters and it abstracts the logic to either redirect to webform or open the new case popup.
* caseTypeCategory - Case Category Name
* contactId - contact ID (optional)
* callback - call back function to be called after a case is created (optional)
2. `isVisible` - Checks the permission and returns true if the logged in user has permission to Add New Case.

CPS-77: Fix for Add Case button in Contact Tab not redirecting to Webforms

---

CRM/Civicase/Hook/alterMailParams/SubjectCaseTypeCategoryProcessor.php
civicase.php

There was an issue with emails being sent via a case from cases of some case type category: subject contains the word 'case' instead of case type category name.
Automatic word replacement was not working for subject in emails (because civicrm does not run translation function for that). So to workaround it we added `civicase_civicrm_alterMailParams()` hook to alter email subject manually, all the job is done by new `CRM_Civicase_Hook_alterMailParams_SubjectCaseTypeCategoryProcessor()` class.
To fetch the case type category name we need case id which is not present in `$params` of the hook function, luckily `$_GET['caseid']` is available, so we used it instead.

CPS-127: Replace 'case' with respective category in email subject

---

api/v3/Activity/Copybyquery.php
api/v3/Activity/Movebyquery.php

The Move To Case action for moving an activity to a case was not working. This PR fixes the issue.
- We were trying to move an activity to a case via the Activity.create API. However this does not work because of a couple of factors. One of such is that the API is explicitly hardcoded to copy to case and the mode parameter is not exposed as an option to be passed via the API, see [here](https://github.com/civicrm/civicrm-core/blob/master/api/v3/Activity.php#L120-L125).
- When checking Core,  it turns out that the CRM_Activity_Page_AJAX::_convertToCaseActivity is used to move/copy activity to case. The same [function](https://github.com/civicrm/civicrm-core/blob/master/api/v3/Activity.php#L125) is used by the API but the API does not allow to set the mode. This function is now used in the …

CATL-1313: Modify CopyByQuery and MoveByQuery Case Activity APIs

---

ang/civicase/crm-dashboard/directives/crm-dashboard-tabset-affix.directive.js

This PR fixes the dashboard tab navigation elements when they need to be affixed and the Admin Menu element is visible. Previously the affixing was not taking into consideration this element.
We updated the code so it includes the Admin Menu height to the position `top` of the CRM Menu and to the `padding-top` of the dashboard container. This extra spacing is only applied when the Admin Menu is visible.

CATL-1321: Fix dashboard tab affix when Admin Menu is visible

---

ang/civicase/shared/directives/tags-container.directive.js
ang/test/civicase/shared/directives/tags-container.directive.spec.js

This PR fixes an issue with tags displayed on case details. When switching from a case with tags to another case without them the tags from the previous case would be displayed in the current one.
When the tags container directive was first introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/173 we used a condition to update the values of the tags from an object input to an array of objects. Since this was added conditionally when we switched from a case with tags to another without the tags of the previous one would still persist. To fix this we removed the condition and set the tags array to empty if no tags were provided to the directive.
We also removed `Object.values` in favour of `_.values` since the former is [not supported by Internet …

RSE-896: Fix Case tags

---

ang/civicase/activity/actions/services/move-copy-activity-action.service.js
ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js

This PR updates the endpoints we use for Move and Copy activity. Previously we were creating new activities, but now we use the new `movebyquery` and `copybyquery` endpoints.
For more information about why this change is required please refer to: https://github.com/compucorp/uk.co.compucorp.civicase/pull/437
Moving activities does not work
We updated the `move-copy-activity-action.service.js` activity action service. We removed the `prepareAPICallsForSingleActivity` function since the new endpoints support a single or multiple activities so long as they are sent through the `id` parameter.
We also updated the previous `prepareAPICallsForMultipleActivities` so it only sends the subject parameter for multiple activities.
Also fixed some tests related to displaying the activity type title on …

CATL-1314: Update Move/Copy activity endpoints

---

ang/civicase/activity/factories/get-activity-feed-url.factory.js
ang/test/civicase/activity/factories/get-activity-feed-url.factory.spec.js

Clicking on Case tasks from Case Details does not open up filtered tasks. This PR fixes the problem.
This is a regression issue, 
In https://github.com/compucorp/uk.co.compucorp.civicase/pull/281/files#diff-c0737ba8aafd36cf7a4e7a001d7f13d7R12, we implemented a new solution to show tabs. So the URL to show the Activity tabs needs to be changed to `Activities`.

CPS-72: Fix Activity Feed link

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html
api/v3/Case/Getrelations.php

The "Description" column has been added to the Other Relationships tabs in Case Details section.
1. `Case.getrelations` has been modified to also return the `description` field.
2. Markup to show `Description` field is added to `case-details-people-tab.directive.html`.

CPS-129: Add Relationship Description to Other Relationships tab

---

ang/civicase/case/search/directives/search.directive.js
ang/civicase/dashboard/directives/dashboard.directive.js

There is a relation filter on the cases Dashboard page and we have same filter when we go to the case type category page. And there was a mess with letters upper/lower case - first letter of a category name should be uppercased for all options in that filters, but one option still had lower case.
There is `CRM_Civicase_Helper_CaseCategory::getWordReplacements()` which provides word replacing for the following forms of the word: `Case`, `Cases`, `case`, `cases`. In order to have first character uppercased we need to use `Case`, but `case` was used for the filter option. Now we are using correct form of the word and issue is fixed.

RSE-1005: Uppercase the case type category name in the filter

---

ang/civicase/case/search/directives/search.directive.js

There was an issue with filters on **Manage Cases** page (`/civicrm/case/a/?case_type_category=cases`) - when filtering case by id - it was displayed in results even if it was deleted. It should not be displayed int this case unless **Deleted Cases** checkbox is ticked.
The search filters values are used to send an api request to get the data here. But if checkbox (boolean field) had no value it was not included into filters list - as a result both deleted / not deleted entities where displayed.
Now we force `false` value for empty `is_deleted` field and search works as expected.

CATL-1171: Exclude deleted cases from search

---

CRM/Civicase/Event/Listener/ActivityFilter.php
CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php
CRM/Civicase/Factory/CaseTypeCategoryEventHandler.php
CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
api/v3/Activity/Getmonthswithactivities.php
civicase.php

We had a bug with case type categories - disabling a case type category doesn’t hide respective item from main menu. Actually it's working fine when user clicks _Edit_ and unticks _Enabled_ checkbox, but not working when user clicks _Disable_ link in the categories list:
Enable / Disable was working fine when user submits a form, because we have a post processor for this form. But when user clicks the link normal api request is called, which has no processing.
So to fix it:
1. The `CRM_Civicase_Event_Listener_CaseTypeCategoryIsActiveToggler` listener was added to listen for api call responses.
1. To avoid duplication the `CRM_Civicase_Service_CaseTypeCategoryEventHandler` class was created which handles create/update/delete processing for case type category option values. …

RSE-1013: Fix 'Disable' link of case type category

---

CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0011.php

The search for file activity of the case was not working - results where always empty.
How to reproduce:
1. Create a case
2. Upload a file
3. Go to activities tab
4. Select “File“ from “All activity categories“ filter.
5. Results are empty, but file upload activity is expected.
The `File Upload` activity type was used here which was missing grouping property. In this PR we set this property to `file` in order to make the search work.
Respective upgrader is added - `CRM_Civicase_Upgrader_Steps_Step0011`.
Also as part of this PR some comments where fixed to pass phpcs checks.

RSE-999: Fix file activity search

---

CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php

When the Print/Merge document form is clicked from the contact actions menu and saved as draft, we need to set the activity created to be with the contact that is being viewed and make the activity to be unassigned. This behaviour is different from when the form is used on Manage cases for instance where the activity is attached to the case and the activity is not with any contact.
The scenario describes in overview exists.
When the print merge form on the contact actions menu is used and saved as draft, the activity created is set to be with the viewed contact and the assigned to set as blank.
The current behaviour of the form on manage cases and elsewhere when used within a case context is maintained. The changes only affect when these form is used via the contact actions outside a case …

CPS-33: Set Activity Contact With For Print/Merge Document On Contact actions

---

CRM/Civicase/XMLProcessor/Report.php

When viewing the activity report, each case role that has a user assigned is shown in duplicates. An empty case role field is shown in addition to the case role field.
This PR fixes the issue.
The `CRM_Civicase_XMLProcessor_Report` is based off the core `CRM_Case_XMLProcessor_Report` class. This issue existed in the core class but was fixed [here](https://github.com/civicrm/civicrm-core/commit/5655a8d4acd2af4d6452148c781a55a5836df5ed). The fix is to apply this core fix to the clase in civicase.
At some point we might need to sync all the changes in the base class to this class or probably find a way to use the core class without copying the code. This is out of scope for this task however.

RSE-978: Fix Duplicate Case Role Field in Activity Report

---

ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card.directive.js
ang/test/civicase/activity/card/directives/activity-card.directive.spec.js

This PR hides the "To:" field from the activity card for "Print/Merge Document" (PDF Letter) activity types.
Since the logic to display the "To" field became more complex we moved it from the view to the controller. The view only checks whether `isToFieldVisible` is true or false. When the activity card is initialized we set the visibility value using the newly introduced `getToFieldVisibilityStatus` function:
```js
function getToFieldVisibilityStatus () {
var isNotPrintPdfActivity = $scope.activity && $scope.activity.type !== 'Print/Merge Document';
var isCommunicationActivity = (($scope.activity && $scope.activity.category) || [])
.indexOf('communication') >= 0;
return isCommunicationActivity && isNotPrintPdfActivity;
}
```

CPS-146: Remove "To:" field from PDF activity

---

ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js

This PR fixes an issue where saving a draft email and then sending the actual email does not save an email activity for the case.
First, we depended on [this core PR](https://github.com/civicrm/civicrm-core/pull/16105) to be merged because it fixes an issue where the email activity didn't support cases.
After that we identified that we have been passing the case ID parameter as `caseId` instead of `caseid` which is how both [the form used for draft emails](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/Form/Task/Email.php#L35) and the [email form](https://github.com/civicrm/civicrm-core/blob/master/CRM/Case/Form/Activity.php#L56) expect the parameter to be written.
The remaining question is: how come creating and updating the draft worked if we were sending `caseId`? …

CPS-134: Fix caseid parameter for saving draft and sending emails

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/test/civicase-base/services/case-actions.service.spec.js
ang/test/civicase/case/actions/services/webforms-case-action.service.spec.js
ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
ang/test/mocks/data/case-actions.data.js

When a "Relationship A to B" is added inside a Case Type, the Case Details People Tab did not work, it is fixed now.
Previously only the `name_b_a` was used to fetch the relationship in `case-details-people-tab.directive.js `. But if "Relationship A to B" was used, then this logic failed and produced error. So changed the logic
```javascript
var relType = _.find(relTypes, function (relation) {
return relation.name_a_b === role.name || relation.name_b_a === role.name;
});
```

CPS-180: Fix broken People Tab when certain relationships are present

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/PermissionCheck/ActivityPageView.php
CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
ang/civicase-base.ang.php
ang/civicase-base/providers/case-type-category.provider.js
ang/civicase/activity/actions/services/move-copy-activity-action.html
ang/civicase/activity/actions/services/move-copy-activity-action.service.js
ang/test/civicase-base/providers/case-type-category.provider.spec.js
ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
civicase.php
gulpfile.js
package-lock.json
package.json
tests/backstop_data/gulp-tasks/backstopjs.js
tests/backstop_data/gulpfile.js
tests/backstop_data/package-lock.json
tests/backstop_data/package.json

When a user only has permission to a single case type category, the Move/Copy to case popup does not show any cases, when typed.
1. The case type categories for which user has "basic case information" permission, is exposed to frontend using `caseTypeCategoriesWhereUserCanAccessBasicCaseInformation`. Also the same values are exposed within angular context using `case-type-category.provider`.
2. Changed the parameters in `move-copy-activity-action.html`. Previously as `case_type_id.case_type_category` parameter was not used, the api was not returning any values because of permission. 
So now `case_type_id.case_type_category` parameter is set to the first case type category for which the user has "basic case information" permission, this bypasses the permission issue.
Also …

RSE-1090: Fix Move/Copy Activity

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/details/summary-tab/case-details-summary-tab.html

This PR fixes the translation for the case details field's placeholder.
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<th>Contact's Page</th>
<td><img src="https://user-images.githubusercontent.com/1642119/80918738-7fca4680-8d34-11ea-89af-4e9f5478c948.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/80918733-7d67ec80-8d34-11ea-8ce0-8a0369f8223f.png" /></td>
</tr>
<tr>
<th>Case Details</th>
<td><img src="https://user-images.githubusercontent.com/1642119/80918739-8062dd00-8d34-11ea-8f22-dda39697735f.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/80918735-7e991980-8d34-11ea-8d47-90375b3545c9.png" /></td>
</tr>
</table>
When we first introduced the editable case details field …

RSE-1082: Fix case details placeholder translation

---

CRM/Civicase/Form/CaseCategoryTypeCustomField.php
CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php

Currently Custom fields for Case Types are not supported in Civicrm core but we need this support for Award case types and possibly for any other case types in the future.
This PR adds the functionality and required classes to make this functionality available for custom field support for case types of case categories.
- This functionality is not available.
- A `CRM_Civicase_Form_CaseCategoryTypeCustomField` class is added that can be extended by other case categories and allows values for custom fields for case type categories to be created/edited. This form can be extended by Awards category or any other category that intends to have a form for processing values for custom fields for case types.
- A new class `CRM_Civicase_Service_CaseCategoryCaseTypeCustomFieldExtends` was added that …

RSE-647: Case Category Type Custom Fields

---

ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/civicase/contact/directives/contact-icon.directive.html
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js

As part of this PR the following fixes has been made
1. Now as part of "Other Case" block in Contact Case Tab, "all Cases where the Contact has any role other than case client" would be shown.
2. Contact Icon for Organisations did not work, it is fixed now.
1
2
1
2
1. In `contact-case-tab.directive.js ` the logic is changed.
```javascript
contact_id: { '!=': $scope.contactId },
contact_involved: $scope.contactId
```
2. The Contact Type returned by BE has changed from "Organisation" to "Organization". So changed the logic
```html
<i class="material-icons" ng-switch-when="Organisation">domain</i>
```

CPS-6: Change "Other Case" logic in Contact Case Tab

---

CRM/Civicase/Helper/CaseUrl.php
CRM/Civicase/Hook/PageRun/ViewCasePageRedirect.php
CRM/Civicase/Hook/PostProcess/RedirectToCaseDetails.php
ang/civicase/dashboard/directives/add-case-dashboard-action-button.controller.js
ang/test/civicase/activity/card/directives/activity-card.directive.spec.js
ang/test/civicase/dashboard/directives/add-case-dashboard-action-button.controller.spec.js
ang/test/mocks/data/activities.data.js
ang/test/mocks/data/case-actions.data.js
civicase.php

This PR redirects the user to the case details after creating a new case from the dashboard.
* We added a new post process hook to add the expected case details URL to the user context. The reason for this is that the FE does not know the ID of the newly created case and this must be returned by the BE.
* We also updated the `add-case-dashboard-action-button.controller.js` file so it redirects the user when: the user context variable is defined, and the user has not clicked on the "Save and New" button. The reason for this last check is that the BE will send a user context URL when clicking on this button, and this URL is used by `CRM.loadForm` to reload the case form. Since we don't need to handle this scenario we ignore it.
* Removed the `getCaseTypeCategory` function that was reading …

RSE-1056: Redirect to case details after creating a case

---

ang/civicase/case/search/directives/search.directive.html
ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/search/directives/search.directive.spec.js

This PR displays the list of cases when the manage case page loads with the expanded search.
First we need to understand that the search component is the one that triggers the event ([here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/ang/civicase/case/search/directives/search.directive.js#L291-L297)) that initiates the API call to fetch case types. The API call is executed in the case list table when the event that comes from the search component is triggered ([here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/ang/civicase/case/list/directives/case-list-table.directive.js#L397-L399)). Also note that these two components are siblings, not parent-child ([here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/ang/civicase/case/list/ …

CPS-168: Display case list when searching

---

CRM/Civicase/Hook/PreProcess/AddCaseAdminSettings.php
CRM/Civicase/Service/CaseCategorySetting.php
civicase.php
js/civicase-settings-form.js

This PR fixes a regression issue that was introduced after we upgraded to a new CiviCRM version.
The Webform URL fields stopped showing and hiding when they were enabled or disabled for a particular case category.
As pointed by @tunbola, [this core PR](https://github.com/civicrm/civicrm-core/pull/16513) made it possible to automatically append settings to the form without having to alter the template of the admin.
The upgrade of CiviCRM version also updated the admin settings page, and the path that we were relying on was updated and we were not able to add the manual fields and the script needed to hide and show them. This is the only reason why the fields were not duplicated.
To take advantage of the new behaviour introduced by core and to fix the issue, the following changes have been …

CPS-166: Fix case settings

---

.github/workflows/linters.yml
.github/workflows/unit-test.yml

This PR is to add two Github Action workflows which are:
- Linters workflow that contains Eslint, Stylelint, PHPCS
- Unit Tests workflow that contains PHPUnitTest
Currently, the workflow does not run JS tests (Karma tests) as we are having inconstancy issue when tests are failing randomly with Compuclient and always fails with Drupal vanilla. 
Linters and tests were not executed automatically for Pull Requests
Linters workflow will be triggered and run on when every PR is created and/or updated.
- PHPCS will only run if *.php is updated.
- Stylelint will only run if .*scss is updated.
- Eslint will only run if .*js is updated
Unit Tests workflow will be triggered and run when every PR is created and/or updated. 
- On the event that PR is created, the workflow will run all phpunit tests.
* …

IN-336: Add linters and unit tests workflows

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
api/v3/Case/Getdetails.php

This PR fixes few bugs, related to People's tab.
When a Client is removed, all existing relationships for that client should be set to inactive.
This is not a regression.
**Technical Details**
This is fixed in `$scope.unassignRole` function, with the following code
```javascript
// when client
if (!role.relationship_type_id) {
apiCalls.push(['Relationship', 'get', {
case_id: item.id,
is_active: 1,
contact_id_a: role.contact_id,
'api.Relationship.create': { is_active: 0, end_date: 'now' }
}]);
}
```
When replacing a client, all existing relationships for that client, should be reassigned to the new client.
This is not a regression.
**Technical Details**
This is fixed in `getReplaceClientApiCalls` function, with the following code
```javascript
['Relationship', 'get', {
case_id: item.id, …
```

CPS-156: People Tab Bugs

---

info.xml

**Improvements**
- Case category word replacements improvements
**Bug Fixes**
- Fixed an issue where Lower section of the UI not showing cases when user clicks on "Find cases" link from main menu.
- Fixed being unable to search for cases by case client under activities tab for Case categories when moving an activity to another case.
- Fixed numerous issues with the People's tabs on a case including:  
-- Error when adding a case role using Add another Case Role Name menu on the contact row, 
-- Being unable to filter roles on manage cases
-- When removing the first client from a case with multiple clients, the client gets incorrectly assigned to the case manager role.
-- Error shown when adding Benefits Specialist after adding a case client.
- Fix issue with Settings/Webforms URL field …

BASW-634: Civicase Release v1.1.0

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

When some particular fields combination is selected for the Case pivot report, an error screen showing a Db error is shown.
The error described above exists.
The error no longer exists.
The issue actually occurs for when the selected column field is of type Checkbox or select. As can be seen [here ](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Form/Report/BaseExtendedReport.php#L570), a single quote is wrapped around the `&` when the operator is `LIKE`. However, this has already been taken care of [here: ](https://github.com/compucorp/uk.co.compucorp.civicase/blob/2890de5ec1662d4c3345483ceb6dc7025a34ed8b/CRM/Civicase/Form/Report/BaseExtendedReport.php#L663), so this results in two single quotes and this breaks the generated SQL statement.
The fix was to …

BASWSPRT-152: Fix SQL Error with Case Activity Pivot Report

---

ang/civicase/case/factories/format-case.factory.js

If a case status is disabled, then there is an error in Manage Cases page, if a case with disabled case status is present.
In `format-case.factory.js`, only active cases statuses were loaded to fetch the Label of the Case Status for a Case. But if the status is disabled, error was thrown. To fix this, All Case Statuses are loaded.

BASW-621: Fix for Cases with disabled Case Status

---

tests/backstop_data/engine_scripts/puppet/on-before.js
tests/backstop_data/gulp-tasks/backstopjs.js
tests/backstop_data/scenarios/manage-cases.json

This PR Adds Backstop tests for the linked cases tab and the "Other Cases" block on the case summary tab.
We introduced a new property for scenarios: `apiCalls`. It should contain an array of strings which have api calls in the format accepted by [CiviCRM CV](https://github.com/civicrm/cv). Example:
```json
{
"label": "My Scenario",
"url": "some-url",
"apiCalls": [
"contact.create first_name=Jon last_name=Snow contact_type=individual",
"settings.create mySetting=1"
]
}
```
These calls will be made before the scenario is executed. Important: even though we can create any type of record, this is better used for changing settings only. If we need to setup data, we need to change the [backstop data setup task](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/tests/backstop_dat …

CATL-1356: Backstop tests for Other Cases block and Tab

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/BuildForm/AddStyleFieldToCaseCustomGroups.php
CRM/Civicase/Hook/BuildForm/CaseCategoryCustomGroupDisplay.php
CRM/Civicase/Hook/PageRun/CaseCategoryCustomGroupListing.php
civicase.php
js/custom-group-form.js

This PR helps us show the "Display Style" field when creating custom fields for cases. This field is exclusive for contact related entities, but we have made it so it's available for cases as well.
The "Display Style" field is not visible
The "Display Style" field is normally only visible to contact related entities, as defined by Core. We changed this behaviour by creating a `AddStyleFieldToCaseCustomGroups` hook that appends `Case` to the list of entities that support the "Display Style" field.
We also included a JS file to accomplish the following things:
* Hiding the "Support Multiple Records" checkbox, which only makes sense for contact entities.
* Hiding an extra option that shows up in the "Display Style" select after it's saved. This option is called "Tab Table". It's not clear …

CATL-1345: Display style field when extending case entity

---

CRM/Civicase/APIHelpers/CustomGroups.php
CRM/Civicase/APIHelpers/CustomValues.php
api/v3/CustomValue/Getallgroupstreevalues.php
api/v3/CustomValue/Gettreevalues.php
api/v3/CustomValue/getalltreevalues.php

This PR introduces a new endpoint: `CustomValue.getallgroupstreevalues`.
This new endpoint returns the custom values for all active groups. This endpoint is similar to `CustomValue.gettreevalues`, but the later does only return values for inline custom groups.
5 custom groups defined for cases. 2 displayed inline, 3 displayed in tabs.
```js
{
"is_error": 0,
"version": 3,
"count": 2,
"values": {
"Backstop_Case_Custom_Group": {
// ...
},
"Case_Extra_Description": {
// ...
}
}
}
```
```js
{
"is_error": 0,
"version": 3,
"count": 5,
"values": {
"Case_Description": {
// ...
},
"Case_Extra_Description": {
// ...
},
"Test_Case_Custom_Fields": {
// ...
},
"Backstop_Case_Custom_Group": {
// ...
},
"My_Custom_Fields": {
// ...
}
}
}
```
The problem is that the `CRM_Core_BAO_CustomGroup::getTree` …

CATL-1346: All groups tree values endpoint

---

phpcs-ruleset.xml

The PHP Linter is producing error in local/github action. This PR fixes the same.
Error is not present anymore.
Few days back, the “Drupal Coder” php rule set was updated with a new rule, which is in result breaking our PRs.
https://git.drupalcode.org/project/coder/-/commit/7385c9df4a7c93aef8690c1cf22f6f6a52e152ed
`Drupal.Classes.UseGlobalClass.RedundantUseStatement` rule has been excluded to fix this.

CPS-239: Fix PHP lint error

---

ang/civicase-base/providers/case-type-category.provider.js
ang/civicase-base/services/case-type-filterer/case-type-filterer.service.js
ang/civicase-base/services/case-type-filterer/filters/belongs-to-category.service.js
ang/civicase-base/services/case-type-filterer/filters/has-id.service.js
ang/civicase-base/services/case-type-filterer/filters/is-included-in-list-of-ids.service.js
ang/civicase/case/directives/case-overview.directive.html
ang/civicase/case/directives/case-overview.directive.js
ang/test/civicase-base/providers/case-type-category.provider.spec.js
ang/test/civicase-base/services/case-type-filterer/case-type-filterer.service.spec.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/mocks/data/cases-types.data.js

This PR updates the case overview section of the dashboard so we only display the case statuses that have been enabled for the case types that are being displayed.
* Permissive Award has Ongoing, Resolved, Won, and Lost statuses
* Award ON has Ongoing, Resolved, and Urgent statuses
Expected statuses: Ongoing, Resolved, Urgent, Won, and Lost.
Some refactoring was done in order to properly support this enhancement:
* Hidden case statuses are now stored in a separate variable. Since case statuses now depend on the loaded case types we don't need to reload the hidden case statuses from the browser cache each time we reload the case types and statuses.
* We removed the case type fetching and changed it for a local filtering service (more on this below).
* The logic to automatically display the …

CPS-107: Only display case statuses belonging to loaded case types

---

ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/search/directives/search.directive.spec.js

Fix the 'Cases I am involved' filter text in Case Search to 'Cases I am involved in'.

CATL-1437: Fix 'Cases I am involved in' filter text

---

CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php

According to new requirements we need the menu item for new Case type category be visible right away, previously user had to clear cache to see it. Now cache is cleared automatically when Case type category is created / updated / deleted.
There is a `CRM_Civicase_Hook_PostProcess_CaseCategoryPostProcessor` class which handles the Case type category create / update / delete, so we've just added flush cache command to it.

RSE-1020: Clear cache after Case type category create/update/delete

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
api/v3/Case/Getdetails.php

According to new requirements this PR adds *Last activity* field on Case Panel (on Cases tab of Contact page) above the *Next activity* field.
1. To fetch last activity we used respective code from next activity - the `_civicrm_api3_case_get_activities()` was added which is used to fetch both next and last activities now.
2. Also as part of this PR field labels in `contact-case-tab-case-details.directive.html ` were wrapped in `ts()` for consistency.

CATL-1299: Add 'Last activity' to the Case Panel

---

ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/feed/directives/activity-feed.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.html
ang/civicase/case/card/directives/case-card-case-list.directive.html
ang/civicase/case/card/directives/case-card-dashboard.directive.html
ang/civicase/case/card/directives/case-card-other-cases.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/details/directives/case-details-header.directive.html
ang/civicase/contact/directives/contact-card.directive.html
ang/civicase/contact/directives/contact-card.directive.js
ang/civicase/contact/directives/contact-icon.directive.html
ang/civicase/contact/directives/contact-icon.directive.js
ang/civicase/contact/directives/contact-popover-content.directive.html
ang/civicase/contact/directives/contact-popover-content.directive.js
ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js

This PR makes the contact's email address on the contact's popup card to be clickable. When you click the email a form shows up to send an email to the selected contact. The activity that gets created after sending the email can be assigned to a case when the popover is displayed inside a case, or it gets created as a standalone activity when not related to a case.
The email is not clickable
* The contact's popover content directive was updated so we open the email form when clicking on the contact's primary email.
* When a case ID is used we assign this email to a case, otherwise we create a standalone activity. We need to use a condition instead of passing `caseid: undefined` because `undefined` is passed to `CRM.url` and it's not ignored. This breaks the form when no actual case ID is …

CATL-1394: Contact Card Email Links

---

ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/feed/directives/activity-feed.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.html
ang/civicase/case/card/directives/case-card-case-list.directive.html
ang/civicase/case/card/directives/case-card-dashboard.directive.html
ang/civicase/case/card/directives/case-card-other-cases.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/details/directives/case-details-header.directive.html
ang/civicase/contact/directives/contact-card.directive.html
ang/civicase/contact/directives/contact-card.directive.js
ang/civicase/contact/directives/contact-icon.directive.html
ang/civicase/contact/directives/contact-icon.directive.js
ang/civicase/contact/directives/contact-popover-content.directive.html
ang/civicase/contact/directives/contact-popover-content.directive.js
ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js
info.xml

* ‘coming soon’ block in case summary configurable (setting added so can remove ‘coming soon’) https://github.com/compucorp/uk.co.compucorp.civicase/pull/463
* Added a related cases tab (configurable) https://github.com/compucorp/uk.co.compucorp.civicase/pull/473  
* Case overview card on contact record redesigned
* included last activity on case panel and reordered so ‘next activity’ then ‘last activity’ https://github.com/compucorp/uk.co.compucorp.civicase/pull/486 
* summary moved to the top https://github.com/compucorp/uk.co.compucorp.civicase/pull/484
* removed ‘upcoming’ and ‘status’ https://github.com/compucorp/uk.co.compucorp.civicase/pull/484
* Show tags when uploading files https://github.com/compucorp/uk.co.compucorp.civicase/pull/476
* Email addresses are a ‘URL’ to open email …

CPS-248: Release v1.2.0

---

ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/search/directives/search.directive.spec.js

In Manage Case page, when a Relationship filter is applied, the case search gets initiated without applying the filter. But when the relationship filter is changed again, then the previous value gets applied.
This is a regression of https://github.com/compucorp/uk.co.compucorp.civicase/pull/457/files#diff-5debfe960193b84b126dbfbfe8cd35c4R26, the `crm-ui-select` directive from core has a flaw, when `ng-change` is mentioned in `crm-ui-select` directive, the change listener gets fired before the ng-model is changed. To avoid this `$timeout` is applied. 
On the long run we need to fix this by creating a core PR.

CPS-251: Fix Manage Case Relationship filter

---

ang/civicase/case/directives/case-overview.directive.js

In Case Dashboard, console errors are present.
This happens, when a Case Type has added a disabled Case Status.
In `case-overview.directive.js`, now requesting all case status's including the disabled.

CATL-1460: Fix Case Dashboard console errors

---

info.xml

* Fixed a bug with Activity Type filter in Activity Feed, the filter had a Multi Select dropdown, but the feature was not supported by CiviCRM core, so it has been changed to a Single Select dropdown. Also, now that searching with Multiple Categories are not supported, the Hyperlink from "Other Cases" in case card has been removed. This feature never worked, because of the above reasons, so we are removing it. https://github.com/compucorp/uk.co.compucorp.civicase/pull/498
* Fixed a bug in Manage Case page, when a Relationship filter is applied, the case search gets initiated without applying the filter. But when the relationship filter is changed again, then the previous value gets applied. https://github.com/compucorp/uk.co.compucorp.civicase/pull/504
* Fixed a bug in Case Dashboard …

CATL-1462: Release v1.2.1

---

ang/civicase/case/list/directives/case-list-table.directive.js
ang/test/civicase/case/list/directives/case-list-table.directive.spec.js

When changing a Case from Manage Case List, the existing tab filters(activity tab, people tab) were applied to the new case also. This PR fixes that issue, and removes any extra filters.
Added a new function `removeExtraRouteParams`, which removes all parameters added by the individual tabs, when switching to a new case.
```javascript
function removeExtraRouteParams () {
var allowedRouteParams = ['caseId', 'cf'];
$route.current.params = _.pick($route.current.params, function (value, key) {
return allowedRouteParams.indexOf(key) !== -1;
});
}
```

CPS-194: Remove URL parameters added by individual tabs when changing case

---

CRM/Civicase/Hook/BuildForm/DisplayAllCustomGroupsInCaseForm.php
civicase.php

This PR displays both inline and tab custom groups when creating new cases. Previously, inline custom groups where the only ones being displayed.
We created a new `DisplayAllCustomGroupsInCaseForm` hook that runs when preparing the form used to display custom fields for different entities. The form only runs when updating cases (and their respective case categories).
The custom groups and their fields are stored in the form's `_groupTree` property, but only inline ones. To include all groups we first call `CRM_Civicase_APIHelpers_CustomGroups::getAllActiveGroupsForEntity` to fetch all custom groups for a given case category, then we proceed to prepare the custom group data by passing each element to `CRM_Core_BAO_CustomGroup::formatGroupTree`. Finally, we pass this result to …

CATL-1444: Include inline and tab custom groups when creating cases

---

ang/civicase-base/directives/tags-selector.directive.js
ang/civicase-base/factories/is-truthy.factory.js
ang/civicase-base/services/activity-category.service.js
ang/civicase-base/services/activity-status.service.js
ang/civicase-base/services/activity-type.service.js
ang/civicase-base/services/case-status.service.js
ang/civicase-base/services/priority.service.js
ang/civicase/activity/card/directives/activity-card.directive.js
ang/civicase/activity/directives/add-activity-menu.directive.js
ang/civicase/activity/factories/format-activity.factory.js
ang/civicase/case/actions/services/email-managers-case-action.service.js
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/factories/format-case.factory.js
ang/test/civicase-base/factories/is-truthy.factory.spec.js
package-lock.json

In Case Details section, wrong contact was shown as Case Manager. This PR fixes that.
In `ang/civicase/case/factories/format-case.factory.js`, the manager was set with this condition
```javascript
if (contact.manager) {
item.manager = contact;
}
```
But the backend sends value like `contact.manager = '0'`, above logic was setting that contact as true. Hence the error.
To fix this, a new factory `isTruthy` has been created, which checks strings as well as boolean values and return true, if `value === '1'`.
```
isTruthy('1') => true
isTruthy(true) => true
isTruthy(1) => true
isTruthy('0') => false
isTruthy(false) => false
isTruthy(0) => false
```
This function has been used throughout the application, to avoid such bugs.

CATL-1485: Fix for wrong Manager shown on Case Details

---

ang/civicase/case/actions/services/go-to-webform-case-action.service.js
ang/civicase/case/actions/services/webforms-case-action.service.js
ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
ang/test/mocks/data/case-actions.data.js
api/v3/Case/Getwebforms.php

If a webform does not have any case type assigned to it, we now show that for every case type.
1. In `api/v3/Case/Getwebforms.php`, when no case types were assigned, the api used to return `[null]`, instead of an empty array. This is now fixed.
2. In `ang/civicase/case/actions/services/go-to-webform-case-action.service.js`, renamed `checkIfWebformContainsCaseTypeId` to `checkIfWebformVisible`. Now it returns true if the webform does not have any case type assigned.

CPS-270: Show webforms without any Case Types

---

CRM/Civicase/Hook/alterAPIPermissions/CaseCategory.php
api/v3/CustomValue/Getalltreevalues.php

This PR fixes a permission issue that happens when saving custom fields belonging to a custom case category.
The error that was being thrown was 
```
Error in call to CustomValue_getalltreevalues : API permission check failed for CustomValue/getalltreevalues call;
insufficient permission: require ( access my cases and activities or access all cases and activities or basic case information )
```
The issue happened because the new `getalltreevalues` endpoint was trying to use the normal basic case permissions instead of the custom ones for the case category. To fix this we updated the `CRM_Civicase_Hook_alterAPIPermissions_CaseCategory` so the `getalltreevalues` uses the basic custom case permissions.
We also removed an extra permission assignment to `getalltreevalues` since it was …

CATL-1495: Fix permission issue

---

ang/civicase/case/details/directives/case-details.directive.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js

This PR fixes an issue with the case details tabs where multiple tabs would be shown when refreshing the manage cases page.
The issue happened because we kept track of the details tab insertion using a variable. The value of this variable would be forgotten each time the manage case page was reloaded. Another issue is that we were modifying the original list of case tabs and that is why the number of tabs was conserved even when the page was reloaded.

CATL-1494: Fix multiple case details tabs issue

---

CRM/Civicase/Helper/CaseCategory.php

Currently, the word replacements done at the case category level, i.e each case category has it's own word replacement configuration, however since a set of case type categories can share a case category instance, the word replacements now need to be at the instance level. 
Word replacements is done as the case category level. 
Word replacements is now done at the case category instance level.
Rather than checking for the case category word replacement class, the Instance class is now checked.

RSE-1209: Make Word Replacements To Be At Category Instance Level

---

ang/civicase/case/details/directives/case-details.directive.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js

This PR fixes an issue introduced by https://github.com/compucorp/uk.co.compucorp.civicase/pull/513 where it would not be possible to switch to the Details tabs.
The issue happened because we were reading the list of tabs from `CaseDetailsTabs` instead of `$scope.tabs`. The former is the list of tabs included by civicase and other extensions, and the later includes these tabs as well, plus any custom tabs added by the case details directive. In this scenario we added the `Details` tab to `$scope.tabs` and that's why we should use this variable when trying to access tabs.

CATL-1494: Fix active tab issue

---

ang/civicase/case/services/cases-utils.service.js
ang/test/civicase/case/services/cases-utils.service.spec.js

This PR fixes an issue where send an email to the case's client would fail when the word "Client" is replaced by a different word.
Note: The word `Client` has been replaced to `Member`.
The issue happened because the `getAllCaseClientContactIds` method in the case utils service was checking using the hardcoded `Client` value, but this value could have already been translated to `Member` and so when sending an email no client is found and the email form breaks.
To fix this we simply wrap the word `Client` in a `ts` function before we do the check.

CATL-1487: Fix send mail to case client

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html

This PR fixes an issue where changing a case status from the contact's case tab would fail. This would happen when some case statuses have been deleted.
We created some case statuses (A, B, C), deleted one of them (A), and try to change the status to one of the remaining ones (B or C)
The problem is that we were using the index of the case status as the `id` for it. In certain cases this works, but it breaks as soon as some statuses get deleted since the wrong id would be assigned to the index. To fix this we use `status.value` which holds the right status id.
We have also removed an extra `case_status_id: id,` parameter that was being sent when changing the case type. There are two reasons for removing this parameter: 1 - we don't need to send the status ID when changing the case type, …

FEMS-37: Fix change case status

---

ang/civicase/case/actions/services/go-to-webform-case-action.service.js
ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js

When clicking on Webform link from the dropdown, we now show a popup, asking users to refresh the page to get latest data after submitting the webform
In `go-to-webform-case-action.service.js`, added `CRM.alert` function call to show the popup.

CATL-1304: Show popup when clicking on Webform link

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.html

This PR makes email addresses displayed on the People's tab to be interactive.
*Note:* The email addresses links visible here are the contact's name that lead to the contact's page, not the actual contact's email address.
The people's tab markup was updated so it uses `crm-popup` class to open the email form for the given contact and case.

CATL-1466: Add links to email addresses on peoples tab

---

ang/civicase/case/actions/services/go-to-webform-case-action.service.js
ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js

The popup about refreshing the page, when a webform was opened, was only visible for 10 seconds. Now it has been increased to 30 minutes.
In `go-to-webform-case-action.service.js`, added 1800000ms as expire time.

CPS-1304: Increase popup display time to 30 minutes

---

CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
CRM/Civicase/Upgrader.php

The major work for adding custom fields support for case type has already been done in https://github.com/compucorp/uk.co.compucorp.civicase/pull/460. This PR only does some cleanup of deprecated functions that are called when enabling the civicase extension and also renames some variable.
The cleanups were not done.
- Some cleanup was done in the extension and the case category variable in the `CaseCategoryCustomFieldExtends` and `CaseCategoryCaseTypeCustomFieldExtends` was renamed to some more better variable since the variable for creating the custom field entity does not necessarily have to be the case category name.
The deprecated functions/Classes were removed because initially the Civicase extension Custom field support was using a custom function to set case types for custom …

RSE-1200: Case Category Custom Field Support Cleanup

---

CRM/Civicase/Service/CaseCategoryCustomDataType.php
CRM/Civicase/Service/CaseCategorySetting.php

When Installing Civicase on a site for the first time or when running Civicase tests, some notices related to case type categories are shown in the terminal.
- Errors/Notices shown in terminal when installing Civicase fresh on a site.
- Tests ran successfully after this without throwing these notices.
- The issue was because the `case_type_category` field is not originally part of the CaseType BAO but the field that is added to the CaseType BAO via a hook and the field is not available on the BAO at install. The Fix is to fetch the Case type categories using the Option Group BAO.
- Also the function for fetching the Case type categories was pointing to the `case_type_category` rather than the `case_type_categories` option group.

RSE-1199: Fix Errors When Installing Civicase

---

ang/civicase-base/directives/tags-selector.directive.js
ang/test/civicase-base/directives/tags-selector.directive.spec.js

In Case Files Tab, when a file is uploaded with some tags, and then another file is added for upload, the previously selected tabs still show up. This is fixed as part of this PR. Now the tags are cleared after completion of an upload.
In `ang/civicase-base/directives/tags-selector.directive.js`, added a watcher for `$scope.model`, to reset the selected tags.

CATL-1524: Update tags when model is changed

---

CRM/Civicase/Api/Wrapper/CaseGetList.php
CRM/Civicase/Hook/BuildForm/LinkToCaseSearchByCaseId.php
ang/civicase/activity/actions/services/move-copy-activity-action.service.js
ang/test/civicase/activity/actions/services/move-copy-activity-action.service.spec.js
civicase.php

This PR allows searching by Case ID as well as Case client name when searching for cases on the Linked Cases form and on the Move to Case popup form. The default behaviour only allows to search by case client name.
User can only search by case client name.
User can only search by case client name and case id.
The default search field for the Case.getList API which the case search field uses is the Case client name, [see](https://github.com/civicrm/civicrm-core/blob/master/api/v3/Case.php#L746).
A new parameter `search_by_case_id` is introduced as part of the parameter the Case.getList API accepts so that when this parameter is present, the search is done on both the client name and the case Id. The reason for this is that the API might be used else where and we don't want to alter the …

CATL-1511: Enable search by caseID in Linked Cases

---

ang/civicase/shared/directives/file-uploader.directive.html
ang/civicase/shared/directives/file-uploader.directive.js
ang/test/civicase/shared/directives/file-uploader.directive.spec.js

This PR makes the subject field for the Case's file upload form to be required.
* We used angular forms to make the field required.
* We made the `Upload File(s)` button a proper submit button.
* We handle the file upload when the form is submitted using `ng-submit="saveActivity()"`.
* The form is set to pristine after it has been submitted using `$scope.fileUploadForm.$setPristine();`

CATL-1514: Make File Upload Subject Required

---

ang/civicase/shared/directives/file-uploader.directive.js
ang/test/civicase/shared/directives/file-uploader.directive.spec.js

In Case Files tab, when uploading a file with Tags, the tags were not added unless the "edit all contacts" permission is added.
Permission error is with `EntityTag.create`, which is a Core API.
It was decided to switch to custom `EntityTag.createByQuery`endpoint to bypass the permission error, which was created in civicase. And it does not check the "edit all contacts" permission.

CATL-1523: Fix permission error in Files Tab while adding tags

---

ang/civicase/case/actions/directives/edit-tags.html
ang/civicase/case/actions/services/edit-tags-case-action.service.js
ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/contact/directives/contact-card.directive.js
ang/test/civicase/case/actions/services/edit-tags-case-action.service.spec.js

Similar to https://github.com/compucorp/uk.co.compucorp.civicase/pull/545, as part of this PR, permission errors has been fixed while adding/removing tags for a Case.
Also changed the UI of the tags selection modal, to align this with other tags selection modals
1. Used `civicase-tags-selector` directive in `ang/civicase/case/actions/directives/edit-tags.html`.
2. In `ang/civicase/case/actions/services/edit-tags-case-action.service.js`, changed the implementation to use `civicase-tags-selector`.
Also fixed a regression introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/543, which resulted in "To" field not being shown in Activity Card. Also there were console errors.
**Before**
**After**
**Technical Details**
In …

CATL-1605: Edit Cases Tags refactoring

---

ang/civicase/shared/directives/crm-editable.directive.js

As part of this PR, the height calculation for `crm-editable` directive has been fixed.
More details can be found in https://github.com/compucorp/neu/pull/30
In crm-editable.directive.js , the height calculation was not happening correctly using em. So it has been changed to `scope.lineLimit * <height of each line>`.

CATL-1598: Fix height calculation for crm-editable

---

ang/civicase/activity/calendar/directives/activities-calendar.directive.js
ang/civicase/activity/feed/directives/activity-feed.directive.html
ang/civicase/activity/filters/directives/activity-filters.directive.html
ang/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.html
ang/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.js
ang/civicase/bulk-action/directives/bulk-actions-message.directive.html
ang/civicase/bulk-action/directives/bulk-actions-message.directive.js
ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html
ang/civicase/case/list/directives/case-list-table-first-column-header.html
ang/civicase/case/list/directives/case-list-table.directive.html
ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/shared/directives/panel-query.directive.js
ang/test/civicase/activity/calendar/directives/activities-calendar.directive.spec.js
ang/test/civicase/bulk-action/directives/bulk-actions-checkboxes.directive.spec.js
ang/test/civicase/bulk-action/directives/bulk-actions-message.directive.spec.js
ang/test/civicase/shared/directives/panel-query.directive.spec.js
api/v3/Activity/Getdayswithactivities.php

As part of this PR, few optimisations has been made to different parts of the Civicase Application, to make it faster.
When loading the Manage Cases page, we were loading all the Cases, in order to make "Select All" Bulk action functionality to work. But loading all cases takes a lot of time if the system has many cases. And also the "Select All" is not used all the time. 
So now we have moved this loading logic, only on demand. When the user will select "Select All", at that time we are loading the cases.
Previously, the Activity Calendar was making two separate calls to the `Activity.getdayswithactivities` api endpoint. Once to 
fetch dates for Completed Activities, and the other one to fetch Incomplete Activities.
But everytime this API is called, it fetches the full list of cases …

CATL-1606: Application Performance Optimisation

---

ang/civicase/contact/directives/contact-card.directive.html

This PR removes the HTML title (tooltip) when the contact's full name is displayed on activity cards. 
Displaying the full name is controlled through a setting. For info refer to the original PR:
https://github.com/compucorp/uk.co.compucorp.civicase/pull/521
We add an empty title when showing the contact's full name. This stops the title from showing.

CATL-1572: Remove Title from Activity Card when showing Contact's Full Name

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js

As part of this PR, the Activity Creation calls has been removed from People tab, while creating/reassigning roles as it will be handled in the backend.
Made necessary changes in `ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js`.

CATL-1642: Remove activity creation api calls

---

CRM/Civicase/Event/Listener/CaseRoleCreation.php
CRM/Civicase/Service/CaseRoleCreationBase.php
CRM/Civicase/Service/CaseRoleCreationPostProcess.php
CRM/Civicase/Service/CaseRoleCreationPreProcess.php
CRM/Civicase/Test/Fabricator/Relationship.php
CRM/Civicase/Test/Fabricator/RelationshipType.php
civicase.php
phpcs-ruleset.xml
settings/CiviCase.setting.php
tests/phpunit/CRM/Civicase/Helpers/CaseSettingsTrait.php
tests/phpunit/CRM/Civicase/Helpers/SessionTrait.php
tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPostProcessTest.php
tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
tests/phpunit/api/v3/CaseRoleCreationTest.php
tests/phpunit/bootstrap.php

Currently, when a case role is added using the Relationship.create API, the logic for creating the activity and reassigning the role resides in the Frontend, this is a disadvantage because if a case role is added via some other means, e.g webform, these logic is not activated. This PR moves these business logic to the backend so that when a case relationship is created from any source either via Webform or civicrm fronted, these post processing is triggered in all cases.
This PR also adds the `One active case role` setting to the civicrm settings page, what this settings does in essence is that it will only allow one active instance of each case role for all case types when turned on.
- The `One active case role` setting is not added.
- Business logic when creating/reassigning a case …

CATL-1637: Add Business Logic to Handle Pre and Post Processing Of Creating A Case Related Relationship

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js

This PR fixes the following bugs related to single case role selection:
* Removing an existing role was removed unintentionally in https://github.com/compucorp/uk.co.compucorp.civicase/pull/556 and this was restored.
* Whe pass the right parameter value to the relationship endpoint when reassigning a relation. Previously we were passing the contact ID instead of the relationship ID.
To restore this functionality we looked into the previous code removed by https://github.com/compucorp/uk.co.compucorp.civicase/pull/556 and only included the part that removes the case role.
The list of roles and list of contacts don't include the relationship ID so when we need to replace a relationship we make a chained API call to first get the relationship ID and then do the replacing as normal.

CATL-1642:  Single Case Role Bug Fixes

---

CRM/Civicase/Service/CaseRoleCreationPostProcess.php
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js

As part of this PR, specifying reassignment date while reassigning role in people's tab is now supported.
Also fixed a regression with when reassigning roles. It happened in https://github.com/compucorp/uk.co.compucorp.civicase/pull/560. As we choose to use Chained api calls, it always passes the relationship id to the chained api call, so it became a "Update" call instead of "Create". Hence it was not setting the old relation as inactive, instead it was just updating the old relationship. This is fixed now.

CATL-1590: Specify reassign role date in people's tab

---

CRM/Civicase/Hook/BuildForm/CaseTypeCategoryWebFormRedirect.php
CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
CRM/Civicase/Hook/PreProcess/CaseTypeCategoryWebFormRedirect.php
CRM/Civicase/Hook/SummaryActions/AlterAddCaseAction.php
civicase.php

If a web form is available for a case type category then all the add case links for that particular case type category should take the user to that web form.
There was a alter navigation menu hook placed to replace the url with web form url but that hook was not enough to cater all the places in html that had the link.
Instead of changing the link urls a new pre process form hook has been added which will redirect the user to the web form if one is available for the current case type category. So this hook will add as a global redirect handler and there wont be any need for multiple hooks to change the urls in pages html. But this approach has one limitation that at the moment redirect to pages other than civicrm on popups cannot be achieved so redirect will only work for non ajax pages.

CATL-1684: Add Case Webform Redirect

---

.github/workflows/backstop.yml
.gitignore
tests/backstop_data/Readme.md
tests/backstop_data/backstop.tpl.json
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-add-tag.js
tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-remove-tag.js
tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-dropdown.js
tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-client.js
tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-non-client.js
tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-other-relationships-loading.js
tests/backstop_data/gulp-tasks/backstopjs.js
tests/backstop_data/package-lock.json
tests/backstop_data/scenarios/activity-feed-panel.json
tests/backstop_data/scenarios/contact-case-tab.json
tests/backstop_data/scenarios/dashboard.json
tests/backstop_data/scenarios/manage-cases.json
tests/backstop_data/site-config.json.sample

As part of this PR, Backstop JS tests are configured through Github Actions.
At the moment, backstop js is run on our local. And the problem with this is, 
1. Setting up backstop tests, is not nice experience, as we need to make sure all the data is setup properly.
2. Also running the tests take at least an hour, and if some data is missing, then we need to re run.
So the idea is to run Backstop tests through Github Actions, with data being set up automatically using code.
To run the test, Add "run backstop" label to the Pull Request.
If needed to rerun backstop tests in the same Pull Request, just remove the "run backstop" label and add it again.
1. One "run backstop" label is added to the Pull Request, the github action will start running.
2. After 15-20 mins, when all the tests are …

CPS-245: Backstop JS GitHub Action

---

ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js

This PR fixes a bug where standalone email activities could not be resumed.
The issue happens because we were referencing the activity's assignee contact and this contact is not defined for standalone activities, only for case activities. We replaced this to the source contact which is used by both standalone and case activities. For case activities the source contact and assignee are the same for draft emails.

FEMS-45: Fix resuming standalone draft email activities

---

CRM/Civicase/Event/Listener/ActivityFilter.php
CRM/Civicase/Event/Listener/CaseRoleCreation.php
CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php

On enabling any Drupal module on the latest Compuclient deployed sites running CiviCRM 5.28.0, an error page is displayed with the Configuration saved message. This is not happening on sites with CiviCRM 5.24.6.
Error when enabling a drupal module on sites running CiviCRM 5.28.0.
No errors when enabling a drupal module on sites running CiviCRM 5.28.0.
When enabling a module in drupal, some internal functions will be called to refresh some data cached in memory. At some point this will call a CiviCRM function, that, in the past would call the ContactType BAO. After the change in CiviCRM 5.28.0, this now calls the API V4. This will dispatch an event, that will be captured by the listener in civicase. The civicase event listener tries to convert the `$apiRequest` variable to an array …

CPS-319: Fix Error Page When Enabling Drupal Module

---

info.xml

- Fixes a bug where standalone email activities could not be resumed. https://github.com/compucorp/uk.co.compucorp.civicase/pull/548
- Fixed a bug where "Add Case" from Contact Record page was not redirecting to Webforms(if configured). https://github.com/compucorp/uk.co.compucorp.civicase/pull/567
- Fixed a bug where enabling any Drupal module on the latest Compuclient deployed sites running CiviCRM 5.28.0, displayed an error page. https://github.com/compucorp/uk.co.compucorp.civicase/pull/570
- Backstop JS tests are configured through Github Actions. Means they can be run for any Pull Requests. https://github.com/compucorp/uk.co.compucorp.civicase/pull/537

CPS-302: Release v1.8.0

---

CRM/Civicase/Helper/CaseSetting.php
CRM/Civicase/Helper/XmlProcessor.php
CRM/Civicase/Hook/PreProcess/AddCaseAdminSettings.php
js/civicase-settings-form.js
settings/CiviCase.setting.php

Recently the single case role per type setting was introduced, however this setting is not applicable when the muliclient setting is on, hence we need to make sure that this setting does not show up when multiclient is on. This PR makes that happen.
Currently the Single Case role setting checkbox will show up irrespective of the value of the Multiclient Case setting field.
Now the single case role and allow multiple clients settings has been placed with each other and a relationship between them has been added which will allow to tick single case role only if single client per case is selected as shown below.
CRM_Civicase_Hook_PreProcess_AddCaseAdminSettings hook has been modified to place both the above mentioned settings with each other and js/civicase-settings-form.js file is …

CATL-1674: Allow Single Case Role Setting Only When Multiclient Case Setting Is Single

---

.github/workflows/linters.yml
ang/civicase-base.ang.php
ang/civicase-base/providers/case-type-category.provider.js
ang/test/civicase-base/providers/case-type-category.provider.spec.js
ang/test/mocks/data/case-category-instance-mapping.data.js
ang/test/mocks/data/case-category-instance-type.data.js
phpcs-ruleset.xml

As part of this PR( and https://github.com/compucorp/uk.co.compucorp.civiawards/pull/127 ), Frontend Solution to support Award Instance has been added.
1. `case_category_instance_type` option group is exposed to the frontend.
2. Mapping of Case Category and Instance has been exposed to the frontend using `caseCategoryInstanceMapping` property.
3. In `case-type-category.provider.js`, added 2 new functions
* `findAllByInstance` : Used to find all case type categories by the given instance name.
* `isInstance` : Used to check, if the sent case type category is part of the sent instance.
4. Moved "exclude DAO files" linter rule to the ruleset file from `linter.xml`. This was done because otherwise the PHP linter was picking up JS files.

RSE-1096: Awards Instance support - Frontend solution

---

ang/civicase/activity/filters/directives/activity-filters.directive.html
ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.html

The Bulk Action and Activity Filters inside the Activity Feed stopped working when using with latest version of Civicrm(v 5.28.3).
Recently in Civicrm Core(https://github.com/civicrm/civicrm-core/commit/dfe20f626c7d6e9eb2b80d9f19b9d5a7c0dfc2fd#diff-d8719e8d406c65259e59e38cfe10efbeR1663) the following function was added `$.htmlPrefilter`. This function removed self closing tags from the markup.
More details can be found here https://github.com/civicrm/civicrm-core/commit/dfe20f626c7d6e9eb2b80d9f19b9d5a7c0dfc2fd#diff-d8719e8d406c65259e59e38cfe10efbeR1664-R1725.
So as part of this PR, `<civicase-bulk-actions-checkboxes>` tags has been fixed. As it was self closing before.

CPS-326: Fix self closing html custom tags

---

tests/backstop_data/gulp-tasks/backstopjs.js

After https://github.com/compucorp/uk.co.compucorp.civicase/pull/537, the Backstop JS github action was still not working. This PR fixes that.
The github actions failed with following error
`Error: Mandatory key(s) missing from params array: source_contact_id`.
Recently this piece of code was added https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Service/CaseRoleCreationPostProcess.php#L190, which expect the logged in user id to be present.
But when using `cv api|batch`, this does not get set.
So `cv api:batch -U ${LOGGED_IN_USER_NAME}` is used, which sets the username.

CPS-245: Fix source_contact_id error

---

info.xml

* Allow only a single user per case role. This can be configured through a setting. [CATL-1674](https://github.com/compucorp/uk.co.compucorp.civicase/pull/569) and [CATL-1579](https://github.com/compucorp/uk.co.compucorp.civicase/pull/568).
* Fixed the bulk dropdown element. This element stopped working after updating the CiviCRM version. [CPS-326](https://github.com/compucorp/uk.co.compucorp.civicase/pull/576).
* Fixed the sample data generation for Backstop. This also helps fix the assets generated by the github action. [CPS-245](https://github.com/compucorp/uk.co.compucorp.civicase/pull/577).

CPS-320: Release v1.9.0

---

CRM/Civicase/Upgrader/Steps/Step0012.php
ang/civicase-base/constants.js
ang/civicase-base/directives/send-to-api-on-change.directive.js
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/civicase/case/details/people-tab/services/role-dates-updater.service.js
ang/test/civicase-base/directives/send-to-api-on-change.directive.spec.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
ang/test/civicase/case/details/people-tab/services/role-dates-updater.service.spec.js
ang/test/mocks/data/constants.data.js

This PR allows case role dates to be updated. When a new date is selected, all relationships belonging to the role are updated with the new date and an activity is created to record the change.
Nothing happens aftering changing the date.
We split the logic to update the date into a service and a directive. The "Send To API On Change" directive takes care of sending the API data and managing the saving state, and the "Role Dates Updater" service which takes care of preparing the API data to send and updating the local date values after they have been updated on the API. The directive is meant to be generic so it can be used with other inline editor components. More info below.
A new upgrader was added to create the the "Change Case Role Start Date" and "Change Case Role End Date" activity …

CATL-1758: Update case role dates

---

CRM/Civicase/BAO/CaseCategoryInstance.php
CRM/Civicase/Factory/CaseTypeCategoryEventHandler.php
CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/BuildForm/AddCaseCategoryInstanceField.php
CRM/Civicase/Hook/CaseCategoryInstanceBase.php
CRM/Civicase/Hook/PostProcess/CaseCategoryPostProcessor.php
CRM/Civicase/Hook/PostProcess/SaveCaseCategoryInstance.php
CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
CRM/Civicase/Service/CaseCategoryCustomDataType.php
CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
CRM/Civicase/Service/CaseCategoryInstanceUtils.php
CRM/Civicase/Service/CaseCategoryMenu.php
CRM/Civicase/Service/CaseCategorySetting.php
CRM/Civicase/Service/CaseManagementUtils.php
CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
CRM/Civicase/Setup/CaseCategoryInstanceSupport.php
CRM/Civicase/Test/Fabricator/CaseCategory.php
CRM/Civicase/Upgrader/Steps/Step0012.php
tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php

The case category webform settings display the case category value rather than the case category name. This PR fixes that. 
The issue was introduced in this [commit](https://github.com/compucorp/uk.co.compucorp.civicase/pull/533/files#diff-827f957d95878344873e43d0ee49df39R17) when the function for fetching the case type category options was modified. The new function returns an array with the case category name as the key and the case category value as the Value which is the opposite of what the old function does. 
To fix the issue the array was flipped.

RSE-1309: Fix Issue With Case Category Webform Setting Displaying Category Value Instead Of Name

---

.gitignore
ang/civicase/case/actions/directives/case-actions.directive.js
ang/civicase/case/details/directives/case-details-clear-filters.html
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/list/directives/case-list-table.directive.html
ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/case/search/directives/search.directive.spec.js
ang/test/karma.conf.js
package-lock.json
tests/backstop_data/package-lock.json

In Manage Case page, when a case from the (n +1) page is selected, and then the filter is changed so that the current case is no longer part of the filtering. In this stage, when page is refreshed and "Clear Filters" button is pressed, the UI was still not showing the requested case. This PR fixes the same.
1. Added `lcov` coverage reporter to karma js, so that the same can be used by IDEs to find uncovered source code.
2. Previously, if the requested case was in the 2nd page(or any page other than the first page), the error happened because in https://github.com/compucorp/uk.co.compucorp.civicase/blob/ed5f60375e8d9ba3400a70299f48c8bda71fa8c9/ang/civicase/case/list/directives/case-list-table.directive.js#L445
the `page_of_record`, only gets applied when loading the page for the first …

CATL-1675: Fix Clear Filters Button

---

.github/workflows/unit-test.yml
README.md

As part of this PR
1. Added Github Action badges to the readme.md file, so that the status of the tests can be seen in the Repositories home page.
2. Update Civicrm version to 5.28.3 in unit test github action.

RSE-1393: Add unit tests badge

---

CRM/Civicase/Hook/Tokens/AddContactTokens.php
CRM/Civicase/Hook/Tokens/AddContactTokensValues.php
CRM/Civicase/Service/ContactCustomFieldsProvider.php
CRM/Civicase/Service/ContactFieldsProvider.php
civicase.php
tests/phpunit/CRM/Civicase/Hook/Tokens/AddContactTokenValuesTest.php
tests/phpunit/CRM/Civicase/Service/ContactCustomFieldsProviderTest.php

Adds contact entity fields to tokens for currently logged in user.In addition to contact fields it also adds to tokens the custom fields that extends contact, individual, organization and household.
Previously there were core tokens for contact but that belonged to the target contact of the document.
In addition to contact fields that refers to target contact there are new tokens added that belongs to currently logged in user. They follow naming convention of current_user.contact_field_name and resides in current user tokens.
This pr utilizes two hooks namely hook_civicrm_token and hook_civicrm_tokenvalues. First one is used to define custom tokens that can target current user and second one is used to define values for the tokens.

CATL-1785: Add Current User Contact Entity And Contact Custom Fields To Tokens

---

CRM/Civicase/Setup/AddChangeCaseRoleDateActivityTypes.php
CRM/Civicase/Setup/ChangeCaseRoleDateActivityTypeSetup.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0013.php
ang/civicase/case/details/people-tab/services/role-dates-updater.service.js
ang/test/civicase/case/details/people-tab/services/role-dates-updater.service.spec.js
package-lock.json

This PR fixes an issue related to the role date change introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/581 If the previous date role was missing, it would throw an error.
The issue happened because we use jQuery's parser function to parse the previous role date. Since the date was not defined the parser would throw an error. To avoid this we modified the function so it would omit the dates that are missing from the activity's subject. This also improves the subject's structure.
* The package lock file was updated so it now is similar to the output produced by the right NPM version, which is defined by the NVM config file in the repo.
* The upgrader that added the activity types for the change role date was refactored so it can run on new installations and existing …

CATL-1804: Fix role date issue

---

ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

This PR fixes an issue where active case relationships would not be properly displayed if the contact had a previous inactive relationship to the case.
The issue happened because when we were grouping the case role relationships in the `getUniqueCaseRelationships`, we were sorting them by the `is_active` field. Since some of the values would contain `0`, this would be sorted first and would be the value used as the representative of the group even if there was another active case for the same contact. This in turn meant that the contact would not be displayed.
To fix the issue we don't sort by the active field, but find the active role when grouping them. If no active role is displayed, we select the first in the group.

CATL-1806: Fix active case relationship

---

ang/civicase/case/details/people-tab/directives/roles-tab.directive.html

This PR fixes the list of roles that is displayed when clicking the "Add Case Role" button in the People's Tab.
This was a regression introduced by https://github.com/compucorp/uk.co.compucorp.civicase/pull/574. When updating the list of roles the previous parameter was updated instead of using the role service variable.

CATL-1807: Fix Add Case Role button

---

ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

This PR fixes an issue when working with single case roles. https://github.com/compucorp/uk.co.compucorp.civicase/pull/574 introduced a regression where multiple case roles could be added even if the setting forbade this.
Counting the number of case roles was already in place before refactoring the code into the role service. The count is used to know if more contacts can be assigned to a particular case role. There were two issues with the original approach:
1. We were using the field `name` instead of `role`. Name does not exist in either object.
2. Inactive case roles would be taken into consideration, a feature the previous implementation didn't have a problem with because it didn't support it. After allowing listing past case roles, we should only count the ones that are active.
Unit …

CATL-1852: Fix limit for adding roles

---

CRM/Civicase/Service/CaseRoleCreationPreProcess.php
tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php
tests/phpunit/api/v3/CaseRoleCreationTest.php

This PR fixes an issue where the role start date is always set to today, even if a different date is provided. This happens when creating or reassigning a case role.
This issue was introduced by the `CRM_Civicase_Service_CaseRoleCreationPreProcess` class which was added in https://github.com/compucorp/uk.co.compucorp.civicase/pull/557
The reason for this class was to automatically set the default date as today and fixes issues with webforms, specifically when dealing with single case roles.
To fix this we only set the current date to today when working with single case roles, but also the start date is empty.

CATL-1803: Use provided start date when reassigning roles

---

CRM/Civicase/Form/CaseCategoryTypeCustomField.php

This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/130.
Here we add a flag `hasCustomFieldsAssigned` to the `CRM/Civicase/Form/CaseCategoryTypeCustomField.php` file, when there are no Custom Field Sets available for the sent Entity ID.

RSE-1296: Add a flag to notify when custom fields are not present

---

CRM/Civicase/Service/CaseCategoryPermission.php
ang/civicase-base/services/crm-load-form.service.js
ang/civicase-base/services/crm-url.service.js
ang/civicase/case/actions/directives/case-actions.directive.js
ang/test/civicase-base/services/crm-load-form.service.spec.js
ang/test/civicase-base/services/crm-url.service.spec.js
ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
ang/workflow/action-links/controllers/workflow-duplicate.controller.js
config/urls/case_category_url.php
xml/Menu/civicase.xml

As part of this PR, new permission `administer Civi<case type category>` has been created for all case type categories available in a system.
1. In `CRM/Civicase/Service/CaseCategoryPermission.php`, added the new permission.
2. In `config/urls/case_category_url.php`, added `case_type_category` permission check for `civicrm/workflow/a` url.
3. In `xml/Menu/civicase.xml`, updated the permission to access workflows list page.
4. In `ang/workflow/action-links/controllers/workflow-duplicate.controller.js`, changed the Notification message to match the requirements.
5. Also added new unit tests. And in this process, created 2 new services `civicaseCrmLoadForm` and `civicaseCrmUrl`, which encapsulate `CRM.loadForm` and `CRM.url` global JS functions. Reasoning behind creating this, is that we …

RSE-1375: Create New Permissions to access Workflows List page

---

info.xml

**New Features**
* Add a new permission to restrict the export of reports and case information. [CATL-1585](https://github.com/compucorp/uk.co.compucorp.civicase/pull/584).
**Enhancements**
* End date is visible for a case role in peoples tab while adding/updating case roles. [CATL-1591](https://github.com/compucorp/uk.co.compucorp.civicase/pull/575).
* Introduce an inline date picker for case role start and end date while adding/updating case roles. [CATL-1592](https://github.com/compucorp/uk.co.compucorp.civicase/pull/585).
* Past case roles are visible in peoples tab. [CATL-1593](https://github.com/compucorp/uk.co.compucorp.civicase/pull/574).
* Add New tokens for current user while creating pdf and emails. [CATL-1785](https://github.com/compucorp/uk.co.compucorp.civicase/pull/590) …

CPS-347: Release v1.9.2

---

CRM/Civicase/Hook/BuildForm/MakePdfFormSubjectRequired.php
CRM/Civicase/Hook/BuildForm/PdfFormSubjectRequired.php
civicase.php

This pr makes the subject field required in the pdf create form.
Previously it was possible to fill and submit the form and create the pdf without filling the subject field.
This pr stop user from submitting the pdf creation form with subject field being empty.
Build form hook is used to check if there is a subject field in the pdf create form and if there is then this makes that field required

CATL-1823: Make subject field required in create pdf form

---

CRM/Civicase/Helper/CaseManagementCustomGroupPostProcess.php
CRM/Civicase/Helper/InstanceCustomGroupPostProcess.php
CRM/Civicase/Hook/PageRun/CaseCategoryCustomGroupListing.php
CRM/Civicase/Hook/Post/CaseCategoryCustomGroupSaver.php
CRM/Civicase/Hook/Post/UpdateCaseTypeListForCaseCategoryCustomGroup.php
CRM/Civicase/Service/BaseCaseTypePostProcessor.php
CRM/Civicase/Service/BaseCustomGroupDisplayFormatter.php
CRM/Civicase/Service/BaseCustomGroupPostProcessor.php
CRM/Civicase/Service/CaseCategoryInstanceUtils.php
CRM/Civicase/Service/CaseManagementCaseTypePostProcessor.php
CRM/Civicase/Service/CaseManagementCustomGroupDisplayFormatter.php
CRM/Civicase/Service/CaseManagementCustomGroupPostProcessor.php
CRM/Civicase/Service/CaseManagementUtils.php
tests/phpunit/CRM/Civicase/Hook/PageRun/CaseCategoryCustomGroupListingTest.php
tests/phpunit/CRM/Civicase/Hook/Post/CaseCategoryCustomGroupSaverTest.php
tests/phpunit/CRM/Civicase/Service/CaseManagementCaseTypePostProcessorTest.php
tests/phpunit/CRM/Civicase/Service/CaseManagementCustomGroupDisplayFormatterTest.php
tests/phpunit/CRM/Civicase/Service/CaseManagementCustomGroupPostProcessorTest.php

Previously we have business logic in some hook classes for modifying the custom group listing page, performing some actions when a custom group is saved or updated or when a case type is created/updated. 
This was working fine but now that we have introduced category instances, what to modify on the listing page for a custom group might be diffrent for the case management and applicant management instances which is why this PR decouples this logic into specific instance related classes so that each category instance can have it's own logic encapsulated within it's related class.
The hook classes for modifying the custom group listing page, performing some actions when a custom group is saved or updated or when a case type is created/updated runs based on a general business logic for all …

RSE-1373: Use Category Instance Related Classes In Custom Group Related Hooks

---

ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

This PR fixes an issue where client roles would not be visible 
The issue happened because we were filtering the case clients in the list of case contacts using the ts function as follows: `{ role: ts('Client') }`. The problem is that the role is always set to `Client`, even if the particular case category displays this as `Applicant` or `Prospect`, etc.
This was a regression introduced by https://github.com/compucorp/uk.co.compucorp.civicase/pull/574
To fix the issue we simply removed the `ts` function when filtering.
There was also an issue with the translation of the word `Client` for certain case categories, such as award. The problem is that the object we were using to display the client's data didn't have the role translated. To fix this issue we translated the word `Client` …

CPS-359: Fix case client issues

---

CRM/Civicase/Service/CaseCategoryInstance.php
CRM/Civicase/Service/CaseCategoryMenu.php
CRM/Civicase/Service/CaseInstance.php
CRM/Civicase/Setup/AddManageWorkflowMenu.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0014.php
package-lock.json

As part of this PR, the Manage Workflows menu has been created for `case_management` case type categories.
Menu Items were not present.
Menu Items are created. 
1. In `CRM/Civicase/Service/CaseCategoryMenu.php`, added "Manage Workflows" menu item for newly created sites.
Also added `createManageWorkflowMenuForExistingCaseCategories ` function, which creates Manage Workflow menu for existing case type categories of the system.
2. Added `CRM_Civicase_Service_CaseInstance` service class, which includes `assignInstanceForExistingCaseCategories` function. This function assigns all existing Case Type categories to the `case_management` instance.
3. Added a new upgrader which uses `CRM_Civicase_Setup_AddManageWorkflowMenu ` class to execute both of the above steps.

RSE-1380: Add "Manage Workflows" Menu

---

CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
civicase.php
js/civicase-settings-form.js
settings/CiviCase.setting.php

This PR adds the following changes:
* A new "Restrict email recipients to contacts involved with the case" setting.
* The list of case contacts is added to the front-end settings object when opening a case email form.
The new setting was added to the `settings/CiviCase.setting.php` file in the regular way except for the help text. There seems to be an issue in CiviCRM with settings pages and help texts as explained by their documentation (https://docs.civicrm.org/dev/en/latest/framework/setting/ see `help_text`). The help text is not exposed to the front-end and the `CRM.help` service displays an empty message. To fix this we pass the help text through an HTML parameter and added javascript code in `js/civicase-settings-form.js` to make sure the help text is properly displayed.
The …

CATL-1863: Add case email contacts to front-end settings

---

CRM/Civicase/Hook/ValidateForm/SaveCaseTypeCategory.php

This PR updates the validation rule when creating a case type category to disallow the space character. 
This validation was not updated
Since we use the case category name to setup some functionalities like custom fields support, Civicrm for example expects the name of the object to be extended not to contain spaces, else the Javascript generated on the Add custom group screen will be broken when trying to select options for the Entity.

RSE-1469: Disallow space in category name when creating a case type category

---

CRM/Civicase/APIHelpers/CaseDetails.php

The contact involved filter queries for cases where the passed in contact is a client or has a relationship with the client of a case. If the `Include activities I'm involved in` setting is turned on, it will also include cases where the contact has a linked activity. The functionality works fine but on sites having thousands of records, the subquery to fetch the cases for the involved filter loads very slowly. An investigation was done on this and some recommendations made on how to rewrite this query. This PR implements the recommendations and adds the optimized query.
There might be other query optimizations needed but this PR focuses on optimizing that part of the code for now.
```sql
SELECT civicrm_case.id
FROM civicrm_case
LEFT JOIN civicrm_case_contact AS case_client
ON …
```

CATL-1876: Optimize query for for handling contact involved filter.

---

CRM/Civicase/Service/CaseRoleCreationPostProcess.php
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/details/people-tab/directives/contact-prompt-dialog.html
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js

This PR changes the way relationships are removed or reassigned. Previously we would only allow the current or future dates, but this was changed to the current or past dates.
This change is made to be in alignment with the https://github.com/civicrm/civicrm-core/pull/18844 core PR that handles the active status of the relationship depending on the start and end dates provided.
These screen grabs have been taken from the NEU site where https://github.com/civicrm/civicrm-core/pull/18844 has been merged and the issue is more apparent. This has been tested in Compuclient sites without the aformentioned change and it works the same as before, but dates are limited.
We added logic to the BE and FE so when the end date is the same as today we send `is_active: 0` instead of the end date. This is …

CATL-1917: Limit relationship remove/reassign end date to today

---

CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
js/restrict-case-email-contacts.js

This PR replaces the recipient dropdowns in the case email forms by using new dropdowns that can only select case contacts.
We took the list of contacts generated in https://github.com/compucorp/uk.co.compucorp.civicase/pull/618 and used them to replace the existing recipient dropdowns. The only note is that the `To` field expects values to be in a `123::contact@example.com` and the `CC` and `BCC` expect the contact IDs only.

CATL-1864: Replace recipient dropdowns with case contacts dropdowns

---

CRM/Workflow/Hook/addDependentAngularModules.php
ang/civicase-base/providers/case-type-category.provider.js
ang/test/civicase-base/providers/case-type-category.provider.spec.js
ang/test/workflow/action-links/controllers/workflow-duplicate.controller.spec.js
ang/test/workflow/services/ang/workflow/services/duplicate-workflow-case-management.service.spec.js
ang/workflow.ang.php
ang/workflow/action-links/controllers/workflow-duplicate.controller.js
ang/workflow/services/duplicate-workflow-case-management.service.js

Refactor Duplicate Workflow functionality to support overriding from other extentions.
No visual change has happened.
1. In `ang/workflow/action-links/controllers/workflow-duplicate.controller.js`, changed the logic to look for a service with the name of `DuplicateWorkflow<case-category-instance-name>`. This service should have a function called `create`, which should have the logic to duplicate workflows of that instance.
Here underscores are removed, and the first letter is capitalised from the <case-category-instance-name>.
So for `case_management`, the service name would be `DuplicateWorkflowCasemanagement`.
2. Added a way to add dependent angularjs modules of `workflow`. So created `CRM_Workflow_Hook_addDependentAngularModules` class. Which is going to be used by other extentions.

RSE-1455: Refactor Duplicate Workflow functionality

---

CRM/Civicase/Hook/BuildForm/AddScriptToCreatePdfForm.php
CRM/Civicase/Hook/BuildForm/MakePdfFormSubjectRequired.php
civicase.php
js/create-pdf-form.js

This pr adds a redirect for the user after pdf is generated. User is redirected when he clicks on the Create pdf button and not on clicking the preview  button.
Previously when user generated the pdf the pdf form did not get close and user stayed on the same page.
This pr adds a redirect to the activities page after pdf generation, If the pdf is generated inside a case then the user will be redirected to case activities otherwise to contact activities.
This pr utilizes buildform hook in `CRM/Civicase/Hook/BuildForm/AddScriptToCreatePdfForm.php` to add new script file to the pdf creation form. This new script checks the user current location while creating the pdf and redirects accordingly.

CATL-1900: Redirect After Pdf Download

---

CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
civicase.php
js/civicase-settings-form.js
js/restrict-case-email-contacts.js
settings/CiviCase.setting.php

This PR has all the changes needed to restrict case email recipients to case contacts only. The included changes are:
* CATL-1863: Add case email contacts to front-end settings #618
* CATL-1864: Replace recipient dropdowns with case contacts dropdowns #623

CATL-1799: Restrict Case Email Contacts

---

civicase.php

Fixed the following issues, about PDF Download activity.
1. When "Download Document" was pressed, it deleted the activity instead of moving it to `Completed` state.
2. When `Preview` was pressed, it also deleted the activity, but nothing should have happened to the activity.
Issues were not fixed.
Issues are fixed.
In `civicase.php` postpocess hook,
1. Added code to check if the clicked button is "Download Document".
2. If true, instead of deleting the activity, updating its status to `Completed`.

CPS-384: Fix PDF Download activity deletion

---

CRM/Civicase/BAO/Query/CaseCategory.php

Currently when a case category user is performing a search on the Advanced search page, the search results is restricted to the case type categories that the logged in user has access to. This logic is wrong and we should only limit the search result by case type categories when the user tries to search with case related filters
The fix is applied and we make sure that before we apply the logic to limit search results by case type categories, the advanced search query object should have have a join with the case table which means the user tried to perform the search with a case filter.

CPS-372: Limit Adv. Search By Accessible Case Categories Only When Case Filters Are Present

---

info.xml

**Improvements**
* Restricted case email recipients to case contacts only. https://github.com/compucorp/uk.co.compucorp.civicase/pull/627
**Bug Fixes**
* Fixed PDF Download activity deletion when "Download Document" was pressed. https://github.com/compucorp/uk.co.compucorp.civicase/pull/629
* Refactored duplicate Awards functionality. https://github.com/compucorp/uk.co.compucorp.civicase/pull/620
* Limit relationship remove/reassign end date to today. https://github.com/compucorp/uk.co.compucorp.civicase/pull/626
* Limit Adv. Search By Accessible Case Categories Only When Case Filters Are Present. https://github.com/compucorp/uk.co.compucorp.civicase/pull/630

CPS-386: Release v1.9.5

---

CRM/Civicase/Helper/NewCaseWebform.php

On some client sites, where a webform is used for adding a case, when the Add case webform link is clicked the client id in the webform link is not correctly filled thereby leading to some values in the webform not being auto-populated as expected.
The function for fetching the webform client Id in civicase assumes that the `client_id` would always be an array but it some cases, it is actually an integer as that is what was observed in the client site where this issue was reported thereby returning `null` as the client Id, however checking how the webform_civicrm processes the client_id variable [here](https://github.com/colemanw/webform_civicrm/blob/7.x-5.x/includes/wf_crm_webform_preprocess.inc#L631), the value might not always be an array and is first …

CATL-1959: Fix Bug In Fetching Webform Client ID

---

ang/civicase/case/actions/services/email-case-action.service.js
ang/test/civicase/case/actions/services/email-case-action.service.spec.js
package-lock.json

Previously in the "Email - Send Now" popup, "client" role was not shown as an option. This PR adds that feature, so that email can be sent to clients too.
In `ang/civicase/case/actions/services/email-case-action.service.js` modified the `getContactsForCaseIds` function to fetch client ids, if Client role is selected.

RSE-1516: Add Client Role To Roles List While Sending Bulk Email

---

CRM/Civicase/Helper/NewCaseWebform.php
CRM/Civicase/Hook/PreProcess/CaseTypeCategoryWebFormRedirect.php

When the Add case creation form is overriden via the civicase settings to instead redirect to a webform, using the Add case button on the actions menu for a contact redirects to the webform correctly but the contact details that should be autofilled on the webform is not autofilled because the contact ID and webform cid parameter is not passed in the URL.
This PR fixes the issue.
- The issue described above exists.
The `CaseTypeCategoryWebFormRedirect` PreProcess hook is responsible for redirecting the Case form to the equivalent webform URL for the case category. This hook is modified to take the form contact ID into consideration and pass it along with the webform cid parameter as URL arguments when redirecting to the webform.

CATL-1961: Fix Contact Details On Webform Not Being Pre-filled With Add Case Button on Actions Menu 

---

CRM/Civicase/Hook/Helper/CaseTypeCategory.php

When creating a case for a case type category, the case type dropdown lists the case types belonging to the relevant case category. The function for fetching these case types will currently return `25` case types by default (i.e the default limit for civicrm api calls), this is not an issue for sites that don't have much case types but for sites that have a lot of case types, this will result in unexpected behaviour as not all case types will be present in the dropdown. 
The `getCaseTypesForCategory` function is modified to return only active case types and also to return all case types for the concerned case category.
**Affected screen**

CPS-390: Remove Limit restrictions And Fetch Only Active Case Types

---

ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/services/cases-utils.service.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/case/services/cases-utils.service.spec.js

"Create Email" Activity did not work for "Application Management" instance, and there was console errors.
In `ang/civicase/case/details/directives/case-details.directive.js`, `CasesUtils.getAllCaseClientContactIds` function was called to fetch client IDs for a case. But the `CasesUtils.getAllCaseClientContactIds` function relies on a string called `Client` to be present in the `caseObject.contacts` array. Now due to word replacement, this word gets translated to Member(for NEU), or Applicant(for Awards), so the logic did not work in all cases.
Now this `CasesUtils.getAllCaseClientContactIds` function has been removed, instead in `ang/civicase/case/details/directives/case-details.directive.js`, the client ids are fetched from the `caseObject.client` array.

RSE-1528: Create Email did not work for Application Management instance

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

This pr fixes the issue with display of custom fields and form fields with select multiple enabled in case reports. When the fields that have multiple values were loaded in report the column displayed the ids mixed with some weird characters, This pr fixes the issue for all the custom fields and form fields with select multiple enabled and displays multiple label separated by a | character.
Multiple values for theme were shown incorrectly
All the values are displayed correctly
The alterFromOptions function in class CRM_Civicase_Form_Report_BaseExtendedReport is responsible for changing option ids with option labels. Previously it only cater for single values now it has been modified to work with mulitple options as well.

BASW-638: Pivot Report Bug Fix

---

CRM/Civicase/Hook/alterAngular/AngularChangeSet.php
civicase.php
templates/CRM/Civicase/ChangeSet/CaseTypeCategory.html

This PR exposes the Case Type Category field on the Case Type create/edit screen. The field is exposed with the name `Instance`. 
This Case Type Category field is not part of the create/edit screen.
The Case Type Category field is now part of the create/edit screen with the field name `Instance`. Only users with the `Administer CiviCRM` or `Administer CiviCase` permission can view this field. 
- A new Angular ChangeSet was created for the case category field and injected into the core `~/crmCaseType/caseTypeDetails.html` angular template via the `civicrm_alterAngular` hook.
```php
if (CRM_Core_Permission::check([['administer CiviCase', 'administer CiviCRM']])) {
$angular->add(CRM_Civicase_Hook_alterAngular_AngularChangeSet::getForCaseTypeCategoryField());
}
```
If the …

RSE-1543: Expose Case Category Field On Case Type Create/Edit Screen

---

.github/workflows/backstop.yml
.github/workflows/unit-test.yml

Recently, creating a Drupal site with civibuild step with the github unit tests workflow was failing and as a result, unit tests were not being ran. 
The issue described above exists
Because the command to create the drupal site was ran without specifying the drupal version to build the site with i.e `civibuild create drupal-clean --civi-ver 5.28.3 --web-root $GITHUB_WORKSPACE/site`, civibuild will pull from the [Drupal 7.x master](https://github.com/civicrm/civicrm-buildkit/blob/a44e322faf6d3bc21fbc178d44da2fd078e7ae55/app/config/drupal-clean/download.sh#L7) branch.
The Civibuild site creation was [failing](https://github.com/civicrm/civicrm-buildkit/blob/7461255fc26317979c3261e9318d60bbb88bfcd0/src/civibuild.lib.sh#L1051) at the point where a patch for mysql 8 is to be applied for the …

CPS-397: Fix failing Drupal Build For Unit Test Workflow

---

info.xml

- Case category field is now available on the case type create/edit screen https://github.com/compucorp/uk.co.compucorp.civicase/pull/640
- Fixed issue with the number of case types being limited to 25 on the case creation form https://github.com/compucorp/uk.co.compucorp.civicase/pull/636
- Fixed issue with Add case button on contact actions not pre-filling form values when the case creation form isa webform https://github.com/compucorp/uk.co.compucorp.civicase/pull/638
- Fixed Client role not visible on bulk emails https://github.com/compucorp/uk.co.compucorp.civicase/pull/637
- Fixed issue with Email actions not working properly for a case on manage cases screen https://github.com/compucorp/uk.co.compucorp.civicase/pull/639
- Fixed case activity pivot report issue where multi-value …

CPS-397: Release v1.9.7

---

ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.js
ang/test/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.spec.js

This PR fixes a regression issue related to case linking. 
The https://github.com/compucorp/uk.co.compucorp.civicase/commit/f89b7c8331833acd4f156f2ecfcfa83e4ad5dd01 commit changed the `LinkCasesCaseAction`'s `doAction` return value from an object to a promise that resolves to an object. This works for case actions, but we were also using this service directly in the `civicaseCaseDetailsLinkedCasesTab` directive and this usage was not updated. This issue was not caught by tests because we were mocking the `LinkCasesCaseAction` in this directive.
To fix the issue we have updated `civicaseCaseDetailsLinkedCasesTab` so it uses the `LinkCasesCaseAction` service's return value as a promise that needs to be resolved.
For testing, we are not mocking the service anymore, but using it directly. If …

CATL-1981: Fix case linking

---

CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCases.php
ang/civicase/case/actions/services/email-case-action.service.js
ang/test/civicase/case/actions/services/email-case-action.service.spec.js
civicase.php
tests/phpunit/CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCasesTest.php

This pr adds the functionality for attaching the bulk email as an activity to all the selected cases. There exists a feature through which a user can send bulk emails to different case roles in multiple cases. This pr attaches this email sending as an activity to all the selected cases.
Previously if user had selected only one case then the activity got recorded successfully against that case but if user selected more than one case then this email sending was not attached to any of the case.
AS described above now the activity is attached to all the selected cases.
This pr utilizes the post process hook in file `CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCases.php` and checks if there are multiple cases that has been selected for bulk emailing then loops over all the selected …

RSE-1442: Add Bulk Email Activity To All The Selected Cases

---

tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomFieldExtendsTest.php

This PR adds more test cases for the Case Type Category creation, in particular here for `CaseCategoryCustomFieldExtends` class.
There were no tests for this class.
Added new unit tests for `create` and `delete` methods of `CRM_Civicase_Service_CaseCategoryCustomFieldExtends`, covering all the basic scenarios.
There was no need to add a fabricator for this class, because it will probably not be used in other places. Therefore, the creation of the instance was delegated to a private method of the Test class itself.

CPS-406: Add tests for CategoryCustomFieldExtends class

---

ang/civicase-base/providers/case-type.provider.js
ang/civicase/case/list/directives/case-list-table.directive.js
ang/test/civicase-base/providers/case-type.provider.spec.js
ang/test/civicase/case/list/directives/case-list-table.directive.spec.js
ang/test/mocks/data/cases-types.data.js

This PR fixes some issues found for case actions:
* Convert Prospect actions were breaking because the case category parameter was not being included in the cases passed to the action.
* Email case roles were breaking when there were case types without a definition.
The convert to prospect action was failing because it required the `case_type_id.case_type_category` property to be included in the case object. This action was working in other areas such as the contact's cases tab because the property is included there. This action was only breaking in the manage cases page so we updated the `case-list-table.directive.js` directive so it requests the parameter required by the action.
In terms of the email action, the issue happens when there are some case types without a definition object. …

RSE-1570: Fix case actions

---

info.xml

- Add Workflow list new columns and filters support https://github.com/compucorp/uk.co.compucorp.civicase/pull/644
- Log email as an activity on cases sent via bulk email feature https://github.com/compucorp/uk.co.compucorp.civicase/pull/653
- Fixed Linked cases button not working on manage case screen https://github.com/compucorp/uk.co.compucorp.civicase/pull/649
- Fixed Console error thrown when attempting to send a bulk email https://github.com/compucorp/uk.co.compucorp.civicase/pull/660

CPS-413:  Release v1.9.8

---

CRM/Civicase/APIHelpers/CaseDetails.php
CRM/Civicase/Api/Wrapper/CaseList.php
tests/phpunit/api/v3/Case/GetcaselistTest.php

When searching for cases where a contact has a particular case role, No results are returned. There is actually a db syntax error when performing this search. 
The `$where` variable here is set empty and is returned empty at the end of the function if `$canBeAClient` is false which is the case here because the contact search is for a user with a particular role and not for a client.
This causes an issue [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/APIHelpers/CaseDetails.php#L280) as a query condition is formed for a WHERE clause with an empty string which triggers an error when the query is ran
```sql
AND case_relationship.relationship_type_id IN ("66")
WHERE () //Syntax error is thrown here
GROUP BY …
```

CPS-391: Fix Issue With Search By Case Roles Not Returning Results

---

api/v3/Case/Getdetails.php

One of the query in file `api/v3/Case/Getdetails.php` was using 'grouping' which is a reserved keyword in Mysql8 so this query was resulting in an error. So this pr backticks the 'grouping' word which will allow to run the same query without errors on mysql8. 
The above issue existed.
This pr modifies the query and uses backticks to make this query compatible with mysql8.
Query has been modified to this
$query = "SELECT COUNT(a.id) as count, ca.case_id
FROM civicrm_activity a, civicrm_case_activity ca
WHERE ca.activity_id = a.id AND a.is_current_revision = 1 AND a.is_test = 0 AND ca.case_id IN (" . implode(',', $ids) . ")
AND a.activity_type_id IN (SELECT value FROM civicrm_option_value WHERE \`grouping\` "
. $categoryCondition . " AND option_group_id = (SELECT id FROM …

CPS-414: Fix Mysql8 Reserved Word Issue

---

ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.js

When deleting an activity on the files tab the activity list is not refreshed giving an impression that the activity is was not deleted while it got deleted in actual.
The above bug existed.
Now when an activity is deleted the activity list gets refreshed immediately and the deleted activity is removed from the list.
Upon deleting an activity an event was fired by the name of 'civicase::activity::updated' but there were no listeners for this event on the files directive. So function for refreshing activities was attached as a listener for the mentioned event.

RSE-1345: Fix Delete Activity Bug

---

CRM/Civicase/Test/Fabricator/CaseCategoryInstance.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryInstanceTest.php

This PR adds more test cases for the service that deals with Case Category Instances. The mentioned service currently has two main tasks: 
1.- Return the list of category instances available, in a specific format. Method: `getCaseCategoryInstances`
2.- Create a category instance for every category that is not associated with one. Method: `assignInstanceForExistingCaseCategories`
The goal is to tests these functionalities, with all the possible variants.
There were no unit tests for this class. Also, `CaseCategoryInstance` did not count with a fabricator, that was necessary for these tests.
Three tests were added, covering all the possible usages. The method `createInstanceTypeFor` is also tested, indirectly, on the tests provided, given 100% of code coverage.
Require special mention the …

CPS-407: Add tests for CaseCategoryInstance class

---

CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js
ang/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.js
ang/test/civicase/activity/activity-forms/services/draft-email-activity-form.service.spec.js
ang/test/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.spec.js

This issue fixes the wrong client id issue while opening the email/pdf form when user resumes the saved draft.
Previously the contact id of the activity creator was being sent as client contact id to the email or pdf form which resulted in multiple errors.
The client id is sent to the email or pdf form
`getActivityFormUrl` function in `ang/civicase/activity/activity-forms/services/draft-pdf-activity-form.service.js` and `ang/civicase/activity/activity-forms/services/draft-email-activity-form.service.js` was responsible for creating the link and parameter for pdf and email forms while resuming draft. Both of these function were sending assignee or source id which refers to creator of activity instead of target id which refers to client id. This pr fixes this issue

CATL-2016: Fix Issue while resuming draft

---

ang/civicase/activity/factories/view-in-popup.factory.js
ang/test/civicase/activity/factories/view-in-popup.factory.spec.js

This pr fixes the issue with email activity in recent communication block on case summary page. When user clicked on an email activity in recent communication an error was shown to the user.
Previously when user clicked on an email activity in recent communication a request was sent to civicrm to edit the activity but civicrm does not allow editing of an email activity so an error was thrown as shown below.
This pr changes the request from edit to view for email activities in recent communication so now when user clicks on an email activity a view of the activity is opened up in a popup.
`ang/civicase/activity/factories/view-in-popup.factory.js` file is responsible for providing services for either view or update of an activity. This pr introduces a check in `viewInPopup` function which …

CPS-417: Fix Bug With Recent Communication Block

---

CRM/Civicase/Page/ActivityFiles.php
CRM/Civicase/Service/CaseCategoryFromUrl.php
ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
config/urls/case_category_url.php

This PR solves a problem downloading files attached to an activity. It was reported for Awards, because there was visible a permission error, but it is important to note that also exists for other cases.
In some parts of the frontend, the URL for downloading all files, `civicrm/case/activity/download-all-files`, was receiving the param `activity_id` and in other places was receiving an array named `activity_ids`.
This causes 404 error in some cases, and permission denied in others (in particular, in awards, the permission error did not exist on Cases because of the underlying logic)
The ticket attachments describe the incorrect behaviour: https://compucorp.atlassian.net/browse/RSE-1376, in all the different cases: Files tab activity, Calendar Activity, and Activity Tab.
After pressing the …

RSE-1376: Fix Bug Downloading All Files On Awards

---

ang/civicase-base/providers/workflow-list-action-items.provider.js
ang/test/workflow/directives/workflow-list.directive.spec.js
ang/workflow/directives/workflow-list.directive.js

As part of this PR, support for instance specific Action Items in Workflow List is added.
This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/167
There are no UI changes for Edit Workflow page(for Case Management instance).
In `ang/workflow/directives/workflow-list.directive.js`, a check is added to only show instance specific Action Items.

RSE-1600: Support for instance specific Action Items

---

CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php

Administer -> civicase -> civicase webforms this menu item was only visible for compucorp admin and not any other user. This was due to the fact that a deprecated permission was being used for this menu item. 
In file `CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php`  the above mentioned menu item was added with a permission of `access CiviCase` which has been deprecated so as a result this menu item was not visible to any user other than the default admin user.
This pr replaces deprecated permission by `access all cases and activities` which fixes the above mentioned issue

CPS-403: Fix Deprecated Case Permission

---

CRM/Civicase/Service/CaseCategoryFromUrl.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryFromUrlTest.php

This PR adds unit tests for the functionality provided by the service `CaseCategoryFromUrl`, that is, basically, to detect the category name from a given Url / Request.
At this moment there are 4 types of URLs that can be used in the class: 
- Url containing information about a Case.
- Url containing information about an Activity.
- Url containing information about a Category.
- Url requested by an Ajax call.
There were no tests for this Service.
We added tests for all the different cases in which the service can detect a category name. 
This service interacts with a static method of `CRM_Utils_Request` class, that therefore can't be mocked.
For removing this limitation, the usual path is to create appropriate interfaces and wrap the static method, but for this particular case that would …

CPS-409: Add tests for CategoryFromUrl class

---

ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html
ang/civicase/case/factories/get-case-query-params.factory.js
ang/test/civicase/case/factories/get-case-query-params.factory.spec.js

In the Case Details section, the Custom Groups were not displayed in order of their "weight". This PR fixes that.
In `ang/civicase/case/factories/get-case-query-params.factory.js`, added 'custom_group.weight'` so that the weight is fetched in the frontend.
In `ang/civicase/case/details/summary-tab/directives/case-summary-custom-data.directive.html`, added sorting
`ng-repeat="(index, customGroup) in customData | orderBy: 'weight'"`

CPS-366: Fix Custom Group Ordering

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

This PR fixes a bug where roles cannot be reassigned after updating the date for the existing role.
The problem is that we changed the model for the start date from `role.start_date` to `role.relationship.start_date` (same for end date) in this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/581 but other uses for the start date were not updated. This PR fixes all other references to the date.

CATL-2031: Use date fields stored inside of relationship object

---

ang/civicase-base/directives/inline-datepicker.directive.js
ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
ang/test/civicase-base/directives/inline-datepicker.directive.spec.js

This PR adds minimum and maximum date limits to the inline date pickers for
case roles.
The `inline-datepicker.directive.js` directive now adds support for `min-date`
and `max-date` properties. These values are watched in case their values change.
The `roles-tab.directive.html` template was updated so it uses the new inline
datepicker features.

CATL-2030: Add date range limits to role inline date pickers

---

ang/civicase/case/search/directives/search.directive.html

This PR updates the label for the new filter for disabled cases.
The reason for changing the label is that this makes it more explicit to the user that **only** disabled cases will be displayed instead of both enabled and disabled cases.
This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/178
The `ang/civicase/case/search/directives/search.directive.html` template was updated. No other changes to the code were needed.

RSE-1627: Update disabled cases filter label

---

api/v3/Case/Getstats.php

This PR fixes an issue where disabled cases are not properly represented on the cases dashboard stats.
The issue happened because `Case.getstats` doesn't automatically use filters related to case types. They need to be manually added. This is the reason we added the `is_active` parameter to the `$caseTypesParams` filters.
Also, all filters related to case types were moved to a `_civicrm_api3_case_getstats_get_case_types` function to avoid splitting blocks of related code and instead have them in a single function. More refactoring needs to be done on this function, but this is an improvement.

RSE-1625: Fix disabled cases stats

---

ang/civicase/dashboard/directives/dashboard-tab.directive.js
ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
api/v3/Activity/Getcontactactivitiescount.php

In the Case(or any other Instance) Dashboard, the milestone activities were not shown. This PR fixes that.
This is caused by https://github.com/compucorp/uk.co.compucorp.civicase/pull/551/files#diff-e944ee6f08041bf15a7bf9bd1680b6a516d69c0973b4f9e59f0d53f099a2db0cR536, when we first introduced a `modified_date` filter. But internally the issue with Date filter was always present.
In `ang/civicase/dashboard/directives/dashboard-tab.directive.js`, only for `Milestone` block, the start time was added as the Current Date and Time of the system. But for other blocks, the Start time of the Week(or the selected date filter) is considered. And because of this, all the activities, before the current time, was not shown. 
Tried to go back in Git history, but could not find any reason of this …

RSE-1565: Fix logic for showing Milestone Activities

---

CRM/Civicase/Service/CaseRoleCreationPostProcess.php
ang/civicase-base/directives/inline-datepicker.directive.js
ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase-base/directives/inline-datepicker.directive.spec.js
ang/test/civicase/case/details/people-tab/directives/case-details-people-tab.directive.spec.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js
tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPostProcessTest.php

This PR fixes an issue where reassigning or removing a case role would not add the end date for the past case role.
The issue was introduced by this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/626. The assumption was that the https://github.com/civicrm/civicrm-core/pull/18844 core PR was going to fill the end date when passing `is_active: 0`. This assumption not only was wrong, but this core PR won't be accepted so we need to remove this implementation.
* CATL-2031: Use date fields stored inside of relationship object #677
* CATL-2030: Add date range limits to role inline date pickers #685

CATL-1948: Fix missing end dates

---

ang/test/workflow/crm/case-type.controller.spec.js
ang/workflow.ang.php
ang/workflow/crm/case-type.controller.js
ang/workflow/crm/override-case-type.config.js
templates/CRM/Civicase/ChangeSet/CaseTypeCategory.html

When clicked on the Save or Cancel button, in the New/Edit Case Type screen, the browser redirects to the Core Case Type List screen. This has been changed to redirect to the New Manage Workflow screen for each Case Type Category. But while creating a new Case Type, if Cancel is pressed, the old functionality still remains, as the Case Type Category cannot be determined at this stage.
No UI Changes.
1. In `ang/workflow.ang.php`, core module `crmCaseType` is added as a dependency, so that the functionality can be overridden.
2. In `ang/workflow/crm/override-case-type.config.js`, the core route `/caseType/:id` has been edited, to assign a new controller `CivicaseCaseTypeController`.
3. A new controller `CivicaseCaseTypeController` has been created. This controller extends the core …

RSE-1295: Override Case Type core screen functionality

---

CRM/Civicase/Hook/BuildForm/CaseCategoryCustomGroupDisplay.php

In this PR https://github.com/compucorp/uk.co.compucorp.civiawards/pull/183, Some tests were added for the Award payments form. The Form tests calls some form hooks already added in the civicase extension and the tests was throwing some errors due to some non existent variables in the hooks. This PR fixes that.

ACU-489: Fix issues with Failing Form Tests

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

This pr adds contact reference custom fields to the column header on the pivot reports. Secondly, it removes the options from columns which are not used yet.
Previously the contact reference custom fields were available only in the rows header not in the column headers.
Now the contact reference fields are available in the column headers. Also the unused columns are removed now.
This pr makes a number of changes to the file ` CRM/Civicase/Form/Report/BaseExtendedReport.php` in order to remove the unused column values and also to include all the custom fields that are of type contact reference.
Note: There is a linter issue in this pr which is due to the fact that the code style is from an imported class from an external extension and we would not want to change that file.

CATL-1387: Add Contact Reference Fields To Column Header

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/ExtendedReport.php
phpcs-ruleset.xml

This pr removes a bug from pivot report that resulted in an out of memory error which happened when any custom field of type contact reference was selected as row header in the pivot report.
If a contact reference type custom field was selected as a row header in the report an error was thrown due to the fact that number of contacts were more than the memory limit.
This pr restricts the rows to only those contacts which has been used atleast once.
This pr makes a number of changes to the file ` CRM/Civicase/Form/Report/BaseExtendedReport.php` in order to remove the unused row values.
Note: There is a linter issue in this pr which is due to the fact that the code style is from an imported class from an external extension and we would not want to change that file.

CATL-2082: Restrict Rows To Only Used Options

---

ang/civicase/shared/directives/ui-date-range.directive.html
ang/civicase/shared/directives/ui-date-range.directive.js

This PR fixes the following issues on the date range directive:
* The placeholders are now visible.
* Provide a way for people implementing the range directive to listen to change events. These can be used to trigger events when the dates change.
This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/186
For change event listener example please check the implementation on https://github.com/compucorp/uk.co.compucorp.civiawards/pull/186
* Fixed lint issues. The change to `enforceTime` was suggested by the linter and has the same result.
* Placeholders no longer use the `ts` service since the underlying `crm-ui-datepicker` does not support dynamic placeholders. If we want to fix this we'd need to fix the core service which would put this ticket out of scope.
* …

ACU-494: Update date range directive

---

ang/civicase-base.ang.php
ang/civicase-base/directives/paging.html
ang/civicase-base/directives/paging.js

This PR adds a pagination component that should be used throughout civicase and other extensions.
This PR is part of https://github.com/compucorp/uk.co.compucorp.civiawards/pull/188
```html
<civicase-paging
paging-data="{ page: 3, pageSize: 25, total: 100, isDisabled: false }"
paging-action="myPageChangeHandle($page, $pageSize, $total)"
></civicase-paging>
```
There are two reasons for creating this component:
1. Creating pagination is too verbose because of all the default parameters that need to be filled. An example of this is https://github.com/compucorp/uk.co.compucorp.civicase/pull/692/files#diff-fe4606fd0c0d06a47f3fb4a80357d9705ffd57497f09e468a4db14ed8e0f8b73R82-R97 where adding the properties text-first, text-last, text-next, etc must always be done when implementing pagination. …

ACU-495: Add civicase paging component

---

CRM/Civicase/Hook/BuildForm/TokenTree.php

This pr removes the case role count from the token tree so if before if it was `Case Role 1 "Role Name"` no it is changed to `Role Name`
The role count existed
The role count is removed
` CRM/Civicase/Hook/BuildForm/TokenTree.php` file was handling the logic for role count in token tree so it is removed from this file.

CATL-2093: Remove Case Role Count From Token Tree

---

CRM/Civicase/Hook/BuildForm/LinkCaseActivityDefaultStatus.php
civicase.php

This pr changes the default status for link case activity from `schedule` to `completed`.
The default status for link case activity was `scheduled`.
The default status is changed to `completed`.
This pr adds a new build form hook in `CRM/Civicase/Hook/BuildForm/LinkCaseActivityDefaultStatus.php` which changes the default status for link case activity.

CATL-2095: Change Default Activity Status For Link Case

---

CRM/Civicase/Service/CaseRoleCreationPreProcess.php
ang/civicase/case/factories/get-case-query-params.factory.js
ang/test/civicase/case/factories/get-case-query-params.factory.spec.js
tests/phpunit/CRM/Civicase/Service/CaseRoleCreationPreProcessTest.php

This PR solves the problem observed while trying to update many consecutive times the relationships of a given case, using webforms.
Despite the problem occurs only when a webform is used, the error is related to the Pre and Post processes performed for the CaseRoles on the CiviCase package.
**UPDATE:**
This PR also contains the fix for another problem found during QA testing, related to People tab on Case view not showing the relationships correctly (despite they were correctly stored).
On the People tab of a given case, we can see the relationships with contacts. Example.: Case Manager, PI CaseWorker, etc
For a particular customer, these relationships can be changed using WebForms, like here:
Before this change, a given contact can't be reassigned twice. In other words, having two …

CATL-2096: Add Default Value To Relationship Id

---

CRM/Civicase/Hook/BuildForm/TokenTree.php

This pr renames client tokens to email recipient and change the case client role order in the token tree.
Client token were available twice
The client tokens has been reamed to email recipient and case client role token has been moved to second spot in the token tree.
The token tree hook in `CRM/Civicase/Hook/BuildForm/TokenTree.php` has been modified to achieve above defined results.

CATL-2105: Change Client Token To Recipient

---

CRM/Civicase/Hook/alterAngular/AngularChangeSet.php
civicase.php

This PR changes the Case Type listing page, URL: `civicrm/a/#/caseType` hiding the New Case Type button that appears at the end of the listing.
We do this because the preferred way to create case types is using the specific workflow, for example in Awards would be using `Create New Award`.
The button for creating a new Case Type is accessible on the Case Type listing page:
The button was removed from the view:

RSE-1551: Hide New Case Type button on Case Type list

---

ang/civicase/case/details/people-tab/services/people-tab-roles.service.js

This pr fixes a bug which caused the client role to disappear from peoples tab on any site that has a word replacement for client role. 
The client role was not visible on peoples tab
The client role is visible
This pr fixes a glitch in file ` ang/civicase/case/details/people-tab/services/people-tab-roles.service.js` due to which the client role was not appearing

CATL-2119: Fix Client Role Display On Peoples Tab

---

CRM/Civicase/Upgrader/Base.php
civicase.civix.php
civicase.php
phpcs-ruleset.xml

This PR fixes is to updates civix file and an upgrader base class.  The base class and civix file are generated automatically by running `civix generate:upgrader
`
The reason for regenerating the civix file and base upgrader class because CiviCRM changed the way they handle warning for using a deprecated function.  See this [PR ](https://github.com/civicrm/civicrm-core/pull/19256).
The changed will always throw use deprecated warning if the deprecated function is used in anywhere, for example, Drupal module, CiviCRM extension. This would not have an issue we install the extension / module via user interface. However, when we use Drush site-install command to install the Drupal site that ship with a Drupal profile that install the extension when creating a site. 
Any module or extension …

COMCL-101: Regenerate civix file and Base upgrader class

---

.github/workflows/release-pr.yml

Using correct Release PR Github Action version v1.0.0.

CPS-464: Use Correct Release PR Github Action version

---

CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php
CRM/Civicase/Hook/PostProcess/HandleDraftActivity.php
civicase.php

When sending a Draft Email, a duplicate activity was being created, but still the original draft activity was not deleted. This PR fixes that problem.
Draft Email Activity was not getting deleted.
Draft Email Activity is now getting deleted.
In https://github.com/compucorp/uk.co.compucorp.civicase/pull/629, the code to delete the activity was wrongly removed. 
@tunbola Pointed that
> Are we sure we can do away with this code? I think this deletes the draft activity right? Don't we still need to delete it at some point?
But I replied with 
> Yes, it is not required anymore. Because deletion of Activities are done seprately. But here once we want to move the Activity from Draft to Completed. It should not delete the activity, instead it should just change its status.
I think I misunderstood …

CATL-2136: Delete Draft Email when sending email

---

ang/civicase/case/actions/services/email-case-action.service.js
ang/test/civicase/case/actions/services/email-case-action.service.spec.js

"Email - Send Now" case action is now visible only on the Bulk Action, not anywhere else.
In Case Summary Page
In Contact Case Tab
In Case Summary Page
In Contact Case Tab
Added `isActionAllowed` function to `EmailCaseAction` to implement this.

CATL-2137: Show "Email-Send Now" case action only in bulk action

---

ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/search/directives/search.directive.spec.js

The Order of the filters in Manage Cases page and Dashboard was different. Now they have been aligned.

CATL-1442: Fix Case Filter order

---

ang/civicase/case/details/people-tab/directives/roles-tab.directive.html
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

In the Peoples tab of Case Summary, if we
1. Assign a Contact to a Role.
2. Assign another Contact to the same role,
3. Assign back the Contact from Step 1 to the same role again.
4. Click "Display previous case role assignments" checkbox.
It did not show 3 Roles in total. Instead it skipped the Role from Step 1. This PR fixes that issue.
**Note:** This issue still exists for Cases with Multiple clients. But thats hard to fix as the logic is very complex. For the time being and because of time constraints, we have fixed it, only when "Allow Multiple Case Clients" is set to Single Client.
Also the dropdown menu was visible for Inactive Roles as well, it has been removed now.
1. In `ang/civicase/case/details/people-tab/directives/roles-tab.directive.html` hiding the dropdown menu when the …

CATL-2139: Show All Relationships in People's tab

---

ang/civicase/case/actions/services/print-merge-case-action.service.js
ang/test/civicase/case/actions/services/print-merge-case-action.service.spec.js

"Print Merge document" case action is now visible only on the Bulk Action, not anywhere else.
Added `isActionAllowed` function to `PrintMergeCaseAction` to implement this.

CATL-2143: Show print merge case action only in bulk action

---

CRM/Civicase/Hook/BuildForm/LimitRecipientFieldsToOnlySelectedContacts.php
CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
js/restrict-email-contacts.js

When sending an email with CC and BCC field, in NEU site, the CC and BCC emails were not sent, this PR fixes that issue.
In `js/restrict-email-contacts.js`, when assigning the `data` for each dropdown element, we were assigning the Contact ID, but should be the Email ID(email_id field in Contact API). It worked before, because in most cases the `contact_id` and `email_id` is same. But for NEU, its not the same, hence the issue was found on NEU.

CATL-2140: Fix CC BCC field

---

CRM/Civicase/Event/Listener/CaseRoleCreation.php
tests/phpunit/api/v3/CaseRoleCreationTest.php

This PR makes that when a webform is sent with relationships information for a Case, the relationship is not recreated if it was not modified.
When using a WebForm for updating relationships for a Case, even when the relationship was not modified (I mean, it continues being between the same contacts, and type, case, etc), it was being recreated, causing problems for identifying the past roles.
If a relationship is not modified, then it is not recreated.
As we can see on the webform_civicrm extension, the relationships selected are being sent without the identifier:
https://github.com/compucorp/webform_civicrm/blob/7.x-5.1-patches/includes/wf_crm_webform_postprocess.inc#L1297
That is the same if the relationship is new or if it didn't change.
These changes identify on the hook that is …

CATL-2142: Do Not Recreate Existent Relationships

---

tests/phpunit/CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCasesTest.php
tests/phpunit/CRM/Civicase/Hook/SelectWhereClause/LimitCaseQueryToAccessibleCaseCategoriesTest.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomDataTypeTest.php

This PR adds unit tests for the `CaseCategoryCustomDataType` class.
This class has only two public methods, that creates and deletes the required `OptionValues` for `CustomDataType` groups. Both methods have been fully tested.
Also, this PR provides a fix to two relatively minor problems on other unit tests, that caused warnings, or errors if we run them more than once.
There were no unit tests for `CaseCategoryCustomDataType` class.
The tests for `AttachEmailActivityToAllCases` were throwing a warning:
The tests for `LimitCaseQueryToAccessibleCaseCategories` thrown errors if we run them more than once (not visible on GitHub hooks since they run only once)
Tests added for `CaseCategoryCustomDataType`, which covers all possible usages.
All the suite runs correctly, without warning or …

CPS-478: Add tests for CaseCategoryCustomDataType class

---

.github/workflows/backstop.yml

The shoreditch branches does not include the CSS files. So this PR generates them before running the Backstop tests so that backstop can use the compiled CSS.
Not needed
Added the following steps before running Backstop test
```
npm install
npx gulp sass
```

CPS-393: Generate CSS files

---

CRM/Civicase/Service/CaseCategoryInstance.php
CRM/Civicase/Service/CaseCategoryMenu.php
CRM/Civicase/Test/Fabricator/CaseCategory.php
CRM/Civicase/Test/Fabricator/CaseCategoryInstanceType.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryInstanceTest.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php
tests/phpunit/CRM/Civicase/Service/CaseTypeCategoryEventHandlerTest.php

This PR has the main purpose of adding unit tests for CaseCategoryMenu service class, but also adds refactorings to other related entities. 
It is important to mention that related changes will not require extra QA manual testing, since are just improving readability, or applies only to other unit tests code.
There were no unit tests for this service.
All the public methods were tested, both for creating and deleting menus. 
- A fabricator for `CaseCategoryInstaceType` was added, since the action was required not only on these tests but also on the CaseCategoryInstance tests. Commit: https://github.com/compucorp/uk.co.compucorp.civicase/commit/e17979d91f4a845cbb8129a08262dda43bfd7a3f
- The method for generating random names on `CaseCategory` fabricator was replaced, since uniqid output …

CPS-477: Add Tests for CaseCategoryMenu class

---

CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php

Moved from https://github.com/compucorp/uk.co.compucorp.civicase/pull/593
This PR changes the "Save Draft" button for Email and PDF Letter activity forms from input elements to button elements. The reason for the change is that Core is moving away from input elements and Shoreditch styles break for these type of elements.
Note: this PR depends on https://github.com/civicrm/org.civicrm.shoreditch/pull/492
We changed the button type from `submit` to `xbutton`.
https://github.com/compucorp/backstopjs-config/actions/runs/636368203
Some artifacts were found, but manually confirmed that no actual regressions were introduced.

CPS-480: Change button markup

---

ang/civicase/case/details/people-tab/directives/roles-tab.directive.html

In Peoples Tab, the pagination was broken for the Case Roles sub tab. This PR fixes that.
In https://github.com/compucorp/uk.co.compucorp.civicase/pull/574, the Peoples tab html was refactored and moved into partials. But in Angular when a partial is created, it creates a Child Scope, so the properties changed in the partial cannot be used by the parent Controller.
Now using `$parent.rolesPage` instead of `rolesPage` to fix this issue.

CPS-495: Fix People Tab pagination

---

CRM/Civicase/Event/Listener/CaseCustomFields.php
civicase.php

Recently we had an issue on one of our client sites when we have multiple Custom field sets enabled for the Case entity:  `Mysql can only use 61 tables in a join`. This error made the award review screen unusable and also affected some parts of the cases extensions screen, e.g when saving a case data on the manage cases screen, an error occurs. The temporary fix for this error is to disable some custom field sets to bring the number of enabled custom field sets down to be below 61.
By default Civicrm will join to all custom field tables for an entity (Even those that are not necessary) in order to return all the custom fields for that entity in the case where specific return parameters are not passed in the Entity.get API parameters.  This can cause …

ACU-540: Restrict Default Custom Fields Load For Case.Get API

---

CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php

When creating an Email activity and marking as draft, rather than a draft activity being created, the email is sent out.
The code works fine on sites running civicrm 5.28 but something seems to have changed in civicrm 5.35. The issue is because the code [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php#L37) does a return and the `CRM_Civicase_Hook_ValidateForm_SaveActivityDraft` class responsible for handling the draft activity logic is not executed because the `fields` variable does not contain the `button` key. The fields variable is populated via POST and the save draft button is not part of the form values submitted when the save draft button is clicked.
This is fixed by setting the button to be of type …

CPS-525: Fix Marking an email as save draft sends out the email

---

CRM/Civicase/Service/CaseCategoryMenu.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryMenuTest.php

This PR modifies the name and label of the navigation menu created for a new Case Type Category.
For the case category menus created, the name of the category is used as a label. Then, when we generate a menu using 'awards' as a name, this is the result:
Now the case category name is firstly changed to lowercase completely, and later capitalized the first letter.

CPS-487: Capitalize Category Name on Label Menus

---

ang/civicase/case/details/summary-tab/directives/case-summary-recent-communications.directive.html
ang/civicase/case/details/summary-tab/directives/case-summary-tasks.directive.html

The "View All" links for Recent Communication redirected the user to the Activity Feed but only showed the Completed Activities. This PR fixes that to show all.
Removed the `statusType: 'completed'` filter from HTML.

CPS-494: Fix View All links

---

CRM/Civicase/Hook/BuildForm/TokenTree.php
js/token-tree.js
tests/phpunit/CRM/Civicase/Hook/BuildForm/TokenTreeTest.php

The Case Token + and - Icons was not working on RSE site. This PR fixes that issue.
When the email activity form is opened for a case, the token list is not properly displayed as one of the token category displays “Undefined“  instead of the token category.
RSE site is using FontAwesome v5(needed in SSP), but `fa-minus-square-o` and `fa-plus-square-o` classes were not supported on v5. Hence removed `-o`, which is compatible with both v4 and v5.
- The logic for initializing the Email Recipient Tokens [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Hook/BuildForm/TokenTree.php#L324) checks if the the token tree contains the `Email Recipient` key before it is intialized and the core field tokens added. However for this client, some custom fields for the …

RSESPRT-36: Fix Case Tokens icons

---

ang/civicase-base/filters/escape-string.filter.js
ang/civicase/case/card/directives/case-card-contact-record.directive.html
ang/civicase/case/card/directives/case-card-dashboard.directive.html
ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
ang/civicase/case/details/summary-tab/directives/case-summary.directive.html
ang/civicase/case/factories/format-case.factory.js
ang/civicase/shared/directives/crm-editable.directive.js
ang/test/civicase-base/filters/escape-string.spec.js
ang/test/civicase/case/factories/format-case.factory.spec.js

This PR fixes an issue where special characters such as &, <, >, etc. would not be properly displayed when present in the Case subject.
<table>
<tr>
<th>Area</th>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<th>Dashboard</th>
<td><img src="https://user-images.githubusercontent.com/1642119/112220096-3d378400-8bfc-11eb-9aaf-6875353665e0.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/112217652-2b081680-8bf9-11eb-9962-785cb21e445a.png" /></td>
</tr>
<tr>
<th>Contact Details</th>
<td><img src="https://user-images.githubusercontent.com/1642119/112220259-6eb04f80-8bfc-11eb-881e-99c3f5605fff.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/112217661-2cd1da00-8bf9-11eb-9bcd-f6b3885dec39.png" /></td>
</tr>
<tr>
<th>Case Details</th>
<td><img …

CPS-39: Fix special characters in case subjects

---

ang/civicase/activity/card/directives/activity-card.directive.js
ang/test/civicase/activity/card/directives/activity-card.directive.spec.js

Fix Case Link in Activity Card.
Link was not working.
In `ang/civicase/activity/card/directives/activity-card.directive.js`, the `case_type_category` has been changed to VALUE from Name.

CPS-572: Fix Case link in Activity card

---

ang/civicase/case/directives/case-overview.directive.js
ang/test/civicase/case/directives/case-overview.directive.spec.js

This PR fixes the sort order of the case statuses displayed on dashboards.
Previously we were displaying these statuses by the order they were created instead of their weight value as defined in the admin area.
This fixes https://github.com/compucorp/uk.co.compucorp.civicase/issues/559
Won and Lost have weight 1 and 2 respectively and as such should be displayed before any other status.
Won and Lost are outside of the screenshot because they are the last statuses created in civicase.
When we were working on https://github.com/compucorp/uk.co.compucorp.civicase/pull/427 we sorted the statuses by weight, but indexed the list right after. Indexing removes any sort order. We indexed these statuses because the previous data structure was indexed as well, but was indexed by weight. Indexing by …

CPS-430: Fix Case Statuses sort order

---

CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
phpcs-ruleset.xml

This PR fixes the error on the Case report "Case with activity pivot". The bug was related to the names of some relationship types, that since they contain the hyphen character "-", were causing a database error on a query.
When trying to create a Case report of the mentioned type, an error was displayed on the screen. The query and the error on the database level were this:
The query is correctly parsed, then the report is visible. Screenshot of the developer tag on the report page:
- The problem only reached the relationship types labels. Activity names and other entities were not important.
- The file modified required to be excluded for PHP style checks, since it was an old file with many conflicts, that would require a refactor for solving it.

CPS-261: Fix Error on Case Reports with Hyphen Characters

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Hook/BuildForm/CaseCategoryCustomFieldsProcessing.php
CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForNewCase.php
CRM/Civicase/Hook/BuildForm/FilterCaseTypesByCategoryForNewCase.php
CRM/Civicase/Hook/Helper/CaseTypeCategory.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
CRM/Civicase/Hook/PreProcess/CaseTypeCategoryWebFormRedirect.php
ang/civicase.ang.php
ang/civicase/case/services/add-case.service.js
ang/test/civicase/case/services/add-case.service.spec.js
civicase.php

When trying to add a new case for a case type belonging to a Case management instance, the case type dropdown contains case types from other case categories belonging to other instances.
The the case type dropdown now contains only case types for the case category under consideration
The reason for the leakage is as a result of the validation of the category [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/CRM/Civicase/Hook/BuildForm/CaseCategoryCustomFieldsProcessing.php#L27) where the function expects a case category name but it was the category ID that was passed. Refactoring the `CRM_Civicase_Hook_Helper_CaseTypeCategory::isValidCategory` to expect the category Id fixed the issue.
A couple of issues found was also fixed in the …

CPS-569: Fix Leaking Case Types On Add Case Form

---

CRM/Civicase/Service/CaseCategoryFromUrl.php

When trying to create a case for a case category instance as non admin, the action is not successfully and the broswer gives an error about multiple redirects. Refreshing the page after the failure will give a notice popup about a permission error for the logged in user.
The error was traced to this line https://github.com/civicrm/civicrm-core/blob/master/CRM/Case/Form/Case.php#L118 which means user was being denied access to some functionalities in the case form. The issue was because the hook class responsible for adding appropriate permissions based on case category was getting the case category Id value here: https://github.com/compucorp/uk.co.compucorp.civicase/blob/eca3321348bcef534937dc91f845e82a6d5e6a94/CRM/Civicase/Hook/PermissionCheck/CaseCategory.php#L44 rather than the case …

CPS-571: Fix Issue With Multiple Redirects When Creating A Case Of Another Instance As Non Admin

---

ang/civicase/activity/card/directives/activity-card-short.directive.html

The Add Activity Button in Contact case tab was not working. This PR fixes that.
This is a regression of https://github.com/compucorp/uk.co.compucorp.civicase/pull/678. Where `ng-if` was used. But using `ng-if` is not recommended with Directives(`civicase-dropdown-toggle` in this case). So changed it to `ng-show`.

CPS-512: Fix Add Activity button in Contact Case Tab

---

CRM/Civicase/Service/ManageWorkflowMenu.php
ang/civicase/case/actions/directives/case-actions.directive.js
ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
ang/test/mocks/data/case-category-instance-mapping.data.js
ang/test/mocks/data/case-category-instance-type.data.js

Added Support for CiviProspect extension.
Related to https://github.com/compucorp/uk.co.compucorp.civicrm.prospect/pull/80
In `CRM/Civicase/Service/ManageWorkflowMenu.php`, added a optional parameter called `$parentMenuLabel`, using which the parent menu label can be sent, incase its not same as the Case Type Category name.
Removed `refreshData` function from Case Actions, because its not required by Prospect anymore.
Updated FE mock data.

CPS-554: Changes to support CiviProspect

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

In Pivot Report, when there are more than 50 records to be shown, the UI was showing pagination of 50 records in every page. But this is wrong, since Pivot Report should not have pagination, as it shows grand total at the end of the report.
Also CiviCRM does not show pagination for core reports. Example: `civicrm/report/activitySummary`.
Now the pagination has been removed, so it works correctly.
The `CRM_Civicase_Form_Report_BaseExtendedReport` class overrides `CRM_Civicase_Form_Report_ExtendedReport`, which overrides `CRM_Report_Form`.
Now `CRM_Report_Form` has a logic to only show 50 records at a time, and have pagination. Now this is fine for normal forms. But in Pivot Report, we need to show all the records.
So in `CRM/Civicase/Form/Report/BaseExtendedReport.php`, removed …

CPS-545: Remove Pagination from Pivot report

---

ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.js
ang/civicase/case/details/people-tab/messages.constants.js
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js
ang/test/civicase/case/details/people-tab/directives/case-roles-tab.directive.spec.js
ang/test/civicase/case/details/people-tab/services/people-tab-roles.service.spec.js

In People's tab, if the Client is reassigned to a contact from existing relationships, of the case, no error was shown, and the client was changed. But this is not correct, as client should not be assigned to a contact from existing active roles.
This PR fixes this.
Client was reassigned.
Client is not reassigned.
This logic was completely missing. So added a condition in `promptForContactThatIsNotCaseClient` to implement this.
```javascript
if (contactPromptResult.role.role === ts('Client') &&
$scope.roles.getActiveNonClientContacts().indexOf(contactPromptResult.contact.id) !== -1) {
contactPromptResult.showErrorMessageFor(
'contactSelection',
PeoplesTabMessageConstants.CLIENT_CANT_BE_SAME_AS_CLIENT
)
};
```
The validation logic was not applied when creating a new client. So moved the …

CPS-511: Do not allow client to be assigned to existing contacts

---

ang/civicase-base/providers/case-type.provider.js

When selecting the client roles dropdown on the popup modal, only the Client role is displayed and other relevant roles that should be displayed is missing.
Due to a recent change, the case category Id is being passed in the URL rather than the case category name. The value of the case category Id fetched from the URL is passed on to JS as an integer. 
However when the dropdown for the case roles selection popup is built, it needs the [Case roles](https://github.com/compucorp/uk.co.compucorp.civicase/blob/6a61010e2b5e46013cec0e5d04a09a4d70bf0637/ang/civicase/case/actions/services/email-case-action.service.js#L131) for the current case category and when the case roles is filtered [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/ang/civicase-base/providers/case-type.p …

CPS-583: Fix Issue With Only client role is displayed when selecting case roles for bulk emails

---

CRM/Civicase/Hook/Helper/CaseTypeCategory.php
ang/civicase.ang.php

When pages that requires angular to be bootstrapped are loaded in civicrm e.g `/civicrm` (Civicrm Dashboard) and a couple other pages, the `js_strings` cache in civicrm cache table keeps getting cleared even though the cache is not yet expired and this results in new cache files being regenerated in the `/sites/default/files/civicrm/persist/contribute/dyn/` folder in a site.
This causes a large number of files to be present in this folder as the files keep growing at a fast rate (Although the files are deleted when civicrm cache is flushed). Also updating the cache for every page request could have some significant impact in performance as has been reported for a site recently. 
This PR optimizes the way the cache is regenerated and ensures the cache is not invalidated on every page load …

CPS-246: Fix Issue with Cache Files Being Regenerated On Every Page Load

---

CRM/Civicase/Helper/CaseCategory.php

This PR fix a problem discovered by QA on the code for adding singular and plural labels to case type categories.
Two problems were discovered, related to the usage of word replacement.
- First, if we have, for example, these labels:
Plural: X-Prospects
Singular: X-Prospecting.
The word `Case`, singular, get replaced first by the `X-Prospecting` labels, generating the incorrect word `X-Prospectings`
- Second, if the new word for singular or plural, contains the word "case", the replacement get done twice.
Word replacements are correctly done, with any singular or plural label.
In the first commit, the order of replacements is changed. Replace first the plural and later the singular, avoiding to capture first the singular occurrence (which will always happen). This problem existed before, …

RSE-1276: Fix for Word Replacements Using Singular and Plural Labels

---

ang/civicase/activity/filters/directives/activity-filters.directive.js
ang/test/civicase/activity/directives/add-activity-menu.directive.spec.js
ang/test/civicase/activity/filters/directives/activity-filters.directive.spec.js
ang/test/mocks/data/activity-types.data.js
ang/test/mocks/data/cases.data.js

The Activity Type filter inside Activity Feed was not working. This PR fixes the same.
This is a regression caused by - https://github.com/compucorp/uk.co.compucorp.civicase/pull/284.
Where we moved `CRM.civicase.activityTypes` to `CRM['civicase-base'].activityTypes`, but forgot to update `activity-filters.directive.js`.
In `ang/civicase/activity/filters/directives/activity-filters.directive.js`, replaced `CRM.civicase.activityTypes` with `ActivityType.getAll()`.
Also added unit tests.

CPS-539: Fix Activity Type filter in Activity Feed

---

CRM/Civicase/Hook/BuildForm/AddCaseCategoryCustomFields.php

The name of the Case Type Category is used also for creating a menu, that is displayed on the panel later. We need to limit the max possible length to assign to this name, since can cause visual problems if it is too long.
The field for the Category Name allowed a maximum of 512 characters. Assigning a big number (greater than 200 hundred) cause additional errors, but just with more than 50 characters it is possible to visually break the interface.
The frontend is limiting the length to 45 characters (using the maxLength attribute)
The "Secondary label" is already limited to 45 characters. 
These changes only affects the Case Type Category options.
**Update:**  Secondary label was not limited to 45 characters, I have updated that now. The `size` attribute was 45, which is related to the …

CPS-595: Add maxLength Attribute to Label Field

---

CRM/Civicase/Form/Report/ColumnDefinitionTrait.php

When adding a new tag to a case or selecting some random tag, and selecting the Case Tag as `row field` and Case Status as `column field`, the tags show up as NULL in the case pivot report
The API call for fetching case tags used to replace the case tag Id's  and display the case tag name in the report post process is not fetching all the case tags at once as Civi will fetch the first 25 records by default. This is causing some tag Ids not to be replaced with their respective names and are appearing as NULL.
The fix is to set the limit to `0`.
Note that a ticket has been created to fix this issue at a more global level by adding an extension to set the limit to `0` by default for cases like this.

NEUSPRT-13: Fix Newly Created Tags Showing Up In Report As “NULL“ 

---

ang/civicase/activity/actions/services/resume-draft-activity-action.service.js
ang/civicase/activity/factories/view-in-popup.factory.js
ang/civicase/case/details/directives/case-details.directive.js
ang/test/civicase/activity/factories/view-in-popup.factory.spec.js
civicase.php
js/close-pdf-form.js

In PDF document Popup, after downloading the document, the popup did not close, and the user had to manually refresh the page to see latest activity. This PR fixes that, so that the popup closes and the activity feed refreshes.
The popup did not close, and the user had to manually refresh the page to see latest activity.
Implemented `civicase_civicrm_coreResourceList` hook, which attaches a new JS file.
Added `js/close-pdf-form.js` to implement the feature.

CPS-490: Close PDF popup after Download Document

---

ang/civicase-base.ang.php
ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
ang/civicase/case/details/people-tab/services/people-tab-roles.service.js

This PR solves two problems observed on the Manage Cases screen, related to inactive Relationship Types on some of the listed cases.
The problem is visible while trying to send bulk emails on a selected group of cases, and also while accessing the People's tab.
We should have a `Case Type` with a RelationshipType assigned, like "MyRelationshipTest A B" on the screenshot:
And that relationship should have been disabled:
When the action "Email - Send Now" is selected, this error is displayed:
Also, accessing People's tab on a case of the specific Case Type display errors:
After clicking on  "Email - Send Now" action, the expected windows is displayed:
Also, people's tab is accessible. The disabled relationship type is shown in a special way, indicating that is not available for being …

CPS-577: Include Inactive RelationshipTypes on View

---

CRM/Civicase/Hook/BuildForm/TokenTree.php
CRM/Civicase/Hook/Tokens/AddCaseCustomFieldsTokenValues.php
CRM/Civicase/Hook/Tokens/AddCaseTokenCategory.php
CRM/Civicase/Hook/Tokens/Helper/CaseTokenValues.php
civicase.php
tests/phpunit/CRM/Civicase/Hook/BuildForm/TokenTreeTest.php
tests/phpunit/CRM/Civicase/Hook/Tokens/AddCaseCustomFieldsTokenValuesTest.php
tests/phpunit/CRM/Civicase/Hook/Tokens/Helper/CaseTokenValuesTest.php

When creating an Email activity for a case and case custom field tokens are selected, when the Email is sent, neither the actual token or replaced token values are present in the Email.  More like the token was replaced with an empty string.
The issue described no longer exists. Now when Emails are sent with case custom fields tokens present. The tokens are replaced properly with the appropriate values.
This PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/749 fixes an issue that causes an error of Max table join on a site that has many Case custom fields enabled. The fix was to prevent default loading of all the custom fields for a Case and rather encourage on demand loading. However, when sending emails, Civi uses the [Case.getsingle …

CPS-609: Fix Case Custom Field Tokens Not Being Replaced In Emails

---

ang/civicase.ang.php

Replaces a deprecated use of `getUrlPath` by `currentPath`.
The new function was already used by the extension, a few lines above, so it should not cause any compatibility issues on existing sites.
CiviCRM logs warnings of deprecated `getUrlPath`.
:sunglasses:

Fix deprecated getUrlPath

---

ang/workflow.ang.php

Removes reference to an undefined variable.
PHP Error
Fixed
`$options` variable is never defined and seems to have been introduced via copy/paste.

Remove reference to undefined variable

---

CRM/Civicase/Setup/UpdateCategoryNavigationItems.php

This PR solves a syntax error on an upgrader method. 
Under some circumstances, the upgraders fail on that call. That does not happen always, probably depends on the PHP version.
The error was fixed.
As mentioned previously, probably the PHP interpreter was considering in some cases as a valid extra parameter, that's why the error passed undetected.

CPS-630: Fix syntax error on upgrader

---

ang/civicase-base.ang.php
ang/civicase-base/directives/access-denied.directive.html
ang/civicase-base/directives/acess-denied.directive.js
ang/civicase.ang.php
ang/civicase/app.routes.js

When trying to access the Dashboard/Manage <Case Type Category screen> for a user of different Case Type Category, the page was accessible, but Console Errors were seen. It has been fixed now, and Access Denied error is produced.
(when the `case_type_category` before and after the hash does not match.)
In `ang/civicase-base.ang.php`, added logic to throw error if the user does not have access to current case type category.
Also added a new directive `acess-denied.directive` which is shown when the `case_type_category` before and after the hash does not match.

CPS-575: Fix page level Permissions

---

ang/civicase/case/details/file-tab/directives/file-filter.directive.js
ang/test/civicase/case/details/file-tab/directives/file-filter.directive.spec.js

In the Case Details Files tab, the activity category filter was not working. This PR fixes the same.
In `ang/civicase/case/details/file-tab/directives/file-filter.directive.js`, the `$scope.refresh` function call was missing, and thats why the page was not getting refreshed.

CPS-501: Fix files tab Activity Category filters

---

CRM/Civicase/Hook/Tabset/CaseCategoryTabAdd.php

In the Contact Details page, the case type category menus are not capitalised, this PR fixes the same.

CPS-537: Capitalise first letter of Contact Details Menu

---

CRM/Civicase/Helper/InstanceCustomGroupPostProcess.php

This PR solves a limitation between the number of Case Types and Custom Groups associations.
If you have more than 25 Case Types created:
only the first 25 appears associated to a Custom Group:
Also, the inverse limitation existed: If you have more than 25 Custom Groups associated with Case Types, only the first 25 Groups get updated when a new Case Type is created.
All the Case Types are associated with the given Group:
And also the inverse situation was fixed: when a new Case Type is added, all the groups are updated.
The situation is solved by removing the limitation on the associated number of entities to return in the respective API call, for CustomGroups of CaseTypes.

RSESPRT-45: Fix Limitation Between Custom Groups and Custom Types

---

CRM/Case/Export/Form/Map.php
CRM/Case/Export/Form/Select.php
CRM/Civicase/Hook/PermissionCheck/CaseCategory.php

This PR solves a problem experienced while trying to export Cases from the Manage Cases screen. Also this error is visible for any other case type.
In Manage Cases page, after selecting "Export Cases" action, an error is displayed:
The export action works correctly:
As can be seen [here](https://github.com/civicrm/civicrm-core/commit/f95d7a0876962829ba6aff1b9437bf1b4cfcbc74#diff-ca3d52925273a5d514259e5d7c95cdbc1e0b98ef642c33b5674ea68d8e85d26f) there was a recent change in civi-core that specifies a format for classes used in standalone mode.
This format is correctly followed by Activities, Contribution, Contacts, and other entities, but not for Cases. Then, these classes are not found when tried to be loaded: `CRM_Case_Export_Form_Map` and `CRM_Case_Export_Form_Select`
For solving the …

ACU-594: Add Map and Select classes for exporting cases

---

CRM/Civicase/Form/Report/BaseExtendedReport.php

When a date related field such as Case start date is selected as the column in the case pivot report, the data for the dates column does not show up. 
The issue is fixed and data now shows up when a date field is selected as a column. 
The regression was introduced in this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/693. The date fields is a bit different from other report fields because it either gets grouped by date or year, the actual values are not used.  The array intersect [here](https://github.com/compucorp/uk.co.compucorp.civicase/pull/693/files#diff-ffc55342f1d0a39ba391eb4d70335b441e7dee676824ce3866b78dad65326b13R779-R780) will return an empty array for date related column fields because the `used options` will return the actual dates for cases while the …

BASWSPRT-275: Fix Missing Pivot Date Data

---

CRM/Civicase/Setup/AddSingularLabels.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0016.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomFieldsSettingTest.php

Some of the recently added upgrader logic was not applied when creating a new fresh site. This PR fixes the same.
Singular Labels were not created.
Singular Labels are created.
This is a regression of https://github.com/compucorp/uk.co.compucorp.civicase/pull/760. Where we forgot to mention apply the AddSingularLabels logic for creating a new site. This PR fixes that.
1. Code from `CRM/Civicase/Upgrader/Steps/Step0016.php` has been moved to `CRM/Civicase/Setup/AddSingularLabels.php`, and reused for upgrading and creating a new site.

CPS-655: Fix new site deployments

---

CRM/Civicase/Service/CaseCategoryInstance.php

When trying to Create a new Case Type Instance, if the Case Type already exists, error was thrown. This PR fixes that, and just edits the Instance with the new Instance ID.
Error was thrown.
Error is not thrown. And record is updated.
In `CRM/Civicase/Service/CaseCategoryInstance.php`, the `createInstanceTypeFor` was throwing error when trying to add instance for an Existing Case Type Category. Because Case Type Category is anunique field. But this is unexpected, instead now, we edit the case type category.

RSESPRT-55: Edit instance instead of creating if it already exists

---

CRM/Civicase/Hook/alterMailParams/SubjectCaseTypeCategoryProcessor.php
tests/phpunit/CRM/Civicase/Hook/alterMailParams/SubjectCaseTypeCategoryProcessorTest.php

This issue was previously reported for the prospect category (Sales and opportunity tracking) but was also observed for case categories belonging to the case management instance. See details here: https://github.com/compucorp/uk.co.compucorp.civicrm.prospect/pull/93.
When an Email activity is created for a case category of the case management instance, the sent email subject contains the word _singular_wildcard_ instead of the appropriate case category name.
The issue described above is fixed. 
The word replacement for case management instance categories was using the word replacements for Case management instances [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/5ad931596188b21a402a06b7430ac08447c88ed9/CRM/Civicase/Helper/CaseCategory.php#L147-L156) hence this logic …

RSESPRT-59: Fix Wrong Text In Case Management Case Category Email Subject 

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js

When a user tries to perform a bulk action such as adding contacts to a group on the other relationships tab on a case, the modal becomes unresponsive after and some console errors are logged. The bulk action is actually performed but the modal becomes unresponsive. 
The issue is fixed and bulk actions can be performed and the modal can be closed or other actions performed.
The issue is a regression introduced in this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/748, A new `filter` parameter was introduced to the `getRelations` function. There was a place missed in code that still calls the method (this causes an error [here](https://github.com/compucorp/uk.co.compucorp.civicase/blob/daf2749c0a32987f85746a803f4bce06c894ef00/ang/civicase/case/details/people-tab/directives/ …

RSESPRT-60: Fix Console Errors For Bulk Actions On Other Relationships Tab

---

ang/civicase/case/actions/services/edit-tags-case-action.service.js
ang/test/civicase/case/actions/services/edit-tags-case-action.service.spec.js

The Edit Tag form accessed on the manage cases page via the hamburger menu allows to select a tag that has been marked non selectable and the tag dropdown list also displays the tags in an unordered fashion. This PR fixes the issue by removing non selectable tags from the list and also sorting the tag names in alphabetical order. 
The  tag dropdown list also displays the tags in an unordered fashion.
The issues described above has been fixed
To fix the first issue, the tags fetched from the Tags api is simply sorted by the name. 
The second one is a bit tricky because we can't get the results from the API directly as Tagsets are created by default with the `is_selectable` property set to `0` as this property does not really apply to Tagset and is not …

NEUSPRT-25: Remove Disabled Case Tags and Sort Case Tags Alphabetical Order

---

ang/civicase/case/directives/case-overview.directive.js
ang/test/civicase/case/directives/case-overview.directive.spec.js
ang/test/mocks/data/cases-statuses.data.js

Case statuses are sorted in ascending order by weight on the case dashboard but this seems not to be consistent across sites.  
The issue described above exists. 
This issue is easily replicable. For example , on a site with 9 case statuses, if a 10th case status is added, instead of the new case status to be at the bottom of the list, it rather listed as the second case status on the list on the Case dashboard.
The issue described above is fixed and case statuses are ordered by weight in ascending order. \
The weight property of the case status object is a string and when this is being sorted, the sorting is not consistent. E.g "2" > "10" will evaluate to TRUE. To fix the issue, the weight is parsed as an integer to be used for the sorting so that the case statuses are sorted properly. …

NEUSPRT-35: Fix Case Statuses Order On Case Dashboard

---

CRM/Civicase/Form/Report/ColumnDefinitionTrait.php
CRM/Civicase/Form/Report/ExtendedReport.php
CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForChangeCase.php
CRM/Civicase/Hook/BuildForm/CaseCategoryFormLabelTranslationForNewCase.php
CRM/Civicase/Hook/Helper/CaseTypeCategory.php
CRM/Civicase/Hook/Permissions/CaseCategory.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForChangeCase.php
CRM/Civicase/Hook/PreProcess/CaseCategoryWordReplacementsForNewCase.php
CRM/Civicase/Hook/Tokens/AddContactTokens.php
CRM/Civicase/Upgrader.php
README.md
gulp-tasks/generate-translations.js
gulpfile.js
l10n/civicase.pot

The PR implements proper usage of the `ts` or translation function. 
1. Used `E::ts` instead of `ts`.
2. `ts` function should only be used with string values, so applied the same.
3. A new Gulp task, `generate-translations` has been added, which will generate the translation file(`.pot`).
**New function created for translation**
Under `CRM_Civicase_Hook_Helper_CaseTypeCategory` class a new function `translate` has been created. 
This is wrapper for "E::ts" function.
CiviCRM does not recommend to use this to translate variables. But in CiviCase, we have used this function in few places with variables to achieve certain results. Hence this new function has been created, so that it can be only used in the places where it is absolutely necessary.
The Backstop Tests were run in …

CPS-432: Fix ts function usage

---

CRM/Civicase/Page/ContactCaseTab.php

This PR fixes the issue with the awards tab not loading from the contact page. 
Though not directly the cause of the bug here, this PR corrects the bug with the method `getModuleAndDependenciesTranslations($mainModuleName)` ignoring $mainModuleName and instead defaulting to 'civicase'
The error was caused by a NULL value being passed to the CIviCRM function CRM_Core_Resources::singleton()->addSetting() function.

RSESPRT-70: Fix awards tab not loading

---

CRM/Civicase/APIHelpers/CaseDetails.php
CRM/Civicase/APIHelpers/CustomFieldFilter.php
CRM/Civicase/Test/Fabricator/CustomField.php
CRM/Civicase/Test/Fabricator/CustomGroup.php
tests/phpunit/api/v3/Case/GetcaselistTest.php

The filters in the Manage Cases page don’t work correctly when searching by custom fields with multiple options, this is because of the way values for multiple options custom fields are stored by CiviCRM.
As seen in the image above, the first row has two values, 12 and 13 respectively and these two values are stored in a single column delimited by space( ).
So a filter condition to get a case with the custom field that has the value `12` would only return the second row and exclude the first row.
since the where condition generated by civicrm would likely be in the form `where case_the_e_112 = 12`, or in some cases `where case_the_e_112 IN (12, 13)`, in any of the two, it is certain that the condition used by CiviCRM assumes the column `case_the_e_112` would always contain a single value, …

BASWSPRT-308: Fix cases search with multiple options custom field

---

ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
ang/civicase/case/list/directives/case-list-table.directive.js
ang/civicase/case/search/directives/search.directive.js
ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
ang/test/civicase/case/search/directives/search.directive.spec.js

When trying to access a case through the contact case tab and trying to open the case from "GO TO CASE"  button, the following error is thrown. 
"The case you are trying to view is not visible as your filters do not match.
Please click below to remove your filters"
This PR fixes that.
`/civicrm/case/a/?case_type_category=1#/case/list?caseId=55&focus=1&all_statuses=1`
`/civicrm/case/a/?case_type_category=1&p=mg#/case/list?focus=1&cf={"id":55}&caseId=55`
In the code, a api call is 1st made with `page_of_record: <case_id>`, which then returns the page number in which that case is part of(here page number refers to the pagination page number of manage case list). But looks like sometimes this page no is not getting generated correctly, and hence the issue.
Initially I thought that this is …

BASWSPRT-193: Change url of case from contact case tab

---

CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
CRM/Civicase/Service/CaseCategoryMenu.php
tests/phpunit/CRM/Civicase/Service/CaseCategoryCustomFieldExtendsTest.php

This PR adds the required methods for CiviAwards - https://github.com/compucorp/uk.co.compucorp.civiawards/pull/206 - to call them when is disabled/enabled.
- Added methods for activating/deactivating the custom field extend option group for the case
category according to the extension status.
- Added methods for activating/deactivating  a menu item.

IO-143: Add methods to activate/deactivate menu/option group

---

info.xml

CiviCase 2.5.0 release which includes support to CiviCRM 5.39.1

PROD-19: Civicase 2.5.0 release

---

.github/workflows/linters.yml
.github/workflows/unit-test.yml

This PR fixes the failed linter workflow.
The `Set Correct NodeJS version` step bootstraps the project with `nvm` so that `nvm` will install Node.js 14.16.0 which is specified in the file `.nvmrc`.
The issue is the `Run npm install` step didn't use the version 14.16.0 and instead used the version 16.3.1.
Here, I introduce the [setup-node action](https://github.com/actions/setup-node) which allows us to specify a Node.js version. It was created by the Github team.
Before using the action, we read the the version specified in the file `.nvmrc` and set an [output parameter](https://github.com/actions/setup-node/issues/32#issuecomment-539794249) so that the action can use it in the next step.

COMCL-168: Fix linters workflow

---

CRM/Civicase/Api/Wrapper/CaseGetList.php

This PR fixes the issue when the site throws an error when accessing SearchKit menu. 
When using SearchKit function, the APIWrapper hook get called and API v4 object is passed to $apiRequest, and CiviCase implements apiWrappers [hook](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_apiWrappers/), and the implementation only accept a parameter as an array, hence, PHP throws the error.
According to https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_apiWrappers/   $apiRequest parameter can be passed as array or Civi\Api4\Generic\AbstractAction therefore the function must be able to handle multiple types argument. 
Note on the CiviCase's API Wrapper hook, the implementation mainly handle an array and this should not be any issue as the Civi\Api4\Generic\AbstractAction class …

COMCL-167: Accept multiple types argument

---

ang/civicase/case/directives/case-overview.directive.js

This PR resolves the issue with disabled case status appearing on the Case Status filter.
Disabled case statuses are still in the case status filter dropdown.
Disabled case statuses are no longer visible in the case status filter dopdown.

NEUSPRT-92: Filter out disabled case statuses in case overview

---

.github/workflows/linters.yml
api/v3/Case/Getfiles.php
bin/install-php-linter
package-lock.json
package.json

This PR resolves the issue with files not appearing in the case file tabs for specific case IDs, as the server timeouts `HTTP 504` during the request before SQL could return a result. 
The issue is caused by the number of files that are associated with the affected case IDs, and also the more the files the longer it takes for the SQL to execute, which in turn affects the server response time.
The simple approach taken to resolve this issue is to optimise the SQL query for selecting the files.
The query generated by `_civicrm_api3_case_getfiles_select()` for `case_id = 1` before update.
> SELECT DISTINCT caseact.case_id as case_id, caseact.activity_id as activity_id, f.id as id, act.activity_date_time
> FROM civicrm_case_activity caseact
> INNER JOIN civicrm_entity_file ef ON …

NEUSPRT-84: Refactored the query for selecting case files into subquery

---

api/v3/Activity/Movebyquery.php

This PR deletes a case activity after moving it to another case, so it doesn't appear in the Case it was moved from.
Move activity from case 1 -> case 2
Activity can still be seen in case 1 after the move.
Move activity from case 1 -> case 2
Activity can no longer be seen in case 1 after the move.

NEUSPRT-98: Delete a case activity after moving to another case

---

api/v3/Activity/Deletebyquery.php

This PR resolves the issue with a copied activity being deleted when the activity it was copied from is deleted.
When an activity is copied from one case to another, the duplicated activity is linked to the original activity in the DB by the column original_id.
hence, when an activity is deleted, activities linked to it via their original_id column are deleted also.
The solution is to unlink other activities from the activity before it is deleted. a new function `unlink_from_other_activities` is created to unlink other activities if any before it is deleted, note this function is only called in `civicrm_api3_activity_deletebyquery` so it only affects activities deleted in the CiviCase dashboard.

NEUSPRT-108: Prevent deleting of copied activities

---

ang/civicase/case/list/directives/case-list-table.directive.js

This PR resolves the bug that happens when editing cases' subjects and details in the cases list view, if multiple case subjects and details are edited only the first case is changed and it takes the value of the last edited case.
The `crmEditable` function uses the data-id value of the closest element with class `.crm-entity` to know the id of the entity being edited, but `data-*` attributes are only pulled once from the DOM when the data property is first accessed, and subsequent read of the `data-*` returns the value from the cache, which is the value of the first case to be opened and not the currently opened case.
The solution is to clear the cache when a new case is opened.

NEUSPRT-102: Clear crm-entity stored data in cache

---

CRM/Civicase/APIHelpers/ActivityQueryApi.php
api/v3/Activity/Copybyquery.php
api/v3/Activity/Movebyquery.php

This PR transfer case activity tags along with the activity when the activity is been moved or copied from one case to another.
Activity tags are not moved to the new activity.
Activity tags are moved to the new activity.

NEUSPRT-110: Transfer activity tags when moving or copying

---

CRM/Civicase/Helper/CaseCategory.php
CRM/Civicase/Upgrader.php
tests/phpunit/api/v3/Case/GetfilesTest.php

This PR Resolves the SQL syntax error that occurs when creating a new case_category_instance_type type e.g. A new type of Awards application, and when installing the extension.
On a server with MySQL 8 and above the following error is thrown when trying to access some part of CiviCase(create a new case_category_instance_type type e.g. A new type of Awards application ) and option group settings page 
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'grouping ,v.value as value, v.grouping as `grouping` FROM civicrm_option_value v' at line 1
```
This error is caused by retrieving a column named `grouping` without having it surrounded by backticks `` ` ``,  because grouping is a …

WHF-329: Remove the use of sql keyword 'grouping' causing syntax error

---

api/v3/Case/Getwebforms.php

This PR orders the case webform actions by title ASC on default, or uses the sort order specified by the caller of `case.getwebforms` API action.
The order of returned results from `case.getwebforms` is not always guaranteed
The order of returned results from `case.getwebforms` is now guaranteed

CATL-2244: Order case webform action by title ASC

---

ang/civicase/case/details/people-tab/services/people-tab-roles.service.js

Users cannot update any of the case roles/relationships start or end date when the "Allow multiple case clients" is set to "Single client per case".
_A brief description of the pull request. Try to keep it non-technical._
Neither of the case role/relationship start or end date could be set when "Single client per case" is set:
Both of the case role/relationship start and end dates can be changed:
Due to the work done in this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/732
when "Allow multiple case clients" is set to "Single client per case", the list of retuned relationships no longer has the `relationship_ids` parameter, which is used to construct the relationship API call that updates the relationship start and end dates …

CATL-2256: Fix updating role/relationship date under certain configs

---

CRM/Civicase/Activity/ContactActivitiesSelector.php
api/v3/Activity/Getall.php

The activity tab loads very slowly  (and often does not load because it timeout) when the contact has a lot of Activities of certain types, mainly "Bulk Email" and "Mass SMS", this PR fixes that.
Activity tab is very slow (and in this case it timeout):
activity tab loads fine:
Though the difference is that "Bulk Emails" and "Mass SMS" activity types will no longer show the "To" and "From" parts:
When sending bulk emails, CiviCRM creates one activity that is shared between all the contacts that the email was sent to, these contacts will be stored as “target contact” inside the civicrm_activity_contact table.
In one of our client sites, most contacts  have around 33 activities, most of them are “Bulk Email” activities, but each of these activities are shared with another 30,000 something …

FDI-80: Improve activity tab performance

---

CRM/Civicase/BAO/Query/ContactLock.php
CRM/Civicase/Page/MyActivities.php

These are the quick fixes for issue #848 . It also includes a quick fix to use addModules instead of setModules (due to a message we get from Core that setModules is deprecated).

PHP fatal error fixes, issue #848

---

CRM/Civicase/Hook/ValidateForm/SendBulkEmail.php
CRM/Civicase/Hook/alterMailParams/SubjectCaseTypeCategoryProcessor.php
ang/civicase/activity/activity-forms/services/activity-form-services/add-custom-path-activity-form.service.js
ang/civicase/case/actions/services/email-case-action.service.js
ang/civicase/case/details/directives/case-details.directive.js
ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
ang/civicase/case/details/people-tab/directives/other-relationships-tab.directive.html
ang/civicase/contact/directives/contact-popover-content.directive.js
ang/test/civicase/activity/activity-forms/services/activity-forms-services/add-custom-path-activity-form.service.spec.js
ang/test/civicase/case/actions/services/email-case-action.service.spec.js
ang/test/civicase/case/details/directives/case-details.directive.spec.js
ang/test/civicase/contact/directives/contact-popover-content.directive.spec.js
civicase.php
tests/phpunit/CRM/Civicase/Hook/ValidateForm/SendBulkEmailTest.php
tests/phpunit/Helpers/MailHelpersTrait.php

CiviCRM only supports sending bulk mail to contacts on a single case, in a previous PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/804 we bypassed this limitation and allowed sending of bulk mail to contacts on multiple cases, this feature worked until recently when we added support for CiviCRM version `5.51.3`. because of the following 
1. CiviCase uses this action form `CRM_Contact_Form_Task_Email` to send emails action, but in the recent version of CiviCRM some methods peculiar to case entity have been moved to a new child form `CRM_Case_Form_Task_Email` as seen in this commit https://github.com/civicrm/civicrm-core/commit/dcecc495e042dc45c45e23a0e02d1e02caef2341
2. In the hook `CRM_Civicase_Hook_ValidateForm_SendBulkEmail` we update the `_toContactEmails` form field to …

MAE-823: Fix bulk mail

---

CRM/Civicase/Upgrader/Steps/Step0018.php

`Award` is a case_type_category, the  description below is applicable to other case_type_category like `Prospect`.
As we can see in the image above the custom group is used for Arts & Humanities Awards and other award types. if a new award type is created with Arts & Humanities Awards as its subtype, this new award type would also be added to the custom group used for i.e. `extends_entity_column_value`. this applies to all case sub-types. so the  extends_entity_column_value column keeps growing but according to the dB schema, it can only take 255 characters `VARCHAR(255)`, when it outgrows the current.
In this PR, we add an upgrader to change the custom_group extends_entity_column_value type to TEXT, so that it can accommodate more IDs.
_the custom_group extends_entity_column_value type …

RSESPRT-121: Change the custom_group extends_entity_column_value type to TEXT

---

ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js

This PR fixes the issue with multiple popups being shown when an action is selected in the `people` -> `other relationships` tab
Multiple popups are displayed to the user
A single popup is displayed to the user
The `ng-change` directive in Angular is used to watch for changes in the model attached to an input. CiviCRM `crm-ui-select` fires events that change the model value more than once, causing the event handler `doContactTask` to be called twice, hence displaying multiple popups, this happens when the attached model value is programmatically updated, even though according to the [angularjs](https://docs.angularjs.org/api/ng/directive/ngChange) this should not happen.
A similar issue was mentioned as a part of this [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/451), …

CPS-720: Fix multiple popups on selecting an action

---

CRM/Civicase/Hook/alterAPIPermissions/CaseCategory.php

Fixing some pages that do not load on PHP 8.
Neither "Manage Cases" page, or trying to create new case type category  are working:
Things are working fine as before:
Case type category parameters that are passed to getCaseCategoryNameFromCaseTypeCategory() function are expected to be either an array or an integer, but the mentioned method tries to check if the "IN" key exist regardless, using array_key_exists() function.
This was not an issue before because on PHP 7.4  it will just throw a warning, but on PHP 8 it throws an error, resulting in issues with the above pages and for the following error in logs:
```
"Nov  9 11:13:29 php oddly-divine-kid_docker_cc-test_site-drupal: 1667992409|10.16.135.31|https://oddly-divine-kid.docker.cc-test.site|php|https://oddly-divine-kid.docker.cc-test.si …
```

MAE-956: Fix Manage cases and new case type cateogery pages on PHP 8

---

CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
api/v3/Activity/Getdayswithactivities.php
api/v3/Activity/Getmonthswithactivities.php

This PR resolves the issue of not being able to record case activity on a contact page.
In PHP 8.0 using array_key_exists with a non-array variable throws an error, we resolve this by ensuring the `$fields['buttons']` is not null.
likewise, in PHP 8.0 undefined constants are no longer interpreted as a string, we explicitly use `limit` index as a string https://github.com/compucorp/uk.co.compucorp.civicase/blob/b51d901649eb6f77b87033309f1fd426d9cc2481/api/v3/Activity/Getdayswithactivities.php#L146

MAE-966: Resolve issue with recording case activity on contact page

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/ColumnDefinitionTrait.php
CRM/Civicase/Form/Report/ExtendedReport.php
CRM/Civicase/Hook/PostProcess/ActivityFormStatusWordReplacement.php

This PR resolves the following issues on the PHP8 site
- users cannot create new case activity reports.
- users cannot create case activities from the case dashboard.
Users are not able to create new case activity reports.
Users are able to create new case activity reports.
Users are not able to create case activities from the case dashboard.
Users can create case activities from the case dashboard.
- users cannot create new case activity reports: This issue was caused by an incompatibility in method definition between the child and parent classes.
- users cannot create case activities from the case dashboard: This happens because caseId returned from the `getVar` method is an array, whereas the caseId is expected as a string, we resolve this issue by getting the first element in the …

MAE-976: Fix issue with Creating Case Activity and creating Case Activity reports.

---

CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php
CRM/Civicase/Hook/BuildForm/LimitRecipientFieldsToOnlySelectedContacts.php
CRM/Civicase/Hook/BuildForm/RestrictCaseEmailContacts.php
CRM/Civicase/Hook/BuildForm/TokenTree.php
CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCases.php
CRM/Civicase/Hook/PostProcess/HandleDraftActivity.php
CRM/Civicase/Hook/ValidateForm/SaveActivityDraft.php
ang/civicase/activity/activity-forms/services/activity-form-services/draft-email-activity-form.service.js
ang/test/civicase/activity/activity-forms/services/activity-forms-services/draft-email-activity-form.service.spec.js
tests/phpunit/CRM/Civicase/Hook/BuildForm/TokenTreeTest.php
tests/phpunit/CRM/Civicase/Hook/PostProcess/AttachEmailActivityToAllCasesTest.php

This PR solves the following:
1- Issues related to `Send Draft` button not visible and not working as expected when user `Send Email`
2- Restrict email recipients only to contact involved with the case not working as expected.
3- When enable `Limit recipients field on bulk email` from settings and `Send bulk message` not working as expected
4- Token list when user `Send Email` is not working properly.
These issues occurs because of the support for CiviCRM 5.51.3
CiviCRM uses `CRM_Contact_Form_Task_Email` to send Email, in recent version they moved to use `CRM_Case_Form_Task_Email`, more on this in here[PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/868) 
for issue 1: `Send Email` sent the user to this url `civicrm/case/email/add` which uses  `CRM_Case_Form_Task_Email ` …

MAE-992: Fix restrict email recipients to contact involved with case

---

api/v3/Activity/Getactionlinks.php

In PHP8  users are unable to access the standalone page, whereas in PHP7.4 the standalone page is displayed but with incorrect data.
On a site running PHP 7.4, The Activity data differs from what is shown on the standalone page.
<hr>
On a site running PHP 8.0+, The activity standalone page returns an error.
The activity standalone displays the correct data with no error.
The error on the standalone page happened because the URL placeholders in the activity menu actions are not resolved to their actual value. e.g. `/civicrm/activity?atype=20&amp;action=view&amp;reset=1&amp;id=%%id%%&amp;cid=%%cid%%&amp;context=%%cxt%%&amp;searchContext=activity` therefore, there's no way for the activity page to know what activity to display.
Upon investigation, it was discovered that the …

MAE-985: Allow users to view an activity in a standalone page

---

CRM/Civicase/Event/Listener/AssetBuilder.php
CRM/Civicase/Hook/Helper/CaseTypeCategory.php
civicase.php

This PP fixes the issue with awards, prospects and other `case_type_categories` showing the default case label. 
Other case-type categories(awards and prospects) show Case labels. 
Other case-type categories(awards and prospects) Dashboard showing their appropriate labels.
In CiviCRM, the Angular translation strings are loaded in a separate AJAX request `/civicrm/asset/builder?an=angular-modules.json` asset after the initial page request. and since the CiviCase word replacement implementation depends on the `case_type_category` URL param to load the translation strings, the replacement strings for the current case_type_category are not loaded.
To overcome this when the `angular-modules.json` asset is requested we call the `CRM_Civicase_Hook_Helper_CaseTypeCategory::addWordReplacement` …

MAE-823: Fix UI not showing the right labels for other case_type_categories

---

CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php

This PR adds a direct Menu Link to create/edit CiviCase Instances in between CiviCase settings and Case Types.
The menu item doesn't exist.
The menu item now exists.

BTHAB-37: Add direct link to CiviCase Instances

---

ang/civicase/activity/factories/format-activity.factory.js

If some activity statuses are disabled, viewing old/existing data may cause Javascript errors, therefore causing the Contact Activity tab to fail to load.
To reproduce:
* Create a new Activity
* Save as Draft
* Then to go CiviCRM administration, and disable "Draft" as an activity status.
* Go back to the contact that had a draft activity - the tab fails to load.
`getAll(true)` to load all activity statuses. This only impacts activity display.
none

Format Activity: avoid errors when some statuses are disabled

---

CRM/Civicase/Hook/BuildForm/AddCaseCategoryFeaturesField.php
CRM/Civicase/Hook/NavigationMenu/AbstractMenuAlter.php
CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
CRM/Civicase/Hook/NavigationMenu/CaseInstanceFeaturesMenu.php
CRM/Civicase/Hook/PostProcess/SaveCaseCategoryFeature.php
CRM/Civicase/Service/CaseTypeCategoryFeatures.php
civicase.php
sql/auto_install.sql

In this PR we add the functionality to display the enabled extra features menu, under their respective CiviCase instance.
No menu support for extra features.
If an extra feature is enabled for a CiviCase instance and the extra feature has support for menu, the menu will be displayed under the instance menu.
This `the extra feature has support for menu` is currently hardcoded and only the `Quotations` feature is supported.
https://github.com/compucorp/uk.co.compucorp.civicase/blob/31d275c5516e348d92fdd386cd65ef298992df90/CRM/Civicase/Hook/NavigationMenu/CaseInstanceFeaturesMenu.php#L12-L19
In the future when adding menu support for other features we can add an input in the option value form, but that is beyond our current scope of work.

BTHAB-20: Display enabled features menu

---

ang/civicase/activity/factories/format-activity.factory.js

This PR fixes the error that happens when a status used in a Case activity is disabled. here is the original PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/846

CIVIIB-88: Avoid errors when some statuses are disabled 

---

CRM/Civicase/BAO/CaseSalesOrder.php
CRM/Civicase/Hook/NavigationMenu/CaseInstanceFeaturesMenu.php
CRM/Civicase/Service/CaseTypeCategoryFeatures.php
CRM/Civicase/Test/Fabricator/Product.php
Civi/Api4/Action/CaseSalesOrder/ComputeTotalAction.php
Civi/Api4/Action/CaseSalesOrder/SalesOrderSaveAction.php
Civi/Api4/CaseSalesOrder.php
Civi/Utils/CurrencyUtils.php
ang/civicase-features.ang.php
ang/civicase-features/app.routes.js
ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js
ang/civicase-features/quotations/directives/quotations-list.directive.html
ang/civicase-features/quotations/directives/quotations-list.directive.js
ang/civicase-features/services/currency-codes.service.js
ang/civicase-features/services/feature-case-types.service.js
ang/civicase-features/services/sales-order-status.service.js
ang/civicase/shared/directives/history-back.directive.js
api/v3/Case/Getdetails.php
tests/phpunit/Civi/Api4/CaseSalesOrder/ComputeTotalActionTest.php
tests/phpunit/Civi/Api4/CaseSalesOrder/SalesOrderSaveActionTest.php
tests/phpunit/Helpers/CaseSalesOrderTrait.php

This PR adds a new screen and API to create a new quotation.
The new sales order screen doesn't exist.
The new quotation screen now exists.
Two new API v4 endpoint actions were added to the Sales Order entity.
- **ComputeTotalAction**: This action takes an array of line items as input and returns an array of tax_rates in descending order based on the tax value, along with totalBeforeTax and totalAfterTax values.  
The purpose of this API is to recalculate the total amount when a change affecting the total is made by the user, such as modifying the quantity of a line item or selecting a new financial type. To prevent excessive calls, the API is debounced and triggered when a `totalChange` event is received `$scope.$on('totalChange', _.debounce(handleTotalChange, 250));`
- …

BTHAB-23: Add API/Screen to create new quotation

---

ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js
ang/civicase-features/quotations/directives/quotations-list.directive.js

With this PR if a user clicks on the `Create Quotation` button from a case dashboard, the `case/opportunity` field will be pre-filled and disabled
Clicking on the `Create Quotation` button from a case dashboard doesn't make any difference.
Clicking on the `Create Quotation` button from a case dashboard will have the case field prefilled

BTHAB-28: Prefill case/opportunity field for new quotations

---

ang/civicase-features.ang.php
ang/civicase-features/quotations/directives/quotations-discount.directive.html
ang/civicase-features/quotations/directives/quotations-discount.directive.js
civicase.php

With this PR users can apply discounts to quotations in bulk
The bulk discount action doesn't exist.
The bulk discount action now exists.
- User selects a list of quotations to apply discounts to
- A dialog appears where the user selects the specific products that the discount would be applied and enters the value of the discount.
- On submission, we look up each quotation for a line item that is linked to one of the selected products, if any, we add the discount to the line item discount.
- After updating the discounts we save every quotation that has been updated. saving the discount will recalculate the total amounts.
- Also since the discount is applied in bulk, and some line items might already be close to 100, we add this code `Math.min(100, newDiscount);` to ensure no discount goes …

BTHAB-46: Allow user to apply bulk discount to quotations

---

CRM/Civicase/Hook/BuildForm/AddQuotationsNotesToContributionSettings.php
CRM/Civicase/Hook/PostProcess/SaveQuotationsNotesSettings.php
civicase.php

With this PR we add a new terms field to the Civi Contribution settings page  
This field doesn't exist
The quotations terms field now exists.
The preferred way to add settings as described here https://docs.civicrm.org/dev/en/latest/framework/setting/extension/ is to create a `.setting.php` file, using this method doesn't produce the desired result as we couldn't move the new settings to the end of the form, also when the form is submitted the Quotations Notes field is encoded such that `<p>hello</p>` becomes `&lt;p&gt;hello&lt;/p&gt;` and doesn't get decoded back when being displayed.
So instead we decided to use hooks to add the field and save its value to settings.

BTHAB-44: Add quotations field to contribution settings

---

ang/afsearchContactQuotations.aff.html
ang/afsearchQuotations.aff.html

This PR adds a new field `description` to the list view, allowing the user to filter the listed quotations by description.
No description filter field.
description filter field now exists.

BTHAB-21: Allow quotation to be filtered by description

---

CRM/Civicase/Form/CaseSalesOrderInvoice.php
CRM/Civicase/Hook/PostProcess/SaveQuotationsNotesSettings.php
CRM/Civicase/Hook/Tokens/AddCaseTokenCategory.php
CRM/Civicase/Hook/Tokens/SalesOrderTokens.php
CRM/Civicase/Setup/Manage/QuotationTemplateManager.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0019.php
CRM/Civicase/WorkflowMessage/SalesOrderInvoice.php
civicase.php
templates/CRM/Civicase/Form/CaseSalesOrderInvoice.tpl
templates/CRM/Civicase/MessageTemplate/QuotationInvoice.tpl
tests/phpunit/CRM/Civicase/Form/CaseSalesOrderInvoiceTest.php
tests/phpunit/Helpers/CaseSalesOrderTrait.php
xml/Menu/civicase.xml

This PR adds the functionality allowing users to download a sales order invoice or send it as an attachment in an email.
The functionality doesn't exist
A User can download an Invoice as a PDF
A User can send an invoice as an attachment
In this PR we've added support for new sales order tokens, only the sales order fields can be used as tokens, we didn't add support for sales order line items as tokens, also good to note that the tokens are only resolved if they are used in a mail sent from the sales order view.
This PR extends the CiviCRM EmailTrait to handle the email display but we handled the sending of the email form, this is because we needed to ensure tokens are resolved, especially the sales order entity tokens and also we wanted to generate an invoice for the sales order and …

BTHAB-43: Add functionality to download / email Sales Order Invoice

---

ang/civicase-features/quotations/directives/quotations-create.directive.js

This pull request (PR) allows the user to save a quotation edit with a default or a previously set date. Also, updated the alert message shown to the user after an update.
Previously, when a user edited a quotation, they could not save the changes with a default date. The user would have to manually enter the quotation date every time they made an edit. 
With this PR, the user can now save a quotation edit with a default or previously set date.
This PR modifies the `quotations-create.directive.js` file in the `ang/civicase-features/quotations/directives/` directory. Specifically, it adds a line of code that sets the quotation date to the date from the retrieved quotation object in the "yy-mm-dd" format. The code uses the jQuery UI `datepicker` function to format the date.

BTHAB-25: Allow user to save quotation edit with default date

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
templates/CRM/Civicase/Form/CaseSalesOrderContributionCreate.tpl
xml/Menu/civicase.xml

This pull request adds a menu item and a new page for creating sales order contributions. The core logic for creating the contribution will be added in a subsequent PR.
Previously, there was no way to create sales order contributions directly from the quotations list page. 
With this pull request, the user can now create a sales order contribution from the quotations list page by selecting the "Create Contribution" option from the dropdown menu. 
- The `civicase.xml` file was updated to add a new menu item for creating sales order contribution.
- A new form controller class, `CRM_Civicase_Form_CaseSalesOrderContributionCreate`, was added to handle the form for creating sales order contributions.
- A new template file, `CaseSalesOrderContributionCreate.tpl`, was added for the form layout. …

BTHAB-33: Add quotations action and form for creating sales order contribution

---

CRM/Civicase/Hook/NavigationMenu/CaseInstanceFeaturesMenu.php
ang/afsearchQuotationInvoices.aff.html
ang/afsearchQuotationInvoices.aff.json
ang/civicase-features.ang.php
ang/civicase-features/app.routes.js
ang/civicase-features/invoices/directives/invoices-case-tab-content.html
ang/civicase-features/invoices/directives/invoices-list.directive.html
ang/civicase-features/invoices/directives/invoices-list.directive.js
ang/civicase-features/invoices/services/quotations-case-tab.service.js
ang/civicase-features/shared/configs/add-features-tab.config.js

This pull request adds a new page to list quotation invoices. The Invoices can be accessed under the Civicase instance that has the invoice feature enabled.
Before this pull request, there was no page for listing quotation invoices.
After this pull request, a user can see a new tab called `invoices`  on the case dashboard, this view will list invoices created for the case quotations.
Also, a new menu item called `invoices` can be seen under the `civicase` instance menu, this view will list all invoices created for any quotations either linked to a case or not.
The `afsearchQuotationInvoices` directive is used to create the search display table for the quotation invoices, it is created using `searchkit` and `afform`, see this [doc](https://docs.civicrm.org/dev/en/latest/afform/overview/) …

BTHAB-48: Add page to list quotation Invoices

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
CRM/Civicase/Hook/BuildForm/AddSalesOrderLineItemsToContribution.php
CRM/Civicase/Hook/Post/CreateSalesOrderContribution.php
civicase.php
js/sales-order-contribution.js

This PR adds the logic required to create a contribution for a single quotation, it is a continuation of the work done in this [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/923)
The create contribution popup is displayed but doesn't create a contribution when it's submitted
When the create contribution form is submitted a contribution is created
For each contribution created for a quotaion a new row is inserted into the sales_order_contribution table
This PR simply uses the `CaseSalesOrderLineItemsGenerator` service to generate line items and then passes these line items as a JSON array to [sales-order-contribution.js] which will display the line items in the new contribution form 
and also hide necessary fields. …

BTHAB-33: Implement feature to create contribution for a quotation

---

ang/afsearchContactQuotations.aff.html
ang/afsearchQuotations.aff.html
ang/civicase-features/quotations/directives/quotations-list.directive.html
ang/civicase-features/quotations/directives/quotations-list.directive.js

This PR 
- Makes UI improvements to the quotation list page
- Adds a button to clear the filter fields
- Prevent the browser from navigating user to another page when the date input is clicked
Empty state - blue background
Empty State - no blue background

BTHAB-101: UI Improvements to Quotations list page

---

ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js

This PR improves the UI of the quotation creation page, and also
- Allow creating of contact on the quotation create page
- Update the financial type when a product is selected
- Limit owner contact field to one
The user cannot create a new contact in the client field
The create page  title says `Create Quotations`
The financial type field is not updated to the financial type of the selected product.
The issues mentioned above are resolved

BTHAB-102: UI improvements to quotation create page

---

CRM/Civicase/Form/CaseSalesOrderInvoice.php
CRM/Civicase/Hook/Tokens/SalesOrderTokens.php
templates/CRM/Civicase/MessageTemplate/QuotationInvoice.tpl

This PR 
- Display terms on quotation invoices only if `tax and invoicing`is enabled in CiviContribute settings.
- Ensure a null value in a sales_order doesn't break the token resolving process.
The invoice doesn't get downloaded
The invoice is now downloadable for the same quotation
Also, terms would only show if `tax and invoicing` is enabled in CiviContribute settings.

BTHAB-113: Hide terms when tax and invoicing is disabled

---

ang/civicase-features/quotations/directives/quotations-view.directive.html

Link owner name to owner contact dashboard
The owner name when clicked navigates to the client contact dashboard
Now, the owner name when clicked navigates to the owner contact dashboard

BTHAB-105: Link owner name to owner contact dashboard

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
Civi/Api4/Action/CaseSalesOrder/ContributionCreateAction.php

This pull request introduces the following changes
- Set sales order bulk contribution status to pending
- Ensure that the correct line-item total is displayed for the previous contributions.
Before this pull request, the `CaseSalesOrderLineItemsGenerator.php` file did not include tax rate in the discount line items. 
With this pull request, the tax rate is now included in the calculation of the discount line items total.

BTHAB-119: Ensure salesorder invoice line item totals are correct

---

ang/civicase-features/quotations/directives/quotations-create.directive.js

Ensure quotation financial type can be updated
This happens because when the edit page is to be populated we get the financial type id and the name, but clearing from the UI only clears the id and not the name of the existing financial type.
The solution is to manually clear the financial type name, when its value gets updated from theUI.

BTHAB-129: Ensure quotation financial type can be updated

---

CRM/Civicase/Setup/Manage/CaseTypeCategoryFeaturesManager.php

This PR removes the `Pledges` from the list of case instance features that can be enabled/disabled

BTHAB-38: Remove pledges from supported case instance features

---

ang/afsearchContactQuotations.aff.html
ang/afsearchQuotations.aff.html
ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-list.directive.html
ang/civicase/shared/directives/history-back.directive.js

Introduces UI improvement to the Quotation create and filter screen.
Date filter input fields had not enough spacing.
Enough spacing between the date filter input fields.
The width of the Financial Type field or Product field extends to the width of their content.
The width of the Financial Type field or Product field is now limited.
Clicking on cancel does nothing on the Quotation edit page, this is because the edit page has no previous page to go back to since it is opened in a new tab.
Clicking on cancel on the Quotagion edit page, closes the tab.

BTHAB-109: UI improvement to Quotation create and filter screen

---

ang/civicase-features/quotations/directives/quotations-create.directive.js
ang/civicase-features/quotations/directives/quotations-view.directive.html

This PR redirect the user back to the previous page after editing the quotation and adds the following as extra
- Keep submit button disabled when save is successful
- Fix a typo on the quotation view page

BTHAB-124: Redirect user to Previous page after editing contribution

---

js/sales-order-contribution.js

This pull request contains two fixes to address issues related to the sales order contribution module in CiviCRM.
-  Fixes a problem where the quantity field throws an error due to excess decimal places. 
- Fix an issue where the contribution line items with tax_amount in thousands are not handled appropriately by CiviCRM when creating a contribution, resulting in an incorrect quotation contribution total. 
- Before the fix, the line item quantity field is not limited
-  Contribution line items with tax_amount expressed in money format are not handled appropriately by CiviCRM
- After applying the first fix, the quantity field is now limited to 10 decimal places, preventing any errors caused by excess decimal places. 
- After the money formatter has been removed from the tax_amount and …

BTHAB-130: Fix pre-filled quotation contribution create screen

---

CRM/Civicase/Hook/Tabset/CaseSalesOrderTabAdd.php

This pull request is aimed at displaying the contact Quotation tab only if the Quotation feature is enabled on at least one case instance.
Previously, the contact Quotation tab was displayed regardless of whether the Quotation feature was enabled on any case instance.
With this pull request, the Quotation tab will only be displayed if the Quotation feature is enabled on at least one case instance. This will provide a more accurate representation of the features available to the user and prevent confusion.

BTHAB-126: Conditionally display contact Quotation tab

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
ang/civicase-features/quotations/directives/quotations-contribution-bulk.directive.html
ang/civicase-features/quotations/directives/quotations-contribution-bulk.directive.js
ang/civicase-features/quotations/directives/quotations-view.directive.js

This PR introduces the following changes
- Updates the status field label on the single quotation contribution create screen and uses the quotation status as the default status.
- Sets the default value for status and financial type from the first sales order on the bulk contribution create screen.
Also, the Date on the Quotation view screen is formatted.

BTHAB-155: Update sales order contribution create screen

---

CRM/Civicase/Form/CaseSalesOrderInvoice.php
templates/CRM/Civicase/MessageTemplate/QuotationInvoice.tpl

This PR standardizes the quotation invoice template to match the fonts and spacing of the contribution invoice. A default spacing value is also declared where no format is attached to the message template. 
The key changes are:
- We now use a top margin of 10px and a left margin of 65px as default margin values.
- The preformatted `{domain.address}` token was previously used to display the domain address, now we get the individual address fields and display them in rows. https://github.com/compucorp/uk.co.compucorp.civicase/blob/1d61227a8620ab73fff3fa097f5c09c306da0e11/CRM/Civicase/Form/CaseSalesOrderInvoice.php#L246-L254
- Also, the domain logo image width and height are constrained to 34px and 99px respectively.

BTHAB-43: Update Quotation invoice template

---

CRM/Civicase/Hook/BuildForm/AddQuotationsNotesToContributionSettings.php
templates/CRM/Civicase/Form/CaseSalesOrderInvoiceNote.hlp
templates/CRM/Civicase/Form/CaseSalesOrderInvoiceNote.tpl

This PR adds a helper text to the quotation notes field on the civicontribute component settings page.

BTHAB-153: Add Helper Text to notes field

---

Civi/Utils/CurrencyUtils.php
ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js
ang/civicase-features/shared/services/currency-codes.service.js
templates/CRM/Civicase/SalesOrderCtrl.hlp

This PR introduces the following changes to the quotation create screen:
- [Format displayed total in selected currency format](https://github.com/compucorp/uk.co.compucorp.civicase/pull/942/commits/fe84c53b748cfaa669d2165ec67a87d5cde4597e)
- [Add help text to notes and descrition field](https://github.com/compucorp/uk.co.compucorp.civicase/pull/942/commits/322015525578245e5cffd960b012662ff8bf1267)
- [Use case client as default quotation client](https://github.com/compucorp/uk.co.compucorp.civicase/pull/942/commits/8fe0f127945be8bc634758fbef768bc78a0cd8dc)
It will be noticed that the total field is displayed in money format.
The total field is displayed in money format, notes have a help button, and the client field is prefilled from the current case/prospect client.
The formatting of …

BTHAB-147: Create Quotation UI Update

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
Civi/Api4/Action/CaseSalesOrder/ContributionCreateAction.php
ang/civicase-features/quotations/directives/quotations-contribution-bulk.directive.html
ang/civicase-features/quotations/directives/quotations-contribution-bulk.directive.js

This PR allows users to create contributions for a quotation with no limit on the percentage value. They can create a contribution with a value of 150% as many times as they want. However, if the `remaining` option is selected, we add checks to ensure that the contribution value created is not less than 1. If it will be less than 1, then no contribution will be created.
Users cannot create contributions with a percentage value greater than 100.
Users can now create contributions with a percentage value greater than 100.
Single quotation contribution
Bulk quotation contribution

BTHAB-128: Support contribution quotation with unconstrained percentage

---

CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
civicase.php

This PR rounds off quotation line-item money fields to 2 decimal places.
In addition, this pull request includes moving the percentage icon to the front of the `Add Discount` bulk action link.
Before, the tax_amount input field or the total_price field could have multiple digits after the decimal point.
After, the tax_amount input field and the total_price field would only have a maximum of two digits after the decimal point.
The percentage icon is after the `Add Discount` text
The percentage icon is before the `Add Discount` text

BTHAB-119: Round off quotation line-item money fields to 2 decimal places

---

CRM/Civicase/DAO/CaseSalesOrder.php
ang/civicase-features/quotations/directives/quotations-create.directive.html

This PR updates the sales order entity title and also makes a visual update to the action buttons on the Quotation Create screen
The action buttons are in the panel body.
The action buttons are in the panel footer.

BTHAB-146: Update sales_order entity title

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
ang/civicase-features/quotations/directives/quotations-contribution-bulk.directive.js
js/sales-order-contribution.js

This PR introduces the following three changes
- [Hides remain_balance radio if there's no leftover balance](https://github.com/compucorp/uk.co.compucorp.civicase/pull/951/commits/a838563de3443adcb025d76c7ad11dbb780371b1)
- [Reports numbers of contribution not created to user](https://github.com/compucorp/uk.co.compucorp.civicase/pull/951/commits/9e524a3626ec824f9c9af1eaa6ccc500045c39dd)
- [BTHAB-146: Allow user to add/remove lineitem on quotation contribution screen](https://github.com/compucorp/uk.co.compucorp.civicase/pull/951/commits/5291875ca73e2617537646286a1ac532272a8661) 
The remaining balance option is always shown when creating single contribution
The remaining balance option is hidden if there's no leftover balance
The user cannot add/remove from populated line items when …

BTHAB-146: Hide remain_balance radio if theres no left over balance

---

Civi/Api4/Action/CaseSalesOrder/ContributionCreateAction.php
ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js
templates/CRM/Civicase/MessageTemplate/QuotationInvoice.tpl

This PR introduces the following updates:
- Contribution Create action should accept the financial type ID  of type int or string
- When editing a quotation the title of the page should be 'Edit Quotation'
- Set the owner_id to that of the quotation that is currently being edited.
- Allow the description column in the quotation invoice to be as long as needed.
The page title is 'Create Quotation' when editing a quotation.
The page title is 'Edit Quotation' when editing a quotation.
The description column is limited to 30 words and extra words are truncated.
The description column can be as long as needed.

BTHAB-106: Fix issues on quotation edit screen and template

---

CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
Civi/Api4/Action/CaseSalesOrder/ContributionCreateAction.php
tests/phpunit/Civi/Api4/CaseSalesOrder/ContributionCreateActionTest.php

It is expected that if a quotation has been invoiced in full, a user shouldn't be able to create a new bulk or single invoice using the 'remaining' option; this expectation works as expected for single contributions, but not for bulk contributions.
This PR addresses this issue.
Bulk contribution action is generating a contribution even when the invoice has no remaining balance.
https://github.com/compucorp/uk.co.compucorp.civicase/assets/85277674/f7439c15-4b79-42d3-9bc2-09c59790c144
Bulk contribution action doesn't generate a contribution when the invoice has no remaining balance.
When the remaining option is selected, the application gets the previously created contribution line items, negating their values, and also gets the line items for the quotations, then adds them together to …

BTHAB-170: Fix issue with creating bulk contribution

---

ang/civicase/shared/directives/file-uploader.directive.js
ang/test/civicase/shared/directives/file-uploader.directive.spec.js

This PR sorts the activities Tag list in alphabetical order.
The tag list was sorted by ID
The tag list is sorted by name in Ascending order.

NEUSPRT-239: Sort activities Tag list in alphabetical order

---

CRM/Civicase/Form/CaseSalesOrderDelete.php
ang/afsearchContactQuotations.aff.html
ang/civicase-features.ang.php
ang/civicase-features/quotations/directives/quotations-list.directive.html
ang/civicase-features/quotations/directives/quotations-list.directive.js
js/sales-order-contribution.js
templates/CRM/Civicase/Form/CaseSalesOrderDelete.tpl

This pull request addresses issues where occasionally the contact quotation tab displays quotations belonging to other contacts. This PR ensures that only relevant quotations are displayed.
The previous implementation did not always filter the quotations based on the viewed contact, resulting in the display of irrelevant quotations.
With this pull request, the quotations displayed for a viewed contact are filtered correctly. The code changes ensure that only quotations relevant to the contact are shown.
The contact quotation tab uses the contact ID set in the route parameter `filters="{client_id: routeParams.cid}` to filter quotations that are relevant to the contact being viewed,  if in between tab navigations, the contact ID route parameter is unset or before it is set by the …

BTHAB-200: Display only relevant quotations for the viewed contact

---

CRM/Civicase/Setup/Manage/MembershipTypeCustomFieldManager.php
CRM/Civicase/Upgrader.php
CRM/Civicase/Upgrader/Steps/Step0020.php
managed/CustomGroup_Product_Discounts.mgd.php

This pull request adds
* Membership Type to the `cg_extend_objects` option group so, custom fields can be created against the membership type entity. The value will only be created if it does not exist. 
* Add product discounts custom field to the membership type. 
Feature didn't exist. 
The custom field was created and exported using CiviCRM v4. I added the [check ](https://github.com/compucorp/uk.co.compucorp.civicase/compare/BTHAB-3-workstream...compucorp:uk.co.compucorp.civicase:BTHAB-178-membership-type-custom-field?expand=1#diff-159c7c58abaafe1914ba43096244e5a1cadd5d9df9a93813ca97ea6572f78170R75) to ensure that the entity can only be installed if membership type value existed in `cg_extend_objects `option value.

BTHAB-178: Membeship Type product discounts custom field

---

ang/civicase-features/quotations/directives/quotations-create.directive.html
ang/civicase-features/quotations/directives/quotations-create.directive.js

This PR applies client's membership type's product discount percentage amount to each product line item. 
The feature did not exist. 
[screencast-btha.localhost_9011-2023.09.01-13_54_34.webm](https://github.com/compucorp/uk.co.compucorp.civicase/assets/208713/3f34d6fd-c546-459f-b11a-dbb1080f0fd7)
The product discount amount custom field for membership type was introduced in this [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/965). In this PR, we applied the percentage to membership type percentage to each line item. 
There are few rules that apply to the implementation, which can be described as follows: 
1. The discount percentage amount will set to default zero if selected client does not have any membership. 
2. The discount percentage amount will set to the total of …

BTHAB-204: Apply contact membership type product discount to sale order items

---

Civi/Api4/Action/CaseSalesOrder/SalesOrderSaveAction.php

This PR adds the logic to prevent deleting SaleOrderLine objects when there isn't any ID attaches to the SaleOrder['items'] which will cause the error as we are passing an empty array to the query. 
This scenario is likely to happen when the API caller want to update a sale order/quotation with a new list of product items, where the product items have not been created yet.

BTHAB-180: Only perform delete if id line item is not empty

---

.github/workflows/unit-test.yml
CRM/Civicase/Helper/CaseCategory.php

This PR fixes an issue in the extension that prevents the case entity from being imported using the `CSV import` extension
Import hangs and the error below is thrown
```
TypeError: Illegal offset type in isset or empty in civicrm_api3_generic_getvalue() (line 338 of /Applications/MAMP/htdocs/cst/profiles/compuclient/modules/contrib/civicrm/api/v3/Generic.php).
```
Import is successfully completed
This error happened because the `CaseType.getvalue` endpoint expects the return param to be a string type and not an array

CST-334: Fix case entity not being imported

---

.github/workflows/unit-test.yml
ang/civicase/shared/directives/file-uploader.directive.html
ang/civicase/shared/directives/file-uploader.directive.js
ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js

At the moment when uploading a file to case using:
an activity will be created with a data that = today's date by default. 
A new field called  "Received Date"  is added to the case file upload screen, which allow users to change the activity date if they wish, if no value is selected on such field, then it will use today's date by default :
- Demo 1: using past date:  
- Demo 2: using future date:  
- Demo 3: Not selecting any date:

NEUSPRT-222: Add date field to file upload screen

---

CRM/Civicase/Form/CaseSalesOrderInvoice.php
CRM/Civicase/Hook/BuildForm/AttachQuotationToInvoiceMail.php
CRM/Civicase/Hook/alterMailParams/AttachQuotation.php
CRM/Civicase/Service/CaseSalesOrderInvoice.php
civicase.php
templates/CRM/Civicase/Form/Contribute/AttachQuotation.tpl

This PR adds a new checkbox option that allows a user to attach a quotation invoice to a contribution invoice mail.
There's no option to attach a quotation invoice to a contribution invoice mail
There's an option to attach a quotation invoice to a contribution invoice mail
When the `Attach Quotation` box is checked, the quotation invoice is attached to the email.
When the `Attach Quotation` box is not checked, the quotation invoice is not attached to the email.
Also, the checkbox doesn't appear on contributions not linked to a quotation.
The [https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterMailParams/](alterMailParams) is used to attach the quotation invoice to the outgoing contribution email.

BTHAB-182: Attach quotation invoice to contribution mail

---

CRM/Civicase/Hook/BuildForm/AttachQuotationToInvoiceMail.php
CRM/Civicase/Hook/alterMailParams/AttachQuotation.php
CRM/Civicase/Service/CaseSalesOrderInvoice.php
CRM/Civicase/Upgrader/Steps/Step0019.php
Civi/Api4/Action/CaseSalesOrder/SalesOrderSaveAction.php
civicase.php
js/invoice-bulk-mail.js
managed/SavedSearch_Civicase_Quotations.mgd.php
templates/CRM/Civicase/Form/Contribute/AttachQuotation.tpl

This PR adds `Send invoice by email` in the bulk action menu for bulk invoice sending
The `Send Invoice by email` action doesn't exist in the bulk action in the contribution search kit view
The `Send Invoice by email` action exists in the bulk action in the contribution search kit view
With the `invoice-helper` extension installed, the `Template field` is displayed
This functionality uses the CiviCRM `CRM_Contribute_Form_Task_Invoice` class to send the email, to avoid having to duplicate the code, this also allows us to keep other customizations provided by third-party extensions like `invoice-helper` to the bulk contribution email screen.
The caveat is that `CRM_Contribute_Form_Task_Invoice`  class is meant to redirect to a contribution view after sending the email as hardcoded from the …

BTHAB-206: Add send invoice by email in bulk action menu for bulk invoice sending

---

CRM/Civicase/Hook/Post/CaseSalesOrderPayment.php

This PR fixes the issue with the `CaseSalesOrderPayment` hook preventing users from recording a contribution with an empty sales order field.
Contribution cannot be recorded with an empty sales order field.
Contribution can be recorded with an empty sales order field.

CIWEMB-514: Fix not able to create non-salesorder contribution

---

CRM/Civicase/Hook/BuildForm/AddEntityReferenceToCustomField.php

This pull request straightforwardly ensures that the hook for converting contribution case/quotation custom fields into entity reference fields will exclusively execute within the context of the contribution create/update form.
This is needed because the entity reference fields only needs to be displayed in the contribute create and update form.

CIWEMB-525: Ensure hook will only run where expected

---

CRM/Civicase/Hook/BuildForm/AttachQuotationToInvoiceMail.php
CRM/Civicase/Hook/alterMailParams/AttachQuotation.php
ang/civicase-features/quotations/directives/quotations-create.directive.js
templates/CRM/Civicase/Form/Contribute/AttachQuotation.tpl

This PR ensures the membership discount information for case clients when creating quotations from the application screen, and also ensures Quotation invoices will be attached by default to invoice mail.
Membership discount is not working when a Quotation is created from  **Application**
https://github.com/compucorp/uk.co.compucorp.civicase/assets/85277674/9ad9d889-b48d-4531-98a1-85350ff235be
Membership discount is working when a Quotation is created from  **Application**
Quotation will not be attached by default
Quotation will is attached by default

BTHAB-257: Fetch discount information for case client

---

CRM/Civicase/Hook/Pre/DeleteSalesOrderContribution.php
CRM/Civicase/Service/AbstractBaseSalesOrderCalculator.php
CRM/Civicase/Service/CaseSalesOrderContributionCalculator.php
CRM/Civicase/Service/CaseSalesOrderOpportunityCalculator.php

The payment and invoice statuses were being calculated in accordance to just invoiced amount without considering the quoted amount and the calculations previously also took into account the deleted invoices which were resulting in incorrect statuses calculations
These were the issues previously
- Quotation's payment status changed to fully paid upon paying total quotation amount partially
- Quotation's payment status did not change to overpaid even after paying more than quoted amount
- Quotation's payment status did not change to fully paid even after paying in full
- Deleting a invoice did not change the payment and invoice statuses correctly
All issues described above are fixed and now quotation's payment and invoice statuses are being calculated correctly after creation, deletion and …

BTHAB-271: Fix Invoice And Payment Status Bugs For Quotations

---

managed/CustomGroup_Product_Discounts.mgd.php

Restrict user from submitting new membership type form if product discount amount field includes string characters.
User was able to submit the form with alphabets typed in the field.
An error is shown to the user and user is unable to submit the form if product discount amount field contains alphabets.

BTHAB-253: Fix Validation For Discount Amount Field

---

ang/civicase/shared/directives/file-uploader.directive.js

Stop activity creation while uploading files of size 0.
If any of the uploaded files has size equals to 0, we showed error to the user but still acivity was created.
If any of the uploaded files is 0 in size then along with showing the error we dont create any activity as well.

NEUSPRT-284: Restrict Activity Creation With File Upload Of Size 0

---

CRM/Civicase/Service/CaseSalesOrderContributionCalculator.php
Civi/Api4/Action/CaseSalesOrder/SalesOrderSaveAction.php

This PR removes unnecessary APIv4 backend permission checks, that prevent users from accessing the API methods via screens like webforms and others.

BTHAB-248: Remove unnecessary API 4 backend permission checks

---

ang/civicase-base/directives/tags-selector.directive.js

This pr disables the the non selectable tags while creating the file upload activity.

NEUSPRT-295: Disable Non Selectable Tags In File Upload Activity

---

CRM/Civicase/Hook/ValidateForm/RemoveEmptyTargetContactFromActivity.php
civicase.php

Civi core errors out if an empty string is posted target contact id while editing file upload activity. This pr resolves the bug by removing the target contact id param from activity form if its submitted value is empty string.

COMCL-333: Fix Bug With Empty Target Contact For File Upload Activities

---

CRM/Civicase/Hook/BuildForm/RefreshInvoiceListOnUpdate.php
ang/civicase-features/invoices/directives/invoices-list.directive.html
civicase.php

This pr fixes following two issues in invoice list page for a case
- Fixes the style of **no record found** message when there are no invoices, to match the styles with other pages.
- Automatically refresh the invoice list after an update has been made to any of the invoices to reflect the changes made
The **no record found** message appeared in blue background
Secondly the invoice list did not refreshed automatically after updating an invoice hence user has to do a page reload to see the changes that he has just made.
The **no record found** message styling has been fixed
Secondly whenever an invoice is updated the invoice list gets refreshed automatically.

BTHAB-158 Invoice list Fixes

---

CRM/Civicase/Service/CaseRoleCreationPostProcess.php

When creating a case, with roles Civicase has an event listener that creates a new activity record `Assign case Role` for the contact creating the case.
But this activity shouldn't be created when an anonymous user submits the case via a web form or other means.
In this PR we've simply added a check to see if a user is logged in before attempting to create the activity.

CPO-147: Allow Anonymous User to submit case with roles via webform

---

CRM/Civicase/Hook/BuildForm/AttachQuotationToInvoiceMail.php
Civi/Api4/CaseSalesOrder.php
Civi/Api4/CaseSalesOrderLine.php
ang/civicase-features/quotations/directives/quotations-create.directive.js
civicase.php
templates/CRM/Civicase/Form/Contribute/AttachQuotation.tpl

This PR introduces two new changes 
-  Ensure discount alert is displayed only if a discount is applied
- Redirect the quotation invoice receipt task to the quotation list, instead of the contribution search page that shows an error.
https://github.com/compucorp/uk.co.compucorp.civicase/assets/85277674/7774076e-9fe2-40ce-971a-26d0df1f732e

BTHAB-257: Quotation and quotation invoice fix

---

CRM/Civicase/Form/CaseSalesOrderContributionCreate.php
CRM/Civicase/Form/CaseSalesOrderInvoice.php
CRM/Civicase/Hook/BuildForm/AddCaseCategoryFeaturesField.php
CRM/Civicase/Hook/NavigationMenu/AlterForCaseMenu.php
CRM/Civicase/Hook/Post/CaseSalesOrderPayment.php
CRM/Civicase/Hook/Post/CreateSalesOrderContribution.php
CRM/Civicase/Hook/Pre/DeleteSalesOrderContribution.php
CRM/Civicase/Hook/Tabset/CaseSalesOrderTabAdd.php
CRM/Civicase/Hook/Tokens/SalesOrderTokens.php
CRM/Civicase/Hook/alterMailParams/AttachQuotation.php
CRM/Civicase/Service/CaseSalesOrderOpportunityCalculator.php
CRM/Civicase/Service/CaseTypeCategoryFeatures.php
Civi/Api4/Action/CaseSalesOrder/ContributionCreateAction.php
ang/civicase-features.ang.php
api/v3/Case/Getrelations.php
api/v3/CaseSalesOrder/Getlist.php

This PR removes unrequired APIv4 permission checks, Because some of these methods have the tendency of being called by unauthorized users, i.e. via web form submission, the permission when checked will cause an unauthorized error to be thrown.
Non-civicrm user is not able to register for an event.
Non-civicrm user is able to register for an event.

COMCL-505: Remove unrequired APIv4 permission checks

---

.github/workflows/unit-test.yml
CRM/Civicase/Hook/BuildForm/AddCaseActivityDateFormatToDateSettings.php
CRM/Civicase/Hook/BuildForm/FormatCaseActivityDateFormat.php
CRM/Civicase/Hook/PostProcess/SaveCaseActivityDateFormat.php
ang/civicase/activity/card/directives/activity-card-big.directive.html
ang/civicase/activity/card/directives/activity-card-long.directive.html
ang/civicase/activity/card/directives/activity-card-short.directive.html
ang/civicase/activity/panel/directives/activity-panel.directive.html
ang/civicase/shared/directives/file-uploader.directive.html
ang/civicase/shared/directives/file-uploader.directive.js
api/v3/Activity/Getall.php
civicase.php
js/modify-activity-date.js
templates/CRM/Civicase/Form/CaseActivityDateFormat.tpl

In this PR we allow the users to customize the activity date format, which will be used when displaying activity date in the CiviCase panel.
Also, we have exposed the time field when uploading a file in CiviCase
- The CiviCase activity feeds use a hardcoded date format 
- The user cannot change the time field when uploading a file
- The CiviCase activity feeds use the user-specified date format from the Date settings.
- The user can change the time field when uploading a file
The settings name is `civiCaseActivityDateformat`

NEUSPRT-324: Allow user to customize activity date format

---

CRM/Civicase/Hook/Permissions/CaseCategory.php

This pr adds a new permission that would allow users to modify cases bu submitting webforms.
No such permission existed.

FOSFAB-316: Add New Permission For Modifying Cases Through Webforms

---

civicase.php

This pr updates the name of case type entity in entity types hook due to the changes in civicrm core.
In [this](https://github.com/civicrm/civicrm-core/commit/64fc4923319ba4f5ce0a69fa1c1392d8178173a1) commit the entity definitions were moved from xml files to entity.php files and in this process the name of case type entity was changed from 'CRM_Case_DAO_CaseType' to 'CaseType'. BUt since we have not yet upgraded so this pr supports both the entity names for now that will allow this extension to work with our current civicrm version(5.51.3) and with version 5.75.0 as well.

COMCL-603: Update Case Type Entity Name

---

ang/civicase-base.ang.php
ang/civicase.ang.php

This pr corrects the path for visual bundle assets to be compatible with civicrm version 5.75.0

COMCL-603: Correct visual bundle assets path

---

CRM/Civicase/Hook/BuildForm/AddQuotationsNotesToContributionSettings.php

This pr fixes an issue that occurs due to upgrade to civicrm version 5.75.0 because of some structural changes to civicrm core form class and it restricted the user from accessing civi contribute settings page.

COMCL-644: Fix contribution settings page

---

civicase.php

This PR addresses an issue where users are unable to create a new communication type activity under the contacts form New Activity. The problem occurs due to the Draft button being added to the New Activity form, which introduces a new button ID that is not accounted for in CiviCRM's form validation process. https://github.com/compucorp/uk.co.compucorp.civicase/blob/eaefbbdf9984c377db93553999496e849c2cad09/CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php#L77-L91
After adding the button in the hook above, the new button ID is not catered for in CiviCRM https://github.com/civicrm/civicrm-core/blob/920907161e991952f07eb4b73910886022e8c414/templates/CRM/Core/Form/RecurringEntity.tpl#L209 where submit buttons are not expected to validate unchanged elements.
Users were unable to create …

COMCL-640: Ensure submit buttons will validate the form properly

---

ang/civicase-features/quotations/directives/quotations-list.directive.html

This pr fixes the styling of bulk action dropdown menu for quotations tab.

COMCL-706: Fix Menu Styles

---

api/v3/Case/Getrelations.php

This pr fixes the other relationship tab on case details page as the relationships were not getting loaded due to an error in an api.

COMCL-716: Fix Other Relationship Tab On Case Details Page

---

CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
js/sales-order-contribution.js

In this PR we have added a small delay between when the contribution page loads and when the quotation line items are populated, this is necessary because the quotation line items can be cleared by other extensions like [Financeextras](https://github.com/compucorp/io.compuco.financeextras) or [lineitemedit](https://lab.civicrm.org/extensions/lineitemedit) that initializes the line item with default values.
The Quotation items
Creating 100% contribution:
Occasionally the contribution line item total shows as ZERO or incorrect values.
The contribution line item total shows the correct values.

BTHAMM-15: Add custom delay before updating line item total

---

ang/civicase/contact/services/contact.service.js

This pr fixes a bug that restricted the auto filling of owner field on create quotation form.

COMCL-701: Fix Auto Filling Of Owner Id Field On Create Quotation Form

---

CRM/Civicase/Hook/BuildForm/AddSalesOrderLineItemsToContribution.php
CRM/Civicase/Hook/alterContent/AddSalesOrderLineToContribution.php
civicase.php
js/sales-order-contribution.js

This PR set the sales order line items from the backend using PHP, instead of the frontend which was causing issues with the total amount displaying incorrect values.
Previously:
We pass the user-supplied percentage to the frontend JavaScript and perform the necessary computations there. However, this approach is causing conflicts with other extensions, such as finance-extras (due to changes in the contribution form) and lineitemedit, which also modify line items.
In this PR:
We perform all percentage computations on the backend and prepopulate the form items using the [altercontent](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterContent/) hook.
The total amount value resets to zero when the financial type or any value changes on the form.
The total amount always display …

BTHAMM-31: Set sales order line items from backend

---

CRM/Civicase/Hook/PageRun/AddCaseTypeCategoryToCache.php
ang/civicase.ang.php
civicase.php

This pr fixes the case type category terms usages. Currently awrads and prospect also uses the term 'cases' instead of awards and prospect on dashboard pages.

COMCL-707: Fix Case Type Category Terms

---

CRM/Civicase/Settings.php
ang/civicase.ang.php

This pr fixes an issue with case permissions which led to permissions being cached and did not change when the user role was changed.
For example the user without delete permission was able to see the delete case option
Previously the case actions were being provided as part of civicase.ang.php which is read only once and then its cached for the rest of the users. So if a user with admin permission uses the site first then all other non admin users will also see the same options on the cases screens. This pr moves the cases actions and other settings to a settings factory which leads to refreshing the settings for each page load.

COMCL-730: Fix Case Permissions Issue

---

CRM/Civicase/Hook/BuildForm/AddSalesOrderLineItemsToContribution.php
CRM/Civicase/Hook/alterContent/AddSalesOrderLineToContribution.php
CRM/Civicase/Service/CaseSalesOrderLineItemsGenerator.php
CRM/Civicase/Service/CaseSalesOrderOpportunityCalculator.php
civicase.php
js/contribution-entityref-field.js
js/sales-order-contribution.js
templates/CRM/Civicase/Form/CaseSalesOrderContributionCreate.tpl

This PR reapplies this PR to the 4.1.1 branch with CiviCRM 5.51
https://github.com/compucorp/uk.co.compucorp.civicase/pull/1037
https://github.com/compucorp/uk.co.compucorp.civicase/pull/1033

BTHA-188: Fix quotes to order feature issues

---

CRM/Civicase/APIHelpers/CustomValues.php

This pr fixes a bug due to which the value of a custom field for a case was not displayed correctly.
The value of custom field was getting replaced with contact names.
The actual value of a custom field is displayed.

COMCL-754: Fix Custom Field Values For Cases

---

CRM/Civicase/Form/Report/BaseExtendedReport.php
CRM/Civicase/Form/Report/Case/CaseWithActivityPivot.php
CRM/Civicase/Form/Report/ExtendedReport.php

This pr fixes the cases with activity pivot report.
The report did not load at all due to incompatibilities with new civicrm version

COMCL-757: Fix Cases With Activity Pivot Report

---

CRM/Civicase/Hook/BuildForm/HandleDraftActivities.php

This pr fixes the saving of pdfs for cases as currently the pdfs are not getting attached to cases when user creates a pdf on a case.

COMCL-792: Fix Pdf Creation For Cases

---

civicase.php

Before this PR there was an issue with Print / Merge Document bulk action for "CiviCase" and "CiviCRM User" roles, where the Print / Merge Document modal doesn't open properly

COMCL-752: Resolve issue with Print / Merge Document bulk action for "CiviCase" and "CiviCRM User" roles

---

CRM/Civicase/Form/Report/ExtendedReport.php

This pr fixes an issue which restricted the user to generate pivot reports. The issue was caused by using a removed old function from civicrm core.

COMCL-835: Fix Pivot Report Generation

---

CRM/Civicase/Hook/Post/CreateSalesOrderContribution.php
ang/afsearchQuotations.aff.html
ang/civicase-features/quotations/directives/quotations-list.directive.js
js/sales-order-contribution.js

This PR resolves the following issues
- Users not able to clear the applied filter on the quotation search widget
- Users not being able to link a contribution with the associated quotation
**Filter not cleared after clicking on the clear button**
https://github.com/user-attachments/assets/59b4539b-a9ca-494b-9aee-8d2cdaf81956
**Contribution not linked with quotation**
https://github.com/user-attachments/assets/d148c42a-aa9b-4041-bc8b-8352e70721a0

COMCL-703: Resolve quotation link and search filter issues

---

CRM/Civicase/Hook/Post/LinkCase.php
ang/civicase/case/actions/services/new-link-cases-case-action.service.js
ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.html
ang/civicase/case/details/linked-cases-tab/directives/case-details-linked-cases-tab.directive.js
civicase.php

This pr adds a functionality for users to link two cases while creating a new case. Two new buttons are added on linked cases tab to achieve this functionality.

FOSFAB-320: Add Functionality To Link Cases While Creating A New Case

---

CRM/Civicase/APIHelpers/CustomFieldFilter.php

This pr makes the custom fields filters to work with mysql8 as well. Currently the api for fetching cases results in an error on mysql 8 when used with sny custom field filter.
As explained [here](https://stackoverflow.com/questions/59998409/error-code-3685-illegal-argument-to-a-regular-expression) the regular expression engine was changed in mysql8 so now regular expression syntax has changed.

NEUSPRT-405: Fix issues with mysql 8 compatibility

---

CRM/Civicase/Hook/Post/LinkCase.php

This pr fixes an issue due to which the users were not able to use submit credit card refund option for a stripe contribution.
The issue was caused by the fact that when a stripe refund is created it fires a post hook but the third parameter is a string instead of int. In CRM_Civicase_Hook_Post_LinkCase class the third parameter for the hook was type hinted as int so it errored out and was not letting the user to complete a refund

CIVIMM-277: Fix Stripe Refund

---

CRM/Civicase/Hook/BuildForm/AttachQuotationToInvoiceMail.php
CRM/Civicase/Hook/Pre/DeleteSalesOrderContribution.php
CRM/Civicase/Hook/alterMailParams/AttachQuotation.php

Handle Opportunity details custom field being disabled
In the system we allow users to add quotation invoices to contribution invoices, and we use API4 to check if the contribution has a quotation in the logic, but if the quotation custom field is disabled this API4 request fails. In this PR we have placed the API request in a try-catch block to prevent it from throwing errors.

CSTMM-110: Handle Opportunity details custom field being disabled

---

.github/workflows/unit-test.yml
CRM/Civicase/Helper/Category.php
CRM/Civicase/Hook/PostProcess/SaveCaseCategoryCustomFields.php
CRM/Civicase/Service/CaseCategoryMenu.php

Before this PR, when a user updates the label of a case type category, the menu labels are not updated; instead, they keep the label they were set to on creation.

NEUSPRT-456: Update casetype category menu label post update

---

managed/CustomGroup_Cases_OpportunityDetails.mgd.php

Currently the case opportunity details custom group managed entity is setup with an update option of **always** which means that the if any client disables it then it will be automatically enabled upon civicrm cache clearance. To fix this issue this PR changes the update option to ** unmodified** which will only update the entity if it has not been edited by the client.

NEUSPRT-447: Fix Case Opportunity Managed Entity

---

ang/civicase/case/list/directives/case-list-table.directive.html

This PR ensures filters select display option texts appropriately

CIVIMM-302: Ensure filters display appropriately

---

CRM/Civicase/Settings.php

This PR fixes the issue where case dashboard breadcrumb is navigating to CiviCase dashboard rather than Awards, Prospects, etc. dashboard, this is fixed by reseting the breadcrumbs when building the case type cateogry settings.
BreadCrumbs shows the default links
BreadCrumbs links corresponds to the current case type category

CSTMM-149: Reset breadcrumbs when building settings

---

js/create-pdf-form.js

When a user creates a PDF letter and clicks the **Preview** button, CiviCRM currently treats it as a **Download** action. As a result:
* An activity record is created.
* The generated file is not marked with `_preview` in its filename.
This pull request resolves the issue by renaming the button’s action name to `_qf_PDF_submit_preview`. This allows core to properly recognise it as a preview action, not a download.

NEUSPRT-438: Prevent creating activities when previewing  PDF letter

---

CRM/Civicase/APIHelpers/ActivityQueryApi.php
api/v3/Activity/Copybyquery.php
api/v3/Activity/Movebyquery.php

This PR fixes a bug in moving/copying of activities to cases due to which the target contacts of activities were not being carried over while  moving/copying of activities.

FEMSSPRT-399: Copy Target Contacts While Moving Or Copying Activities To A Case

---

CRM/Civicase/Form/CaseWebforms.php

This PR fixes an error that restricted the user from accessing case webform page.
The page resulted in an error
The page is accessible
Any form that extends admin from and without its own preprocess method have to implement a method by the name of getDefaultEntity which was missing from this form and it has been added now. This issue existed from very long time but went unnoticed as this page is not used very frequently.

CIVIPLMMSR-474: Fix Case Webform Page

---

CRM/Civicase/Hook/Permissions/CaseCategory.php
CRM/Civicase/Hook/Permissions/ExportCasesAndReports.php

CiviCRM 5.0+ uses a newer format for declaring permissions. As of Civi 5.71, the old format is deprecated.

CIVIMM-293: Fix permission label
