compucorp/uk.co.compucorp.civicase

- CRM/Civicase/Page/ActivityFiles.php
- xml/Menu/civicase.xml
This PR adds a page link that allows downloading all the files associated with an Activity in a single zip file.
A new page was added that retrieves the files for an activity and groups them in a single zip file that can be downloaded by the users.
The structure of the class is divided into the following units:
```php
private static function validateActivityId($activityId) {
if (empty($activityId)) {
http_response_code(404);
CRM_Utils_System::civiExit();
}
}
```
```php
private static function getDestinationPath() {
$config = CRM_Core_Config::singleton();
return $config->customFileUploadDir;
}
```
```php
private static function getActivityFilePaths($activityId) {
$filePaths = [];
$activityFiles = CRM_Core_BAO_File::getEntityFile('civicrm_activity', $activityId);
foreach ($activityFiles as …
```
> C51-41: Add download all activity files page link

- ang/civicase/CaseListTable.js
Scrolling to the top of the screen when Case Card is clicked.
> C51-176: Scroll to top when case is clicked

- ang/civicase/ActivityActions.html
- ang/civicase/ActivityActions.js
- ang/civicase/ActivityCard--Menu--Feed.html
- ang/civicase/ActivityFeed.html
- ang/civicase/ActivityFeed.js
- ang/civicase/ActivityFilters.html
- ang/civicase/ActivityFilters.js
As part of this PR the Delete Feature of Bulk Actions has been developed.
1. Created new `ActivityActions` directive for this feature.
Note: In future all the Activity Menu needs to be refactored to have a common action dropdown, but we dont have time for that now.
2. Now `ActivityFilter` accepts `selected-activities` instead of `selected-activities-count`, as it needs list of activities to do actions on.
> C51-116: Activity Bulk Action - Delete Feature

- info.xml
This PR updates the `info.xml` file to prepare the develop branch for the alpha5 release.
> C51-419: info.xml update for alpha5 release

- info.xml
This PR updates the `info.xml` file to prepare the develop branch for the alpha6 release.
> C51-420: info.xml update for alpha5 release

- ang/civicase.ang.php
- ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
- ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
- ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
- api/v3/Activity/Getactionlinks.php
- info.xml
* C51-417 - Configurable 'Add Cases' Button on Contact
* CATL-1069 - If any case role is assigned in a Case, they are assigned as the case Manager ignoring the original role. This bug is fixed.
> Release v1.0.0-alpha7

- ang/civicase/case/search/directives/search.directive.html
Test Auto Deployment using Slack and Compubot
> RSE-215: Test Auto Deployment using Slack and Compubot

- ang/civicase/case/factories/get-case-query-params.factory.js
- ang/test/civicase/case/actions/directives/case-actions.directive.spec.js
- ang/test/civicase/case/actions/services/print-merge-case-action.service.spec.js
- ang/test/civicase/case/details/directives/case-details.directive.spec.js
- package-lock.json
As part of this PR, the "Payment Information" has been added to the Financial Information Custom Field Block.
`case_type_id.case_type_category` field is being fetched now, which will be used by the Prospect Extension https://github.com/compucorp/uk.co.compucorp.civicrm.prospect/pull/29.
Also unit tests got broken in last PR, which are fixed now.
> RSE-198: Add Payment Info

- ang/civicase/activity/card/directives/activity-card-big.directive.html
- ang/civicase/activity/card/directives/activity-card-long.directive.html
- ang/civicase/activity/card/directives/activity-card.directive.js
This PR uses the `ts` function for word replacements for a few screens missed on the other PR. #238
> RSE-271: Case Category Word Replacements.

- CRM/Civicase/Hook/PreProcess/CaseCategoryCustomFieldsSetDefaultValues.php
This PR fixes an issue with a deprecated function based on changes made in the last PR.
The function `CRM_Core_BAO_Cache::getItem` was replaced with equivalent container function `Civi::cache('cacheKey')->get` but on develop site there is an error when trying to save a prospect.
- The new equivalent Container function for the Custom data cache was only introduced in [5.17](https://github.com/civicrm/civicrm-core/blob/5.17/CRM/Utils/System.php#L1444) and does not exist in prior Civicrm versions. Development site runs on 5.16.
- To fix this because some sites will run civicrm on version < 5.17 with Civicase extension, a function was created that uses the old way of retrieving the cached data when the Service does not exist and to use the new method when the service exists.
> RSE-271: Fix issue with deprecated function.

- ang/civicase/activity/actions/services/delete-activity-action.service.js
- ang/civicase/activity/actions/services/move-copy-activity-action.service.js
- ang/civicase/activity/actions/services/tags-activity-action.service.js
Syntax mistakes has been fixed.
> BASW-517: Syntax Fixes

- ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
The label says 'Select Coantact' where it should say 'Select Contact'.
https://s.nimbusweb.me/share/3310548/a2qbsv6ipff4e6n3r35u
The label is now fixed.
> CATL-1123: Fix Incorrect Label In Case Roles

- CRM/Civicase/Hook/addDependentAngularModules.php
- ang/civicase.ang.php
This PR merges in the work done in https://github.com/compucorp/uk.co.compucorp.civicase/pull/278 to the Awards Epic branch.
> RSE-467: Use Hook to allow adding dependent modules of Civicase

- ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
- ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
This PR contains the commits from https://github.com/compucorp/uk.co.compucorp.civicase/pull/288 since they were merged before passing QA tests and had to be removed from master.
For more information please refer to the original PR.
> CATL-1142: Hide deleted cases from contact's case tab

- ang/civicase-base/services/case-status.service.js
- ang/civicase-base/services/case-type.service.js
- ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
- ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.js
- ang/civicase/case/search/directives/search.directive.html
- ang/civicase/case/search/directives/search.directive.js
- ang/civicase/contact-case-tab/directives/contact-case-tab.directive.js
- ang/test/civicase-base/services/case-status.service.spec.js
- ang/test/civicase-base/services/case-type.service.spec.js
- ang/test/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.spec.js
- ang/test/civicase/case/search/directives/search.directive.spec.js
- ang/test/civicase/contact-case-tab/directives/contact-case-tab.directive.spec.js
- ang/test/karma.conf.js
This PR contains the commits from https://github.com/compucorp/uk.co.compucorp.civicase/pull/290 since they were merged before passing QA tests and had to be removed from master.
For more information please refer to the original PR.
> CATL-1128: Fix open case details

- info.xml
**Improvements:**
1. Added a new hook using which angular modules defined in other extensions can add `civicase` module as a dependency.
2. Added a new angular module `civicase-base`, which is useful to share angular features with other extensions.
3. For Email/PDF Letter Activity types, "Resume Draft" activity action is added. Also the same button is added to the Activity Details Panel.
**Fixes:**
1. Fixed dropdown styles across the application.
2. Deleted cases were shown on the Contact Case tab, which is fixed.
3. Unnecessary Box Shadows are removed from the Case Details and Activity Feed pages.
4. When clicking on "Go To Case" from Contact Case tab, there was a bug which resulted in case details not being loaded, which is fixed.
5. Saving a PDF letter as a draft, produced an error, …
> CPS-14: Release v1.0.0-beta.1

- ang/test/civicase/activity/feed/directives/activity-month-nav.directive.spec.js
- ang/test/civicase/case/search/directives/search.directive.spec.js
- ang/test/mocks/data/month-nav.data.js
> CPS-45: Fix unit tests

- info.xml
**Improvements:**
1. Tooltip text for "Delegated/All" has been improved for the Activity Feed.
**Fixes:**
1. There was a bug while printing activities from Manage Case page, where some of the activities were not shown. This has been fixed.
2. Styling issues inside Activity Details Panel has been fixed.
3. After creating a new case, the browser redirection to the Manage Case page, had some bugs, which resulted in console errors, its been fixed now.
**New Features:**
1. "Add Activity" button has been added to Contact's Activity tab.
2. Added ability to add custom buttons inside the Dashboard's Overview section from other extensions.
3. Added ability to add custom items(with custom markup) inside Dashboard's Action Bar.
4. CiviCRM dashboard has been replaced with a tabbed view, where the …
> CPS-50: Release v1.0.0-beta.2

- ang/civicase/case/directives/case-overview.directive.html
- ang/civicase/dashboard/directives/dashboard-tab.directive.html
- ang/civicase/dashboard/directives/dashboard-tab.directive.js
- ang/civicase/shared/directives/panel-query.directive.js
- ang/test/civicase/dashboard/directives/dashboard-tab.directive.spec.js
- ang/test/civicase/shared/directives/panel-query.directive.spec.js
As part of this PR, the following issues are fixed.
The Case Overview, was not showing the number of cases in the breakdown.
**Before**
**After**
**Technical Details**
In `case-overview.directive.html`, changed the implementation.
Previously `ng-repeat="(ctid, caseType) in caseTypes"` was used. But `ctid` did not hold any value. 
So the following line did not work
`{{ summaryData[ctid][status.value] || '0' }}`
So it is changed to 
```html
ng-repeat="caseType in caseTypes"
...
{{ summaryData[caseType.id][status.value] || '0' }}
```
When "My Awards" filter was applied, Activities and Cases from other cases was visible in Dashboard.
**Before**
**After**
**Technical Details**
Previously, when the `My Awards` filters where applied, the original API request to fetch the details of each panel of …
> RSE-363: "My Awards" filter bug fixes

- CRM/Civicase/Hook/PermissionCheck/CaseCategory.php
Currently the Award Manager cannot print Activity reports or view an activity that is not of type Award review on the Manage Awards page. These pages are not covered by the case category permissions logic, so this PR adds the pages and logic needed to replace the permission check with the equivalent Case category permission.
- Issue described above exists.
- The Activity reports and Activity page are added to the list of pages that require case category permission checks.
> RSE-939: Fix Case Category Permission Issues With Print Report and Activity Page.

- ang/test/mocks/data/relationship-type.data.js
This is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/68
As part of this PR, Relationship Mock data has been added, which is used for javascript unit testing.
> RSE-678: Relationship Type mock data

- ang/test/mocks/data/group.data.js
This is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/72
As part of this PR, Group Mock data has been added, which is used for javascript unit testing.
> RSE-672: Contacts mock data

- tests/backstop_data/Readme.md
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-maximize.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-priority-dropdown.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/activity-detail-status-dropdown.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-add-tag.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-copy-to-case.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-delete.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-move-to-case.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions-remove-tag.js
- tests/backstop_data/engine_scripts/puppet/activity-feed-panel/bulk-actions.js
- tests/backstop_data/scenarios/activity-feed-panel.json
This PR add tweaks some backstop js scenarios and add some new ones
* Filter scenario now have one of the filter dropdown opened
* Bulk actions scenario now have all items selected and bulk action dropdown opened
* Activities Feed Panel - Bulk Actions - Move to case
* Activities Feed Panel - Bulk Actions - Copy to case
* Activities Feed Panel - Bulk Actions - Add tags
* Activities Feed Panel - Bulk Actions - Remove tags
* Activities Feed Panel - Bulk Actions - Delete activities
* Activities Feed Panel - Selected Activity - Details - Maximise
* Activities Feed Panel - Selected Activity - Details - Status Dropdown
* Activities Feed Panel - Selected Activity - Details - Priority Dropdown
* Activities Feed Panel - Bulk Actions - Move to case
* Activities Feed Panel - Bulk Actions - Copy to …
> CATL-1252: [Backstop JS] - Activity panel feed - Add screens for activity feed panel section

- ang/civicase/case/list/directives/case-list-table.directive.html
- gulp-tasks/backstopjs.js
- tests/backstop_data/Readme.md
- tests/backstop_data/engine_scripts/puppet/contacts/contact-dashboard.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-change-status.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-delete.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-edit-tags.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-email-case-manager.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-export.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-link.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-lock.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown-print-merge.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/action-dropdown.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/bulk-actions.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-dropdown.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-client.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/people-tab-add-case-role-to-non-client.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/sort-dropdown.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/status-dropdown-change-status.js
- tests/backstop_data/engine_scripts/puppet/manage-cases/status-dropdown.js
- tests/backstop_data/engine_scripts/puppet/utility.js
- tests/backstop_data/scenarios/activity-feed-panel.json
- tests/backstop_data/scenarios/dashboard.json
- tests/backstop_data/scenarios/manage-cases.json
This PR fixes some broken scenarios and add remaining screens for manage cases and other issue on manage screen page
* Manage Cases - Case Overview - Action Dropdown - Email Case Manager
* Manage Cases - Case Overview - Action Dropdown - Export cases
* Manage Cases - Case Overview - Action Dropdown - Link cases
* Manage_Cases_-_Case_Overview_-_Action_Dropdown_-_Lock_case
* Manage Cases - Case Overview - Action Dropdown - Print Merge Document
* Manage Cases - Case Overview - Action Dropdown
* Manage Cases - Case Overview - People tab - Assign role to a client
* Manage Cases - Case Overview - People tab - Assign role to a non client
* Manage Cases - Case Overview - People tab - Case role dropdown
* Manage Cases - Case Overview - People tab - Remove role
* Manage Cases - Case Overview - …
> CATL-1253: [Backstop JS] - Manage Cases - Add remaining scenarios and other misc fixes

- CRM/Civicase/Page/ContactCaseTab.php
This PR fixes an issue where translations were not working 100% for the contact's page, specially when the translation was coming from a different module and not from Civicase.
Using the Awards tab as an example. The activity type name is not translated according to the case category rules.
The issue happens because the translation for case type categories are stored in the 'civicase-base' module (refer to the `replaceable-db-strings/activity-types.js` file on https://github.com/compucorp/uk.co.compucorp.civicase/pull/443) and these translations were not being loaded, only the ones for `civicase`. For normal pages, CiviCRM loads all translations for all modules (refer to https://github.com/civicrm/civicrm-core/blob/27a90ef6947628703d48d3f2fc565e14f154b8e8/Civi/Angular/Page/Modules.php#L89- …
> RSE-1081: Fix translations on Contact Page

- info.xml
**New Features**
- Added Github Action to run Javascript Unit Tests.
**Bug Fixes**
- Fixed a Database error in Pivot Chart.
- Fixed a bug, where the Manage Cases page broke, if cases with disabled case status's are present.
- Fixed a bug, where clicking on "Print application" gave access denied error.
**Updates for Developers**
- Fixed broken PHP Unit tests.
- Added a new civicase setting, which helps to move the "Other Cases" block to a new tab in Case Details.
> RSE-1121: Release v1.1.1

- CRM/Civicase/Form/CaseCategoryTypeCustomField.php
- CRM/Civicase/Helper/CaseCategory.php
- CRM/Civicase/Service/CaseCategoryCaseTypeCustomFieldExtends.php
- CRM/Civicase/Service/CaseCategoryCustomFieldExtends.php
- CRM/Civicase/Upgrader.php
This PR merges the work done for the Case Category Instance custom fields into the Awards instance branch.
https://github.com/compucorp/uk.co.compucorp.civicase/pull/530
https://github.com/compucorp/uk.co.compucorp.civicase/pull/460
> RSE-647: Case Category Instance Custom Fields

- ang/civicase/case/contact-case-tab/directives/contact-case-tab-case-details.directive.html
This PR changes the order of the activities displayed on the Case Card.
The order of the activities was changed.
> CATL-1504: Change Case Card Activities order

- info.xml
* Cases can be searched by ID when moving, copying, or linking them.
* File activity tags are cleared after uploading a file.
* On Contact Case Tab, Open Cases, Resolved Cases, and Other Cases sections, the "Next Milestone" field has now been replaced by "Last activity". The date of the last activity has also been added to the case.
* On the Case Card, the "Last Activity" field comes first, and the "Next Activity" comes second.
* The file upload subject is now required on the Case's files tab.
> CPS-283: Release v1.4.0

- info.xml
* Move client to next line in Small Screens https://github.com/compucorp/uk.co.compucorp.civicase/pull/547
* The case tags fields design has been improved https://github.com/compucorp/uk.co.compucorp.civicase/pull/549
* Performance has been improved for multiple areas of the application https://github.com/compucorp/uk.co.compucorp.civicase/pull/551
* Fixed permission error in Case Files Tab while adding tags https://github.com/compucorp/uk.co.compucorp.civicase/pull/545 and in the case tag's selection https://github.com/compucorp/uk.co.compucorp.civicase/pull/549
* Fixed the height calculation for inline fields https://github.com/compucorp/uk.co.compucorp.civicase/pull/550
* Removed title element when displaying the contact's full name on the activities list …
> CPS-301: Release v1.6.0

- info.xml
- Add a setting to enforce only one active case role per relationship type for a case https://github.com/compucorp/uk.co.compucorp.civicase/pull/552
- Increase visibility of tags across site https://github.com/compucorp/uk.co.compucorp.civicase/pull/553
- Open Case in focused mode when navigating from contact case tab to manage cases https://github.com/compucorp/uk.co.compucorp.civicase/pull/552
> CPS-305: Release v1.7.0

- CRM/Civicase/BAO/Query/CaseCategory.php
Resolves the issue in sending emails through the actions menu after doing a contacts advance search by non admin users.
Previously as soon as a non admin user clicked on 'Email - send now (to 50 or less)' option from the actions dropdown after performing an advance search, user will see an error. It can be seen in following video
Now emails can be send from the advance search page by any user who has relevant permissions to access advance search page and send emails from there
We have a logic in 'CRM/Civicase/BAO/Query/CaseCategory.php' file which is responsible of reducing contacts in a search to only those contacts which are related to cases in the case type category to which currently logged in users have access to. For example if current user has access to only awards and prospects …
> CPS-294: Resolve Email Sending Issue In Advance Search

- info.xml
**New Features**
* Users can create case categories for applicant management and case management instance. [RSE-1118](https://github.com/compucorp/uk.co.compucorp.civicase/pull/539).
**Bug Fixes**
* Fixed a bug where users were not able to send emails from advance search. [CPS-294](https://github.com/compucorp/uk.co.compucorp.civicase/pull/573).
**Developer Updates**
* npmrc filename was fixed. [CPS-338](https://github.com/compucorp/uk.co.compucorp.civicase/pull/583).
> CPS-335: Release v1.9.1

- ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
- ang/workflow/action-links/controllers/workflow-edit.controller.js
- ang/workflow/action-links/directives/workflow-list-edit-action.html
As part of this PR, the Edit Link functionality has been implemented in Workflow list page.
1. Created `WorkflowEditController` to implement the Edit Link functionality.
> RSE-1411: Implement Edit Link redirect

- ang/test/workflow/directives/workflow-list.directive.spec.js
- ang/workflow/directives/workflow-list.directive.html
- ang/workflow/directives/workflow-list.directive.js
Show empty message in Manage Workflows page when no case types are present
1. Added empty text in `ang/workflow/directives/workflow-list.directive.html`.
> RSE-1423: Show empty message when no case types are present

- CRM/Civicase/Helper/InstanceCustomGroupPostProcess.php
- CRM/Civicase/Hook/PageRun/CaseCategoryCustomGroupListing.php
- CRM/Civicase/Hook/Post/UpdateCaseTypeListForCaseCategoryCustomGroup.php
- CRM/Civicase/Service/BaseCaseTypePostProcessor.php
- CRM/Civicase/Service/BaseCustomGroupPostProcessor.php
- CRM/Civicase/Service/CaseCategoryInstanceUtils.php
- CRM/Civicase/Service/CaseManagementCaseTypePostProcessor.php
- CRM/Civicase/Service/CaseManagementCustomGroupPostProcessor.php
- CRM/Civicase/Service/CaseTypeCategoryEventHandler.php
This PR is a complimentary PR for https://github.com/compucorp/uk.co.compucorp.civiawards/pull/140 and basically optmizes code by moving some logic into the base class so it can be used by extending classes and some other minor fixes.
Optimization not done
A noteworthy functionality added is the `getCustomGroupEntityTypesFunction` function added to the base `CaseCategoryInstanceUtils` class that allows extending case category instance classes to provide function for fetching entity types for the case category custom group entity when available. For the CaseManagement instance, this function is not really needed but is useful for the Applicant management instance as it is used to fetch the Award subtypes list.
> RSE-1374: Code Optimization.

- info.xml
**New Features**
* RSE-44: Manage Workflow Functionality #609
* RSE-1400: Workflows List page + Misc Improvements https://github.com/compucorp/uk.co.compucorp.civicase/pull/594
* RSE-1411: Implement Edit Link redirect https://github.com/compucorp/uk.co.compucorp.civicase/pull/598
* RSE-1412: Duplicate link functionality https://github.com/compucorp/uk.co.compucorp.civicase/pull/599
* RSE-1375: Create New Permissions to access Workflows List page https://github.com/compucorp/uk.co.compucorp.civicase/pull/603
* RSE-1373: Use Category Instance Related Classes In Custom Group Related Hooks https://github.com/compucorp/uk.co.compucorp.civicase/pull/612
* RSE-1423: Show empty message when no case types are present #615
* RSE-1374: Code Optimization. #616
* RSE-1380: Add "Manage Workflows" Menu …
> CPS-375: Release v1.9.3

- info.xml
**Enhancements**
* CATL-1876: Query optimization for handling contact involved filter. #624
**Bug Fixes**
* RSE-1469: Disallow space in category name when creating a case type category for now as this causes some issues with creating custom fields for case categories. A proper fix will be done later. #622
> CPS-379: Release v1.9.4

- CRM/Civicase/Hook/BuildForm/PdfFormButtonsLabelChange.php
- js/create-pdf-form.js
As part of this PR, a popup has been created where user can enter a filename before downloading PDF.
This is dependent on https://github.com/civicrm/civicrm-core/pull/18924
In `js/create-pdf-form.js`, implemented logic to create the new popup.
> CATL-1938: PDF Download Filename popup

- info.xml
**Bug Fixes**
- Fix Bug In Fetching Webform Client ID
> CPS-389: Release v1.9.6

- ang/test/workflow/action-links/controllers/workflow-edit.controller.spec.js
- ang/test/workflow/services/case-management-workflow.service.spec.js
- ang/workflow/action-links/controllers/workflow-edit.controller.js
- ang/workflow/action-links/directives/workflow-list-edit-action.html
- ang/workflow/services/case-management-workflow.service.js
As part of this PR, support for separate "Edit Workflow" page for individual instance has been added.
There are no UI changes for Edit Workflow page(for Case Management instance).
In `CaseManagementWorkflow` service, added a `getEditWorkflowURL` function, which returns the url.
> RSE-1554: Support for separate "Edit Workflow" page for individual instance

- info.xml
- Add Create new button to Workflow list page #651
- Add PHP unit tests for CaseCategoryInstance class #657
- Limit Query Result To Accessible Case Type Categories #666
- Support for separate "Edit Workflow" page for individual instance #652
- Fix Issue With Search By Case Roles Not Returning Results #658
- Fix Mysql8 Reserved Word Issue #664
- Fix Delete Activity Bug #661
- Fix Issue while resuming draft #668
- Fix Bug With Recent Communication Block #669
- Fix Bug Downloading All Files On Awards #672
> CPS-438: Release v1.9.9

- info.xml
* RSE-1600: Support for instance specific Action Items #673
* CATL-1990: Limit Recipient And Cc/Bcc Fields To Only The Selected Contacts #650
* RSE-881: Show disabled cases #681
* CATL-2046: Token Tree Widget #689
* CPS-403: Fix Deprecated Case Permission #676
* CPS-402: Fix Avatar Initials #655
* CPS-366: Fix Custom Group Ordering #683
* RSE-1565: Fix logic for showing Milestone Activities #682
* CATL-1948: Fix missing end dates #665
* CPS-450: Fix Email Draft Forms #690
* CPS-409: Add tests for CategoryFromUrl class #663
> CPS-449: Release v1.10.0-rc

- CRM/Civicase/Form/Report/BaseExtendedReport.php
This pr resolves a bug in pivot report which occurred when you have a matching case role names.
Selecting a case role fields whose name matches another case role results in an error
Above error is resolved
There were two roles one was `solicitor` and other was `criminal solicitor` the criminal solicitor has solicitor in it as well that was the reason for the error in the `CRM/Civicase/Form/Report/BaseExtendedReport.php`  as it checks a particular string that contained case role in it and based on the result a new table was joined so this check resulted in an error when there are matching case role names.
> CATL-2084: Fix Report Case Role Bug

- info.xml
- Add Pagination to Manage Workflow and Dashboard Page #692
- Hide New Case Type button on Case Type list #716
- Add Tests For Token Tree Work #700
- Awards Payments Management #704
> CPS-471: Release v1.12.0

- js/token-tree.js
This PR reverts the changes from https://github.com/compucorp/uk.co.compucorp.civicase/pull/759. As it has moved to https://github.com/civicrm/org.civicrm.shoreditch/pull/513.
> ACUSPRT-81: Revert icons

- ang/civicase/contact-case-tab/directives/contact-case-tab.directive.html
The Add Case button was not working in Contact Case tab. This PR fixes the same.
Add Case button did not work.
The Param for Add Case Service was not updated.
> CPS-573: Fix Add case

- README.md
As part of this PR, the correct supported CiviCRM and PHP versions has been updated in the ReadMe file.
> CPS-701: Fix Technical Requirements

- README.md
- info.xml
Similar to what I did in Membershipextras extension, I am here updating the readme and the info.xml files to be more clear on which version(s) of CiviCRM we are supporting.
> MAE-497: Improve CiviCRM compatibility details

- CRM/Civicase/XMLProcessor/Report.php
This PR fixes the issue preventing a user from printing activities using the bulk action option.
Unable to print the activity report.
https://user-images.githubusercontent.com/85277674/209637921-c47608fc-c55f-45b7-9d73-8bcbb3af1c77.mp4
The user is able to print activity reports.
The `getActivities` method in `CRM_Civicase_XMLProcessor_Report` has more parameters than that of the overridden class `CRM_Case_XMLProcessor_Report` this was allowed in PHP versions prior to PHP8.0.
https://github.com/compucorp/uk.co.compucorp.civicase/blob/4045b6003a32465ec0e12a771673b741a5434575/CRM/Civicase/XMLProcessor/Report.php#L13
But causes a fatal error in PHP 8+.
```
Fatal error: Declaration of CRM_Civicase_XMLProcessor_Report::getActivities($clientID, $caseID, array $activityTypes, array &$activities, …
```
> MAE-999: Fix issue preventing user from creating activity report

- ang/civicase-features/quotations/directives/quotations-view.directive.html
- ang/civicase-features/quotations/directives/quotations-view.directive.js
This PR introduces the following changes
- Improves the single quotation view UI
- Links contact name to the contact dashboard
- Open the quotation tab when a case ID is clicked from the quotation view
The quotation view opens in a popup
The quotation view opens on a standalone page
> BTHAB-105: Improve single quotation view UI

- .github/workflows/unit-test.yml
- ang/civicase/shared/directives/file-uploader.directive.js
- ang/test/civicase/case/actions/services/go-to-webforms-case-action.service.spec.js
This pull request validates case files before uploading to make sure they are not empty.
It is possible for a user to upload a file that has zero bytes.
It is not possible for a user to upload a file with zero bytes.
This PR also resolves the issues with failing test cases
> NEUSPRT-217: Show error if user tries to upload empty file

- CRM/Civicase/Hook/BuildForm/AddEntityReferenceToCustomField.php
- ang/civicase-features/invoices/directives/invoices-list.directive.html
- ang/civicase-features/invoices/directives/invoices-list.directive.js
- ang/civicase-features/quotations/directives/quotations-create.directive.js
- ang/civicase-features/quotations/directives/quotations-list.directive.js
- js/contribution-entityref-field.js
This PR adds a button to create new invoice to the quotation invoice list page.
> BTHAB-145: Add button to create invoice

- Civi/Api4/Action/CaseSalesOrder/SalesOrderSaveAction.php
- ang/civicase-features/quotations/directives/quotations-create.directive.js
- tests/phpunit/Civi/Api4/CaseSalesOrder/SalesOrderSaveActionTest.php
This PR ensures the line item subtotal amount doesn't exceed the product cost price; (If the product's actual price is set)
No validation rule exists on the quotes for the capped amount when set
A validation rule exists on the quotes for products with a capped amount
> BTHAB-202: Ensure the quote product price doesnt exceed the max price

- ang/civicase-features/quotations/directives/quotations-create.directive.js
Use current membership in discount calculation
> BTHAB-263: Use current membership in discount calculation

- CRM/Civicase/Setup/Manage/CaseSalesOrderStatusManager.php
This pr adds the **Deposit Paid** status for quotations
> BTHAB-183: Add deposit paid status for quotations

- info.xml
Bump version for 4.0.1 release
> COMCL-505: Bump version for 4.0.1 release

- info.xml
Bump version for 4.1.0 release
> COMCL-564: Bump version

- ang/civicase.ang.php
This pr fixes an issue due to which the button for creating new case was not visible
> COMCL-620: Fix Add Case Button Issue

- CRM/Civicase/Hook/BuildForm/AddStyleFieldToCaseCustomGroups.php
- js/custom-group-form.js
This pr fixes an issue that restricted users from creating new custom field set.
> COMCL-649: Fix Custom Field Set Page

- js/contribution-entityref-field.js
This pr fixes the layout issues for new contribution page.
> COMCL-674: Fix New Contribution Page's Layout

- ang/civicase/case/search/directives/search.directive.js
- ang/civicase/dashboard/directives/dashboard.directive.js
- ang/test/civicase/case/search/directives/search.directive.spec.js
- ang/test/civicase/dashboard/directives/dashboard.directive.spec.js
This pr fixes a bug in searching cases through different filters on dashboard.
> COMCL-709: Fix Search On Case Dashboard

- info.xml
Bump version for 4.1.1 release
> COMCL-795: Bump version for 4.1.1 release

- CRM/Civicase/Hook/ValidateForm/SendBulkEmail.php
Prevent sending repeating bulk mail for selected contacts
Two emails are sent to each of the recipients
One email is sent to each of the recipients
> COMCL-856: Prevent sending repeating bulk mail for selected contacts

- CRM/Civicase/Service/CaseSalesOrderOpportunityCalculator.php
- js/contribution-entityref-field.js
- js/sales-order-contribution.js
- templates/CRM/Civicase/Form/CaseSalesOrderContributionCreate.tpl
APply fixes from this PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/1038 for CiviCRM 5.75
> COMCL-861: Apply Quotes to order Fixes

- CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php
This pr fixes a bug in case category updation.
> NEU-67: Fix Case Category Updation

- info.xml
> COMCL-921: Merge Rc Branch To Master

- templates/CRM/Civicase/Form/CaseSalesOrderDelete.tpl
- templates/CRM/Civicase/Page/CaseSalesOrder.tpl
This pr fixes errors that arised when smarty engine was upgraded to version 4.
> COMCL-954: Add Fixes For Smarty4 Upgrade

- ang/civicase/activity/feed/directives/activity-feed.directive.js
This PR refactors the activity feed rendering logic to ensure that each activity is correctly associated with its corresponding case ID if neccessary. By introducing a dedicated callback function, we guarantee that the `caseId` is explicitly passed to the `formatActivity` function during iteration, maintaining data integrity and consistency.
Previously, activities were formatted using `_.each` with the `formatActivity` function directly
```js
var newActivities = _.each(result[0].acts.values, formatActivity;
```
However, this approach did not pass the correct `caseId` to the `formatActivity` function, leading to incorrect case associations, as the item index was assumed to be the case ID.
- *Understanding `_.each`*: The `_.each` function in Underscore.js is designed to iterate over …
> RSESPRT-349: Ensure activity feed is formatted with correct caseID

- CRM/Civicase/Api/Wrapper/TagFilter.php
This PR fixes an issue that did not allow user to create the cases as user was presented with an error screen instead of case create form, the issue was introduced in this pr https://github.com/compucorp/uk.co.compucorp.civicase/pull/1080
> NEUSPRT-469: Fix create case

- info.xml
This PR bumps the extension version.
> COMCL-1085: Bump Version

- ang/civicase-base/services/contacts-cache.service.js
- ang/civicase/case/details/file-tab/directives/case-details-file-tab.directive.js
- ang/civicase/contact/directives/contact-card.directive.js
- ang/civicase/dashboard/directives/dashboard-tab.directive.js
- api/v3/Case/Getdetails.php
- api/v3/Case/Getfiles.php
- api/v3/Case/Getstats.php
This PR backports critical performance optimizations and bug fixes from the NEU-121, NEU-120, NEU-118, and NEUSPRT-492. These changes significantly improve CiviCase dashboard and Files tab performance while fixing tag display and filtering issues.
- **Dashboard Performance**: Eliminated N+1 query patterns in case dashboard loading
- **Contact Caching**: Improved contact information caching to reduce redundant API calls
- **Files Tab**: Optimized file loading queries with better JOIN strategies
- **Case Details**: Reduced query complexity in GetDetails API
- **Tag Display**: Fixed tag colors not showing correctly in activity cards
- **Tag Filtering**: Resolved issues with multiple tag filtering using INNER JOIN for better performance
- **Star Display**: Restored star/bookmark functionality …
> NEU-122: Backport: Performance Optimizations
